### ISSUE TITLE
How to help/contribute?

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#1]
Is there a list somewhere with details what needs to be done?
Or where one I start, if I want to help contribute here?

**Comment by snowleopard** [comment]
Hey Moritz! I've been interrupted in the middle of a big refactoring, and I believe it would be better to wait until a first version is complete and pushed to the GHC tree. Once that is done we will come up with a list of things that need to be done and it will be easier to contribute for everyone.

I hope to come back to the project next week and hopefully will have some updates in mid-April.

**Comment by angerman** [comment]
Hey Andrey! Very much looking forward to it!

**Comment by snowleopard** [comment]
A quick update: the next Shaking up GHC project meeting is scheduled on end of April. Hopefully, we'll have some news shortly after that.

**Comment by snowleopard** [comment]
...and the result of the meeting: we decided to do another major refactoring, so a stable version is further delayed. On the bright side, we have a clearer picture of the final goal.

**Comment by bgamari** [comment]
What is the status of this effort?

**Comment by snowleopard** [comment]
The refactoring I mentioned in the previous comment is now complete and I can build most of GHC 7.11. There are still a few bits and pieces for which I rely on the old build system, so it is premature to put this into the GHC tree. 

Progress has been slow in the last two months for personal reasons, but I hope to catch up over the Xmas break.

**Comment by angerman** [comment]
Let me know when you have the list of items. I'm still inclined to help.

**Comment by snowleopard** [comment]
Awesome, thanks! I'll be in touch.

**Comment by bgamari** [comment]
Great news!

**Comment by snowleopard** [comment]
@angerman I've added a note on how to contribute: https://github.com/snowleopard/shaking-up-ghc#how-to-contribute.

The codebase is very turbulent at the moment but please go ahead and try it you like!

**Comment by quchen** [comment]
@snowleopard are you on IRC or something? I'm always getting third-party information about this really nice project, and it's quite hard to ask about current bugs this way. (I'm struggling with the "no rule for Haddock" issue right now and have noone to talk to, for example.)

**Comment by snowleopard** [comment]
@quchen Thanks! I'm glad people are interested in the project although I'm embarrassed by current state of the codebase. I'll be happy to chat in Skype (my handle is andrey.mokhov) at some point, but I won't have time today unfortunately. Feel free to get in touch by email: andrey.mokhov@gmail.com.

By the way, I believe I fixed the `haddock` issue -- see #14.
