### ISSUE TITLE
Need some way to verbosely show commands executed

### ISSUE THREAD

**Issue by bgamari** [snowleopard/shaking-up-ghc#10]
Currently there is no way to convince the build system to dump the full command-lines that it is executing. This is an extremely useful thing to be able to do when things go awry.

**Comment by snowleopard** [comment]
Done: f48da18.

Set `verboseCommands = return True` in `Settings/User.hs` to show all commands, or `verboseCommands = package ghcPrim` or `verboseCommands = builder GhcCabal` etc. to control the setting more accurately.

**Comment by bgamari** [comment]
Brilliant.
