### ISSUE TITLE
Travis build fails on integer-gmp

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#103]
Excerpt from https://s3.amazonaws.com/archive.travis-ci.org/jobs/100326285/log.txt:
```
Error when running Shake build system:
* utils/compare_sizes/stage1/build/tmp/compareSizes
* libraries/integer-gmp/stage1/build/libHSinteger-gmp-1.0.0.1.a
* libraries/integer-gmp/stage1/build/cbits/wrappers.o
* OracleQ (DependenciesKey ("libraries/integer-gmp/stage1/build/.dependencies","libraries/integer-gmp/stage1/build/cbits/wrappers.o"))
* libraries/integer-gmp/stage1/build/.dependencies
* libraries/integer-gmp/stage1/build/cbits/wrappers.c.deps
* libraries/integer-gmp/gmp/gmp.h
* libraries/integer-gmp/gmp/libgmp.a
user error (Development.Shake.cmd, system command failed
Command: make -C libraries/integer-gmp/gmp/gmpbuild MAKEFLAGS=
```

**Comment by snowleopard** [comment]
This is what `make` complains about:
```
../libtool: 1581: ../libtool: preserve_args+= --tag CC: not found
../libtool: 1: eval: base_compile+= /usr/bin/gcc: not found
../libtool: 1: eval: base_compile+= -std=gnu99: not found
../libtool: 1: eval: base_compile+= -DHAVE_CONFIG_H: not found
../libtool: 1: eval: base_compile+= -I.: not found
../libtool: 1: eval: base_compile+= -I..: not found
../libtool: 1: eval: base_compile+= -D__GMP_WITHIN_GMP: not found
../libtool: 1: eval: base_compile+= -I..: not found
../libtool: 1: eval: base_compile+= -DOPERATION_fib_table: not found
../libtool: 1: eval: base_compile+= -O2: not found
../libtool: 1: eval: base_compile+= -pedantic: not found
../libtool: 1: eval: base_compile+= -fPIC: not found
../libtool: 1: eval: base_compile+= -m64: not found
../libtool: 1: eval: base_compile+= -mtune=k8: not found
../libtool: 1: eval: base_compile+= -march=k8: not found
../libtool: 1: eval: base_compile+= -c: not found
libtool: compile: you must specify a compilation command
libtool: compile: Try `libtool --help --mode=compile' for more information.
make[2]: *** [fib_table.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

**Comment by olsner** [comment]
I also ran into this when building on Ubuntu. The in-tree gmp is failing because its generated libtool script is using bashisms not available in plain /bin/sh.

integer-gmp should just link against the system-installed libgmp rather than building its own in-tree version when available. In the makefiles, integer-gmp's configure script detects if libgmp is installed and sets some variables via config.mk.in to do this.

**Comment by snowleopard** [comment]
Thanks @olsner! So, the solution is use a system `libgmp` if available. We had to add support for this anyway. Relevant files in the old build system are `libraries/integer-gmp/gmp/ghc.mk` and `libraries/integer-gmp/gmp/config.mk`.

**Comment by snowleopard** [comment]
Ok, now Travis gets stuck earlier:
```
Error when running Shake build system:
* inplace/bin/hp2ps
* utils/hp2ps/stage0/build/Curves.o
* OracleQ (DependenciesKey ("utils/hp2ps/stage0/build/.dependencies","utils/hp2ps/stage0/build/Curves.o"))
* utils/hp2ps/stage0/build/.dependencies
* utils/hp2ps/stage0/build/AreaBelow.c.deps
* libraries/integer-gmp/include/ghc-gmp.h
libraries/integer-gmp/gmp/config.mk: openFile: does not exist (No such file or directory)
```
Somehow we failed to produce `libraries/integer-gmp/gmp/config.mk`.

**Comment by snowleopard** [comment]
Hey! The last commit did it -- we've got a green light from Travis: https://travis-ci.org/snowleopard/shaking-up-ghc.

**Comment by snowleopard** [comment]
After a more careful inspection, something is wrong: although Shake terminated successfully we clearly didn't build everything we wanted (we didn't even finish stage0).

This sometimes happens with cyclic dependencies. @ndmitchell, is this a known issue?

**Comment by ndmitchell** [comment]
Definitely not known or expected.

**Comment by snowleopard** [comment]
Right, after another attempt we have the following:
* The travis installation doesn't have gmp framework: see `No GMP framework detected` in https://travis-ci.org/snowleopard/shaking-up-ghc/builds/100450076
* We then proceed to build gmp, and fail in the same manner as described at the top of this thread

If I understand correctly, we have two options:
* Install gmp framework on travis before running Shake and hope this will fix the issue
* Fix the libtool script. see https://github.com/snowleopard/shaking-up-ghc/issues/103#issuecomment-168989014

**Comment by snowleopard** [comment]
Looks like calling `make` with `MAKEFLAGS='LIBTOOL=bash\ libtool'` (see 375d41e) helps to overcome the libtool issue.

**Comment by snowleopard** [comment]
This issue appears to be solved! Fingers crossed travis build will be successful.

**Comment by angerman** [comment]
This breaks the build on os x :( See #112 and #114.
