### ISSUE TITLE
CI: Windows

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#110]
Setup CI for Windows builds using [AppVeyor](https://www.appveyor.com), which is Travis for Window I think.

**Comment by snowleopard** [comment]
OK, I'll look into this. Judging by @ndmitchell's `appveyor.yml` script for Shake this is not very difficult.

**Comment by snowleopard** [comment]
On a second thought, Shake is tested on Windows natively, while GHC is built in MSYS2. I'll google for possible CI solutions for Windows + MSYS2.

**Comment by ndmitchell** [comment]
Appveyor comes with MSYS2, and even if it doesn't, you can install it yourself - I don't think that will be a problem.

**Comment by ndmitchell** [comment]
In addition, Stack sets up MSYS2 properly and installs a GHC compiler - I don't think it should be too much more work to have Stack know how to compile GHC in some way. There's a ticket at https://github.com/commercialhaskell/stack/issues/1051 which might turn out to be the easiest route, and has lots of other benefits.

For info, if you did fix the Stack integration, things like https://github.com/ndmitchell/shake/issues/400 would be a lot less scary for me :)

**Comment by snowleopard** [comment]
> Appveyor comes with MSYS2

Cool, I'll check it out. My familiarity with CI is about zero, so it might take a while. But it's useful to learn.

> In addition, Stack sets up MSYS2 properly and installs a GHC compiler

Right, that's another interesting approach. But then I don't know much about Stack either (but I heard it's awesome). It will also take some time to learn :-)

**Comment by ndmitchell** [comment]
I might be able to help on the Stack side, since that's probably the way I'll have a go at following your instructions.

**Comment by snowleopard** [comment]
Found this on `appveyor` website (https://www.appveyor.com/pricing):
```
> Are there any build time restrictions?
All plans have maximum build job execution time of 60 minutes.
```
At the moment we are already over 60 minutes on Travis, and we are still not building a lot of stuff (only vanilla way, no split objects, no haddock, etc.), so I guess `appveyor` is not an option.

Thoughts?

**Comment by ndmitchell** [comment]
Can you build a subset? Perhaps just stage0? That gives you some confidence that it works a bit.

**Comment by angerman** [comment]
I'd say, we should still give it a shot. Maybe it's faster on their machines? And if that still doesn't work, maybe talking to them helps ;)

**Comment by snowleopard** [comment]
OK, agreed. We'll try a full build first and then may start pruning what we build.

**Comment by ndmitchell** [comment]
I thought I'd take a crack at it building on top of Stack - all notes are approximate. Building on top of Stack seems like an easier way to go, because I hope the eventual GHC build instructions will be in terms of Stack one day. From a Windows shell do:

    stack exec -- pacman -S --noconfirm automake autoconf gcc perl binutils p7zip git tar patch
    git clone --recursive git://git.haskell.org/ghc.git
    cd ghc
    git clone https://github.com/snowleopard/shaking-up-ghc.git
    ren shaking-up-ghc shake-build
    stack exec -- perl boot

Start `C:\Users\ndmit_000\AppData\Local\Programs\stack\i386-windows\msys2-20150512\mingw32_shell.bat`:

    configure --enable-tarballs-autodownload
    cd shake-build
    ./build.bat -j

After a bit it freezes, seemingly piping echo through sed. Rerunning with `-j0 -VV` it gives the error:

    Error when running Shake build system:
    * utils/mkUserGuidePart/stage1/build/tmp/mkUserGuidePart.exe
    * OracleQ (PackageDataKey ("utils/mkUserGuidePart/stage1/package-data.mk","utils_mkUserGuidePart_stage1_C_SRCS"))
    * utils/mkUserGuidePart/stage1/package-data.mk
    * compiler/stage1/package-data.mk
    * libraries/integer-gmp/include/ghc-gmp.h
    user error (Development.Shake.cmd, system command failed
    Command: make -C libraries/integer-gmp/gmp/gmpbuild MAKEFLAGS=
    Exit code: 2
    Stderr:
    fib_table.c:1:0: warning: -fPIC ignored for target (all code is position independent)
     /* This file generated by gen-fib.c - DO NOT EDIT. */
     ^
    mp_bases.c:1:0: warning: -fPIC ignored for target (all code is position independent)
     /* This file generated by gen-bases.c - DO NOT EDIT. */
     ^
    add.c:1:0: warning: -fPIC ignored for target (all code is position independent)
     /* mpn_add - add mpn to mpn.
     ^
    add_1.c:1:0: warning: -fPIC ignored for target (all code is position independent)
     /* mpn_add_1 - add limb to mpn.
     ^
    /usr/bin/sed: -e expression #1, char 9: unterminated `s' command
    make[2]: *** [add_n.lo] Error 1
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2
    )

**Comment by snowleopard** [comment]
@ndmitchell Hmm, I'm actually building on mingw64, not mingw32, could it be the reason?

**Comment by ndmitchell** [comment]
Certainly possible. Heading to bed now but I'll have another go in the morning.

**Comment by snowleopard** [comment]
I keep hitting the following cabal error during `appveyor` builds:
```
bash -lc "cabal update -v3"
Config file path source is default config file.
Config file C:\Users\appveyor\AppData\Roaming\cabal\config not found.
Writing default configuration to
C:\Users\appveyor\AppData\Roaming\cabal\config
Downloading the latest package list from hackage.haskell.org
Sending:
GET /packages/archive/00-index.tar.gz HTTP/1.1
Host: hackage.haskell.org
User-Agent: cabal-install/1.22.0.0 (windows; i386)
 
Creating new connection to hackage.haskell.org
Command exited with code 6
```
The same happens when I run cabal outside bash but with a different exit code (not sure whether this matters). Any hints?

**Comment by snowleopard** [comment]
I think the above issue is related to https://github.com/commercialhaskell/stack/issues/457.

**Comment by ndmitchell** [comment]
I was using the MinGHC `make`. I added that to the `pacman` install and got further.

I still get an awful lot of:

    fits_sint.c:1:0: warning: -fPIC ignored for target (all code is position independent)

Seemingly for every file in libgmp.

**Comment by snowleopard** [comment]
@ndmitchell Hit by the `old-time` issue (https://github.com/ndmitchell/shake/issues/398) again:
```
[...]
old-time-1.1.0.3: download
old-time-1.1.0.3: configure
[...]
     [1 of 1] Compiling Main             ( C:\Users\appveyor\AppData\Local\Temp\1\stack2280\old-time-1.1.0.3\Setup.hs, C:\Users\appveyor\AppData\Local\Temp\1\stack2280\old-time-1.1.0.3\.stack-work\dist\2672c1f3\setup\Main.o )
    Linking C:\Users\appveyor\AppData\Local\Temp\1\stack2280\old-time-1.1.0.3\.stack-work\dist\2672c1f3\setup\setup.exe ...
    Configuring old-time-1.1.0.3...
    ./configure: line 560: 0: Bad file descriptor
Command exited with code 1
```

**Comment by ndmitchell** [comment]
In Stack the workaround is:

    echo "" | stack --no-terminal build

Basically, its trying to read from stdin, which is not connected. Try just the `echo "" |` part with Cabal?

**Comment by snowleopard** [comment]
I'm using stack. The command is `stack install alex happy shake ansi-terminal mtl`. Shall I simply add `echo "" |` in front?

**Comment by ndmitchell** [comment]
echo "" | stack --no-terminal install alex happy shake ansi-terminal mtl

**Comment by snowleopard** [comment]
Thanks! Testing on appveyor now.

> I still get an awful lot of:
fits_sint.c:1:0: warning: -fPIC ignored for target (all code is position independent)
Seemingly for every file in libgmp.

I also get these warnings. I tried to find how to silence them (apparently these warnings are pretty much useless), but didn't manage yet.

**Comment by ndmitchell** [comment]
Great, as long as my code is no worse than yours, I'm happy with that :) - continuing with the build now.

**Comment by ndmitchell** [comment]
I'm currently getting weird failures to download files from Appveyor on another project, it may be that Appveyor is having a wobble today and that investigating another day might be wise.

**Comment by snowleopard** [comment]
OK, we now have Windows CI testing build of stage1 compiler: https://ci.appveyor.com/project/snowleopard/shaking-up-ghc/build/1.0.133.

We're very close to the time limit of 1hr, so we may need to optimise the build further.

**Comment by ndmitchell** [comment]
For info, I figured out the steps to install using Stack on a fresh Windows build: http://neilmitchell.blogspot.co.uk/2016/03/compiling-ghc-on-windows.html

**Comment by snowleopard** [comment]
@ndmitchell Cool! What about using `--setup` to get rid of the `boot` and `configure` steps?

**Comment by ndmitchell** [comment]
I'm fairly certain most users will redo the final step after doing a git pull. If that line has `--setup` on it, then they'll end up redoing boot/configure every day, which is not a great experience. For the moment I thought I'd go explicit, and we can work on shaving some steps off later.

**Comment by ndmitchell** [comment]
@snowleopard - having this git repo as a submodule of GHC would be nice, since then you could skip one step. It seems making it a submodule isn't really a big deal, since people who don't care can ignore it.

**Comment by snowleopard** [comment]
@ndmitchell Just for info: the `--setup` flag no longer rebuilds things (it is no longer an `AlwaysRerun` rule). If someone wants to force a rebuild they now have to add `-B`, which I think is a saner behaviour.

Sure, making this repo a git submodule seems reasonable. This will also simplify CI scripts.

One question: the `stack.yaml` file seems to be a full of default settings. Is it really needed? Will anything break if you omit the `--stack-yaml=shake-build/stack.yaml` flags?

**Comment by ndmitchell** [comment]
Ah, that does seem simpler. Does setup also auto-download? Perhaps we should check the script in on my blog into the repo in Markdown, and also keep a "proposed future version" around as well (so I can redo the testing procedure from scratch each time). I wonder if `shake-build/build.bat setup` might be easier though, so there are still two steps - boot/configure and build separately? (My ultimate goal would be to eliminate the boot/configure, push them into Haskell, and fully integrate them - one day...)

Yes, the stack.yaml is required. It implicitly references the Cabal file, and it tells stack what modules to put in the package database. Pushing the stack.yaml one level up would simplify things though, since then it would implicitly pick up the right one. Maybe for after the final milestone.

**Comment by snowleopard** [comment]
> Does setup also auto-download?

Yes! More precisely, it runs the `mk/get-win32-tarballs.sh` script on Windows.

> Perhaps we should check the script in on my blog into the repo in Markdown

Good idea, do send a PR. This could go into the `doc` folder I guess.

Let's discuss the `shake-build/build.bat setup` idea next week.

> My ultimate goal would be to eliminate the boot/configure, push them into Haskell, and fully integrate them - one day...)

:+1: That will a good day!
