### ISSUE TITLE
Parallel builds fail

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#117]
I've had this multiple times now. Travis runs afoul of that as well :(
```
shakeArgsWith                         0.002s    0%                           
Function shake                        0.032s    0%                           
Database read                         0.005s    0%                           
With database                         0.000s    0%                           
Running rules                       816.570s   99%  =========================
Pool finished (25024 threads, 8 max)  0.000s    0%                           
Lint checking                         0.061s    0%                           
Total                               816.670s  100%                           
Lint checking error - 2 values have changed since being depended upon:
  Key:  shake-build/src/Rules/IntegerGmp.hs
  Old:  File {mod=0xD836CAD0,size=0x13A8,digest=NEQ}
  New:  File {mod=0xD957F240,size=0x13CC,digest=NEQ}
       
  Key:  doesDirectoryExist libraries/ghc-prim/stage1/build/autogen/GHC/
  Old:  False
  New:  True
```
@snowleopard, @ndmitchell, can anyone of you provide hints on how to go about figuring out where we broke our dependencies, and how to fix it?

**Comment by snowleopard** [comment]
Interesting, I'll deal with this.

**Comment by ndmitchell** [comment]
The second seems to be from https://github.com/snowleopard/shaking-up-ghc/blob/ae6f58daa17dd6ba6bc81cbd19cc1a4f3e082ae8/src/Rules/Library.hs#L83, it seems a better formulation would be to always do `getDirectoryFiles`, and skip the `doesDirectoryExist` test. However, it seems plausible both ways round.

@angerman, were you editing the file IntegerGmp while building? If so, the first lint error is expected and can be ignored.

**Comment by snowleopard** [comment]
Yes, the first one is due to editing the file during the build.

I believe the second one comes from here: https://github.com/snowleopard/shaking-up-ghc/blob/ae6f58daa17dd6ba6bc81cbd19cc1a4f3e082ae8/src/Oracles/ModuleFiles.hs#L48. I'm now thinking what to do about it.

> it seems a better formulation would be to always do getDirectoryFiles, and skip the doesDirectoryExist test

@ndmitchell I don't think we can do this: in some situations the folder does not exist: this depends on whether we actually build gmp in tree or use a system one. If the folder does not exist, `getDirectoryFiles` fails with an error.

**Comment by ndmitchell** [comment]
`getDirectoryFiles "" [integerGmpObjects -/- "*.o"]` will be fine whether it exists or not. In contrast, `getDirectoryFiles integerGmpObjects ["*.o"]` will require the directory to exist.

**Comment by snowleopard** [comment]
@ndmitchell Ah, indeed! Thanks, I simplified this now: ce8ffdb.

**Comment by snowleopard** [comment]
I think I found the issue. Fortunately it was just a missing order-only dependency on generated `ghcPrim` files: 41ecfdc. Let's see whether this fixes the issue.

**Comment by snowleopard** [comment]
Hurray, we have a green light from Travis! :tada:
