### ISSUE TITLE
Missing touchy

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#125]
Error when running Shake build system:
    * utils/compare_sizes/stage1/build/tmp/compareSizes.exe
    * libraries/time/stage1/build/HStime-1.6.o
    * libraries/time/stage1/build/Data/Time/Format/Locale.o
    * libraries/base/stage1/build/Prelude.hi
    * libraries/base/stage1/build/Prelude.o
    * libraries/base/stage1/build/System/IO.hi
    * libraries/base/stage1/build/System/IO.o
    * libraries/base/stage1/build/Control/Exception/Base.hi
    * libraries/base/stage1/build/Control/Exception/Base.o
    * libraries/base/stage1/build/GHC/Exception.hi
    * libraries/base/stage1/build/GHC/Exception.o
    * libraries/base/stage1/build/Data/Typeable.hi
    * libraries/base/stage1/build/Data/Typeable.o
    * libraries/base/stage1/build/Data/Typeable/Internal.hi
    * libraries/base/stage1/build/Data/Typeable/Internal.o
    * libraries/base/stage1/build/GHC/Word.hi
    * libraries/base/stage1/build/GHC/Word.o
    * libraries/base/stage1/build/GHC/Read.hi
    * libraries/base/stage1/build/GHC/Read.o
    * libraries/base/stage1/build/Text/ParserCombinators/ReadP.hi
    * libraries/base/stage1/build/Text/ParserCombinators/ReadP.o
    * libraries/base/stage1/build/Control/Monad/Fail.hi
    * libraries/base/stage1/build/Control/Monad/Fail.o
    * libraries/base/stage1/build/GHC/IO.hi-boot
    * libraries/base/stage1/build/GHC/IO.o-boot
    user error (Development.Shake.cmd, system command failed
    Command: inplace/bin/ghc-stage1.exe -hisuf hi -osuf o -hcsuf hc -static -hide-all-packages -no-user-package-db -this-package-key base-4.9.0.0 -package-id ghc-prim-0.5.0.0 -package-id integer-gmp-1.0.0.1 -package-id rts -i -ilibraries/base/stage1/build -ilibraries/base/stage1/build/autogen -ilibraries/base -Ilibraries/base/stage1/build -Ilibraries/base/stage1/build/autogen -Ilibraries/base/include -IC:\Neil\ghc\libraries\integer-gmp\include -IC:/Neil/ghc/rts/stage1/build -IC:/Neil/ghc/includes -IC:/Neil/ghc/includes/dist-derivedconstants/header -optP-include -optPlibraries/base/stage1/build/autogen/cabal_macros.h -this-package-key base -XHaskell2010 -optP-DOPTIMISE_INTEGER_GCD_LCM -odir libraries/base/stage1/build -hidir libraries/base/stage1/build -stubdir libraries/base/stage1/build -rtsopts -H32m -O2 -c libraries/base/GHC/IO.hs-boot -o libraries/base/stage1/build/GHC/IO.o-boot
    Exit code: 1
    Stderr:
    ghc-stage1.exe: could not execute: C:\Neil\ghc\inplace\lib/bin/touchy.exe
    )

Running `$ ./build.bat -j1 -VV inplace/lib/bin/touchy.exe` I get told there is no rule to build touchy.

I copied `touchy.exe` from a packaged GHC and continued.

**Comment by ndmitchell** [comment]
Windows 32bit

**Comment by snowleopard** [comment]
Confirmed. I use the same workaround, thanks for documenting the issue here.

I'm a bit confused why we need to build a separate program for this: GHC is supposed to be built in MSYS2, which does provide a standard `touch`. Can we ask GHC to use it instead?

**Comment by ndmitchell** [comment]
I suggest copying the hack to start with, and later deciding if we can get away without it. Note that GHC ships touchy in the installed version, so it may have further uses later on.

**Comment by snowleopard** [comment]
I decided to fix this now, because this will likely also be an issue on appveyor (#110).

**Comment by snowleopard** [comment]
@ndmitchell Please test if the fix works for you.

**Comment by snowleopard** [comment]
Ahh, touchy is naughty:
```
Error when running Shake build system:
* inplace/lib/bin/touchy
* utils/touchy/stage0/build/touchy.o
* OracleQ (DependenciesKey ("utils/touchy/stage0/build/.dependencies","utils/touchy/stage0/build/touchy.o"))
* utils/touchy/stage0/build/.dependencies
* utils/touchy/stage0/build/touchy.c.deps
user error (Development.Shake.cmd, system command failed
Command: /usr/bin/clang -E -MM -Iutils/touchy/stage0/build -Iutils/touchy/stage0/build/autogen -MF utils/touchy/stage0/build/touchy.c.deps -MT utils/touchy/stage0/build/touchy.o -x c utils/touchy/touchy.c
Exit code: 1
Stderr:
utils/touchy/touchy.c:6:2: error: "Win32-only, the platform you're using is supposed to have 'touch' already."
#error "Win32-only, the platform you're using is supposed to have 'touch' already."
```
I need to build it only on Windows. Easy to fix.

**Comment by snowleopard** [comment]
Now tested on Windows and Linux (successful Travis build: https://travis-ci.org/snowleopard/shaking-up-ghc/jobs/100820663)

**Comment by ndmitchell** [comment]
Works for me too.
