### ISSUE TITLE
Undefined reference to adjustorCode

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#126]
Windows 32bit.

    Error when running Shake build system:
    * utils/compare_sizes/stage1/build/tmp/compareSizes.exe
    user error (Development.Shake.cmd, system command failed
    Command: inplace/bin/ghc-stage1.exe -hisuf hi -osuf o -hcsuf hc -static -hide-all-packages -no-user-package-db -package-id base-4.9.0.0 -package-id directory-1.2.5.0 -package-id filepath-1.4.1.0 -i -iutils/compare_sizes/stage1/build -iutils/compare_sizes/stage1/build/autogen -iutils/compare_sizes -Iutils/compare_sizes/stage1/build -Iutils/compare_sizes/stage1/build/autogen -IC:\Neil\ghc\libraries\directory\include -IC:\Neil\ghc\libraries\time\lib/include -IC:\Neil\ghc\libraries\Win32\include -IC:\Neil\ghc\libraries\bytestring\include -IC:\Neil\ghc\libraries\base\include -IC:\Neil\ghc\libraries\integer-gmp\include -IC:/Neil/ghc/rts/stage1/build -IC:/Neil/ghc/includes -IC:/Neil/ghc/includes/dist-derivedconstants/header -optP-include -optPutils/compare_sizes/stage1/build/autogen/cabal_macros.h -XHaskell2010 -odir utils/compare_sizes/stage1/build -hidir utils/compare_sizes/stage1/build -stubdir utils/compare_sizes/stage1/build -rtsopts -H32m -O2 -no-auto-link-packages -optl-luser32 -optl-lgdi32 -optl-lwinmm -optl-ladvapi32 -optl-lshell32 -optl-lshfolder -optl-lwsock32 -optl-luser32 -optl-lshell32 -optl-lm -optl-lwsock32 -optl-lgdi32 -optl-lwinmm -optl-LC:\Neil\ghc\libraries\directory\stage1\build -optl-LC:\Neil\ghc\libraries\time\stage1\build -optl-LC:\Neil\ghc\libraries\filepath\stage1\build -optl-LC:\Neil\ghc\libraries\Win32\stage1\build -optl-LC:\Neil\ghc\libraries\bytestring\stage1\build -optl-LC:\Neil\ghc\libraries\deepseq\stage1\build -optl-LC:\Neil\ghc\libraries\array\stage1\build -optl-LC:\Neil\ghc\libraries\base\stage1\build -optl-LC:\Neil\ghc\libraries\integer-gmp\stage1\build -optl-LC:\Neil\ghc\libraries\ghc-prim\stage1\build -optl-LC:/Neil/ghc/rts/stage1/build utils/compare_sizes/stage1/build/Main.o -o utils/compare_sizes/stage1/build/tmp/compareSizes.exe
    Exit code: 1
    Stderr:
    C:/Neil/ghc/rts/stage1/build/libHSrts.a(Adjustor.o):Adjustor.c:(.text+0x6b): undefined reference to `adjustorCode'
    collect2.exe: error: ld returned 1 exit status
    `gcc.exe' failed in phase `Linker'. (Exit code: 1)

**Comment by snowleopard** [comment]
Right, this is something new to me.

File `src/Settings/Packages/Rts.hs` takes care of all options used when building various pieces of `rts`. Some of them are still not implemented and are commented out below the code. I can see that `Adjustor` actually needs special treatment:
```
 -- rts/Adjustor_CC_OPTS    += -Wno-strict-prototypes $(LIBFFI_CFLAGS)
```
Maybe this is the reason.

**Comment by ndmitchell** [comment]
From a quick grep I see that Adjustor is in assembly:

    rts/AdjustorAsm.S:adjustorCode:

I imagine that's part of it at least.

**Comment by snowleopard** [comment]
Oh, we still don't deal with `*.S` files in any way. I wonder why we didn't need this on Linux (Travis) or on my Windows installation.

**Comment by ndmitchell** [comment]
That does seem a bit weird - I don't see where else it could be getting adjustorCode from... Or maybe there are #ifdef's that only make it relevant on Windows 32bit.

**Comment by ndmitchell** [comment]
#if defined(i386_HOST_ARCH)
    extern void adjustorCode(void);

So only a 32bit issue.

**Comment by snowleopard** [comment]
@ndmitchell I've committed a first step towards a full solution. It covers only `*.S` files in `rts`. Could you please test?

**Comment by ndmitchell** [comment]
Works for me, managed a complete GHC build on 8 cores in 21 minutes.

**Comment by snowleopard** [comment]
Great! But strange: there are still a bunch of `*.S` files that I don't handle.

**Comment by ndmitchell** [comment]
I guess that's the only one required on Win 32.
