### ISSUE TITLE
Travis-CI: Why does the cache not work?

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#127]
Maybe I'm missing something, but it appears as if we run
```
cd ghc/shake-build && cabal install --only-dependencies
```
each and every time. Does `cabal` ignore the cache, or does the cache somehow not work?

**Comment by snowleopard** [comment]
Here is what I noticed at the end of a successful linux build: https://s3.amazonaws.com/archive.travis-ci.org/jobs/100807773/log.txt.
```
The command "./ghc/shake-build/build.sh -j --no-progress" exited with 0.
travis_fold:start:cache.2
store build cache
travis_time:start:0f68fcd7
travis_time:end:0f68fcd7:start=1452173571418164143,finish=1452173571421411991,duration=3247848
travis_time:start:0caacbd4
change detected:
/home/travis/.cabal/packages/hackage.haskell.org/00-index.cache
/home/travis/.cabal/packages/hackage.haskell.org/00-index.tar
/home/travis/.cabal/packages/hackage.haskell.org/00-index.tar.gz
/home/travis/.cabal/packages/hackage.haskell.org/00-index.tar.gz.etag


changes detected, packing new archive
.
uploading archive
travis_time:end:0caacbd4:start=1452173571425140895,finish=1452173580912109135,duration=9486968240
travis_fold:end:cache.2

Done. Your build exited with 0.
```

**Comment by quchen** [comment]
I've been wondering the same. The cache *should* simply upload stuff from the build, and download it before the next one again. In that case, Cabal shouldn't run again.

**Comment by angerman** [comment]
ok. *maybe* we do not produce a cache until we have a successful build, and as we did not have any successful mac build, we never produced any cache?

**Comment by snowleopard** [comment]
@angerman We now have a bunch of successful builds: https://travis-ci.org/snowleopard/shaking-up-ghc/builds.

**Comment by angerman** [comment]
Alright, it's not available for OS X yet. See https://github.com/travis-ci/travis-ci/issues/4011#issuecomment-120001089

**Comment by angerman** [comment]
So we can probably just close this.
