### ISSUE TITLE
Use the extra library

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#130]
A number of functions in Base.hs are very similar to ones in the extra library, for example chunksOfSize is [chunksOf](https://hackage.haskell.org/package/extra-1.4.3/docs/Data-List-Extra.html#v:chunksOf), replace is there as [replace](https://hackage.haskell.org/package/extra-1.4.3/docs/Data-List-Extra.html#v:replace), wordsWhen is [wordsBy](https://hackage.haskell.org/package/extra-1.4.3/docs/Data-List-Extra.html#v:wordsBy). I suggest you use the extra library because:

* It's a dependency of Shake, so you don't increase the transitive set of things that the build system depends on.
* It has barely any dependencies itself, so doesn't cause issues, e.g. with old-time or similar.
* It has lots of useful methods you might not have thought of abstracting, or which might not be useful for just this one project.
* Everything is tested and (to some extent) optimised.

If you decide to use it, I'll send a few pull requests switching things over. If you decide against it then that's fine too - keeping dependencies down is a good plan.

**Comment by snowleopard** [comment]
Actually we do use the `extra` library already, see `import Control.Monad.Extra` in `Base.hs` for functions like `whenM` etc. I think I just didn't manage to find the right functions.

So, please do create a pull request!

**Comment by angerman** [comment]
Ohh wow. Now I feel rather stupid for not finding `wordsBy`. :+1:

**Comment by angerman** [comment]
What happened to this? @ndmitchell you still on this, or should I give it a go?

**Comment by ndmitchell** [comment]
Go for it. I might get some time Tuesday, but happy for you to do it before then, or leave it to you if you prefer.

**Comment by angerman** [comment]
Alright, looking into this. `wordsBy` seems identical to `wordsWhen` and `replace` also do the same. (Except `Extra` defines a corner case as undefined, in which the `replace` in `Base` produces infinite amounts of data).

I'm not certain `chunksOf` and `chunksOfSize` are the same. But I also don't think `chunksOfSize` works as expected :(

As far as I understand `chunksOfSize` is suppose to take an array of arguments `:: String`, and ensure that the size of concatenated items does not exceed a given length, and then split the arguments accordingly, to produce sub lists for which `sum . map length` is less or equal to the given `size`. Whereas `chunksOf` simply cuts the input into chunks of the given size.

`chunksOfSize` however blows up if one of the elements in the list exceeds the given size.

```
chunksOfSize 10 ["foobarbaz", "foo", "bar", "baz", "queue"] === [["foobarbaz"],["foo","bar","baz"],["quux"]]
```
but
```
chunksOfSize 3 ["foobarbaz", "foo", "bar", "baz", "quux"] === [[],[],[],...
```

**Comment by ndmitchell** [comment]
Yep, chunksOf looks entirely different - I was mislead by the name.

**Comment by snowleopard** [comment]
> But I also don't think chunksOfSize works as expected :(
[...]
 chunksOfSize however blows up if one of the elements in the list exceeds the given size.

@angerman Well spotted! Shall we throw an error instead? I don't think we can produce any meaningful result in this situation. Is this blowup your only concern about the current implementation?

By the way, I think we better move `chunksOfSize` from `Base.hs` to `Settings/Builders/Ar.hs` as it is not used anywhere else.
