### ISSUE TITLE
Read User.hs values from external configuration file

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#132]
Assume I want to build ghc in two flavors. Now I could either copy User.hs and produce two versions that capture what I want, or we could allow to specify a configuration file, that is read. YAML maybe?
Thoughts?

**Comment by ndmitchell** [comment]
I think the design is that you should be able to make your Users file conditional on command line arguments, then you can have one Users file which operates in two different modes.

**Comment by angerman** [comment]
@ndmitchell care to explain a bit more?

I see two possible approaches:

- For each option in Users have a potential command line argument. This ends up being
  ```bash
  ./build.sh -arg1 -arg2 -arg3 -arg4 -arg5 ...
  ```

- Allow for a configuration file (e.g. similar to the `Flavour`s in the `mk/build.mk` files are). And then allow something like the following:
  ```bash
  ./build.sh -flavour quick
  # or
  ./build.sh -flavour bench
  # or
  ./build.sh -flavour validate
  ```
  where there is a folder `flavours` that contains some plain text configuration file (e.g. `yaml` format.)

Or a hybrid:
```bash
./build.sh -flavour quick -opt-ghc=-Wall
```
or something.

**Comment by ndmitchell** [comment]
@snowleopard will know better than me, but I think the plan is to allow you to write in Users:

    when (flavour "quick") $ setFlags cc "-O0"
    when (flavour "sse") $ setFlags cc "-msse2"; setFlags hs "-fmsse2"

Not the right syntax, but it should give a hint about the intention. That way you can do full customisations in User, and select which package of optimisations you want from the command line.

**Comment by angerman** [comment]
@ndmitchell thanks for clearing that up. The design space here seems to be quite big :-)

**Comment by snowleopard** [comment]
I agree with @ndmitchell's comment: the plan is to put all logic into `Settings/User.hs` and also perhaps `Settings/Default.hs` and use command line to pass flags to this logic.

We can start tackling this issue by coming up with a clean way to pass command line flags to `Settings/User.hs`. There may be nasty import loops along the way.

**Comment by angerman** [comment]
I'll add support for command line flags in #134 anyway, so maybe we can just build on that then.

**Comment by snowleopard** [comment]
@angerman Yep, sounds good. Although in case of #134 we don't necessarily need to pass command line flags through to `User.hs`, we just need to deliver them to `renderBox` somehow, which sounds easier.

**Comment by snowleopard** [comment]
Thanks to @angerman's `CmdLineFlag` it is trivial to read command line flags in `User.hs`. I demonstrated this in the above commit, which adds `--split-objects` flag enabling the generation of split objects.

I therefore close this issue.
