### ISSUE TITLE
Add option to add flags onto to certain packages

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#133]
Say I'm building GHC, but I'm specifically interested in a certain package. I might want to pass arguments  / flags onto that specific package. (E.g. `-Wall`), but not to every package.

**Comment by snowleopard** [comment]
This can already be controlled very precisely in `Settings/User.hs`, for example:
```haskell
userArgs = mconcat
    [ ...
    , package base ? builderGhc ? arg "-Wall"
    , stage1 ? file "//Data/Binary.*" ? remove ["-O2"]
    , ... ]
```
If you change `userArgs` and run the build script, _all and only affected rules will be rerun automatically_.

In future it will also be possible to control settings from command line, as discussed in #132.

Let me know if you still think this is an issue, but it looks like this can be closed.

**Comment by angerman** [comment]
This needs to be documented! @quchen you up for the task?
