### ISSUE TITLE
Advanced render box styles

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#134]
Currently, when using render box, we are bound to use five lines for each invocation. I propose we abstract render box in a way such that we can either render the box as is right now, or produce a single line condensed output. E.g.
```
> Run Ghc Stage1 (package = gcc-bin) ghc/stage1/build.o (and 5 more) => inplace/lib/bin/ghc-stage2
```
And preferably let this be controlled through a `--style=short` or `--style=box` or similar. That way we could also reduce the logs travis produces.

**Comment by snowleopard** [comment]
Yay, the output style inventions continue! :+1:  
If we combine this proposal with @bgamari's one in #92 we get three potential styles already:
* `--style=normal`: the current implementation, default.
* `--style=brief`: the single line approach proposed here.
* `--style=pony`: @bgamari's messenger pony mode.

@angerman Feel free to self-assign :-)

**Comment by angerman** [comment]
It will need some rewiring though, such that the semantics of the box are captured to be formatted according to style.

**Comment by snowleopard** [comment]
I edited my comment: we actually have 4 styles if #135 is taken into account. I also think `--build-info` is probably a better name (this can be finalised later of course).

**Comment by angerman** [comment]
The big issue with `none` (#135) is, that you still want to capture enough output in case something goes horribly wrong,  so you have an idea where to look. For this the error messages need to be informative enough. This is going to be a fun issue. I suggest we go wit `--build-info` `normal`, `brief`, `pony` first and then try to see how to do `none`. I always wonder if `pony` would be the error case though ;-)

**Comment by snowleopard** [comment]
Yes, it's unclear at this point how to handle `none` properly.

By the way, I also added style `dot` in my comment to have everything in one place.

**Comment by angerman** [comment]
I'll add this. To first-shake, as I have some of this already working in a branch.

**Comment by snowleopard** [comment]
Surely this feature is nice to have, although I don't think it is critical for any milestone. However, if you feel you'll manage to complete this by `first-shake`, let's aim for this!

**Comment by angerman** [comment]
Well, I got this one and the documentation issue assign to me so far. I sure hope, I'll manage :-)

**Comment by snowleopard** [comment]
:+1:

**Comment by angerman** [comment]
This is mostly implemented in #154. Even @bgamari unicorn!

`dot` and `none` are going to be a bit tricky though, as we currently send `"."` and `""` down.  Yet `dot` should not send a newline, and `none` should actually be a no-op instead of an empty string.

Also there's some oracle accessibility issue, which I hope @ndmitchell will help me with.

**Comment by snowleopard** [comment]
I've reopened since it's still work in progress.

**Comment by angerman** [comment]
This is so going to be an easer egg :-)

We've also only covered `renderBox` and not the other *Info* we provide. My current plan of attack is:

- [ ] Figure out how to properly print nothing with `none`.
- [ ] See how we can convince shake not to produce a newline for `dot`.
- [ ] come up with a plan on how to handle other notification items we have, or if
      we can roll them up into a unified approach.

**Comment by ndmitchell** [comment]
I don't think putNormal can be convinced to print without the newline. You can just use putStrLn instead though.

**Comment by snowleopard** [comment]
Let me just copy Shake's implementation of `putNormal` here:
```haskell
putNormal :: String -> Action ()
putNormal = putWhen Normal

putWhen :: Verbosity -> String -> Action ()
putWhen v msg = do
    Global{..} <- Action getRO
    verb <- getVerbosity
    when (verb >= v) $
        liftIO $ globalOutput v msg
```
So I guess we could just substitute the `globalOutput` bit with our own print function.

**Comment by angerman** [comment]
I'll try to get this done today. This has become somewhat of an abomination that it was never intended to be.
