### ISSUE TITLE
Completely quiet build?

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#135]
As mentioned about `styles` in #134, can we tune the output such that there is *no* output, or maybe some progress indication (say, print a single "." for each event), and only have proper output if something breaks? So that logs are not so cluttered with success information, if one is interested only in the failures?

**Comment by snowleopard** [comment]
We are currently printing all build info using Shake's `putNormal`, see `src/Base.hs`.

@ndmitchell Is there a flag to pass to a Shake script that will silence all `putNormal` commands?

**Comment by angerman** [comment]
@snowleopard there is `-q`. Am I answering my own question? Ugh...

**Comment by angerman** [comment]
One still get's a lot of output from subcommands. And there's no indication if something is still happening. But maybe one could implement this in shake, such that a `.` is printed for each rule? @ndmitchell what do you think?
@snowleopard use `-q` and close this?

**Comment by snowleopard** [comment]
OK, let me close this: indeed `-q` is what I meant.

Regarding printing `.` for each command: this may be just another style `dot` to add to #134.

**Comment by ndmitchell** [comment]
There are general plans for Shake to have more concise output modes, see https://github.com/ndmitchell/shake/issues/18
