### ISSUE TITLE
Bootstrapping clean tree fails with message complaining about missing haddock

### ISSUE THREAD

**Issue by bgamari** [snowleopard/shaking-up-ghc#14]
Currently fails with,
```
$ make distclean
$ ./boot
$ ./configure
$ shake-build/build.sh -j4
Reading shake-build/cfg/system.config...
Error when running Shake build system:
* inplace/bin/haddock
Error, file does not exist and no rule available:
  inplace/bin/haddock
```
Perhaps this is fallout from fixing #5?

**Comment by snowleopard** [comment]
This is because stage2 is not handled properly at the moment. I added a separate issue about this: #15. 

I temporarily fixed this issue by building `haddock` and `ghtTags` in stage1: c720083.

**Comment by snowleopard** [comment]
I think we can close this issue. Feel free to reopen if the problem persists.
