### ISSUE TITLE
Ar blows up with split objs

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#141]
Separately noting down the `ar` issue from #138. 
```
/--------------------------------------------------------------------------------------------------------\
| Run Ar (stage = Stage1, package = template-haskell)                                                    |
|     input: libraries/template-haskell/stage1/build/Language/Haskell/TH_o_split/TH__1.o (and 5401 more) |
| => output: libraries/template-haskell/stage1/build/libHStemplate-haskell-2.11.0.0.a                    |
\--------------------------------------------------------------------------------------------------------/
```
that's simply too much for ar.

Looking through the make system. `SplitObjs` seems to be almost always set to `NO`. Except for perf, perf-llvm and perf-cross flavours. It is also disabled for all bootstrap packages.

**Comment by angerman** [comment]
As @ndmitchell mentioned in #138, one can use `ar` with a file. This is also apparently what the make system uses: all objects are put into a `.contents` files (e.g. `libHStemplate-haskell-2.11.0.0.a.contents`), which is then fed into `ar` using `xargs` before being deleted. E.g.
```
"xargs"  "/usr/bin/ar" clqs  libraries/template-haskell/dist-boot/build/libHStemplate-haskell-2.11.0.0.a < libraries/template-haskell/dist-boot/build/libHStemplate-haskell-2.11.0.0.a.contents
```

**Comment by ndmitchell** [comment]
Using xargs is not going via a file, it goes via the command line, albeit with some file redirection in the middle.

**Comment by angerman** [comment]
I guess the issue is that `ar` on `osx` at least doesn't support `@`.

I also wonder why we only provide `q`ick, and not `c` (archive silently) and `s` (add object-file index)?
`l` seems to be just ignored on `osx` and `linux`.

Interesting that we just hit the code with `chunksOfSize`, which is used in `arCmd`. Maybe we can get rid of the `useSuccessiveInvocations` function and of `chunksOfSize` as well, if we just go with `xargs` @snowleopard?

**Comment by ndmitchell** [comment]
Xargs does nothing to increase the limit. I suggest @ on platforms that support it and the other approach where not. Xargs is only to make make easier, not any fundamental reason.

**Comment by angerman** [comment]
Looking at `rules/build-package-way.mk`, where we find:
```
ifeq "$$($1_$2_ArSupportsAtFile)" "YES"
        $$(call cmd,$1_$2_AR) $$($1_$2_AR_OPTS) $$($1_$2_EXTRA_AR_ARGS) $$@ @$$@.contents
else
        "$$(XARGS)" $$(XARGS_OPTS) "$$($1_$2_AR)" $$($1_$2_AR_OPTS) $$($1_$2_EXTRA_AR_ARGS) $$@ < $$@.contents
endif
        $$(call removeFiles,$$@.contents)
```
I believe we can.

**Comment by ndmitchell** [comment]
Although note that Linux and Mac may have large enough command line buffers to not worry.

**Comment by angerman** [comment]
@ndmitchell hmm. I just ran into precisely this issue on mac `5402` arguments. Then, reading through the documentation for `xargs` makes me believe `useSuccessiveInvocations` is precisely what `xargs` does.

So we might find the issue lies with the computation of the chunk size?

**Comment by angerman** [comment]
Hmm... Ok.
```
-- Command lines have limited size on Windows. Since Windows 7 the limit is
-- 32768 characters (theoretically). In practice we use 31000 to leave some
-- breathing space for the builder's path & name, auxiliary flags, and other
-- overheads. Use this function to set limits for other OSs if necessary.
cmdLineLengthLimit :: Action Int
cmdLineLengthLimit = do
    windows <- windowsHost
    return $ if windows
             then 31000
             else 4194304 -- Cabal needs a bit more than 2MB!
```

**Comment by angerman** [comment]
Going through `xargs` hence just moves the computation of the command line length to `xargs`.

**Comment by angerman** [comment]
Another archeological find:
```
# On MSYS, building with SplitObjs=YES fails with
#   ar: Bad file number
# see #3201.  We need to specify a smaller max command-line size
# to work around it.  32767 doesn't work; 30000 does, but says
#     xargs: value for -s option should be < 28153
# so we now use 20000 to be comfortably below this bound
XARGS = xargs
ifeq "$(Windows_Host)" "YES"
XARGS_OPTS = -s 20000
endif
```
in `mk/config.mk`

**Comment by ndmitchell** [comment]
I didn't realise xargs did splitting, useful!

**Comment by angerman** [comment]
Digging through `aclocal.m4` we also find why we use only `q`.
```
# FP_PROG_AR_ARGS
# ---------------
# Sets fp_prog_ar_args to the arguments for ar and the output variable ArCmd
# to an invocation of ar including these arguments.
AC_DEFUN([FP_PROG_AR_ARGS],
[AC_REQUIRE([FP_PROG_AR_IS_GNU])
AC_CACHE_CHECK([for ar arguments], [fp_cv_prog_ar_args],
[
# GNU ar needs special treatment: it appears to have problems with
# object files with the same name if you use the 's' modifier, but
# simple 'ar q' works fine, and doesn't need a separate ranlib.
if test $fp_prog_ar_is_gnu = yes; then
  fp_cv_prog_ar_args="q"
else
  touch conftest.dummy
  for fp_var in clqsZ clqs cqs clq cq ; do
     rm -f conftest.a
     if "$fp_prog_ar" $fp_var conftest.a conftest.dummy > /dev/null 2> /dev/null; then
        fp_cv_prog_ar_args=$fp_var
        break
     fi
  done
  rm -f conftest*
  if test -z "$fp_cv_prog_ar_args"; then
    AC_MSG_ERROR([cannot figure out how to use your $fp_prog_ar])
  fi
fi])
fp_prog_ar_args=$fp_cv_prog_ar_args
AC_SUBST([ArCmd], ["$fp_prog_ar"])
AC_SUBST([ArArgs], ["$fp_prog_ar_args"])

])# FP_PROG_AR_ARGS
```

**Comment by angerman** [comment]
Alright. I think I know enough now. To try and fix this with `xargs`.

**Comment by angerman** [comment]
@ndmitchell mind me asking how to supply the `input` correctly with shake? Use `(StdIn ?)` or is there a different better approach? Using `<` is likely not what I'm looking for, I guess?

**Comment by ndmitchell** [comment]
Use Stdin.

**Comment by angerman** [comment]
Now, this took an interesting turn:
```
Error when running Shake build system:
* utils/compare_sizes/stage1/build/tmp/compareSizes
* libraries/ghc-prim/stage1/build/libHSghc-prim-0.5.0.0.a
user error (Development.Shake.cmd, system command failed
Command: xargs /usr/bin/ar q libraries/ghc-prim/stage1/build/libHSghc-prim-0.5.0.0.a
Exit code: 126
Stderr:
xargs: /usr/bin/ar: Argument list too long
)
```

**Comment by ndmitchell** [comment]
Now that is what I expected based on my understanding of xargs (which may indeed be wrong)

**Comment by angerman** [comment]
This however is what success with the make build:
```
"xargs"  "/usr/bin/ar" clqs  libraries/ghc-prim/dist-install/build/libHSghc-prim-0.5.0.0.a < libraries/ghc-prim/dist-install/build/libHSghc-prim-0.5.0.0.a.contents
```

I'm going to save the contents file this time for inspection.

**Comment by ndmitchell** [comment]
You also have different arguments to ar. Contents file is a good plan.

**Comment by angerman** [comment]
That was also my first hunch that maybe one of the other flags to `ar` would be responsible. Sadly though, that was not the case. So either the make system builds a pruned contents file, and somehow managed to wiggle into the argument length, or there's something else going on, which I do not yet have any idea how to track down.

**Comment by ndmitchell** [comment]
In our work build system we have a smart piece of code that picks the optimal directory to change to and then minimises the objects with shorter relative paths. Can save huge if all the prefixes are the same.

**Comment by angerman** [comment]
`libHSghc-prim-0.5.0.0.a.contents` contains `3651` lines.
and
`libHStemplate-haskell-2.11.0.0.a.contents` contains `5402` lines.
and the entries are qualified relative to the build directory (e.g. `libraries/tempalte-haskell/...`)

Hmm maybe `xarges` running through shake fails to obtain the proper ARG_MAX? Or maybe it makes a difference running through the shell? This is very strange.

**Comment by snowleopard** [comment]
So, let me summarise what happens here:
* `ar` doesn't support `@file` on OS X
* Withough `@file` we hit a command line limit on OS X

The first thing to is to change `cmdLineLengthLimit`: detect that we are running on OS X and return appropriate command line length limit. Function `useSuccessiveInvocations` should then take care of this. @angerman Have you tried this?

**Comment by angerman** [comment]
@snowleopard I am right now. But the fact that `ghc`'s `make` base build system used `xargs` successfully, and I could not with the `shake` base build system, piqued my curiosity. Though I must admit, I have failed to figure out what the reason ist.

We can compute the `cmdLineLengthLimit` if `getconf` is supported using `getconf ARG_MAX`. (`xargs` apparently subtracts `4096` for good measure).

For the record it's `262144` for me. And according to [1], also for most `bsd` systems.

[1]: http://serverfault.com/questions/69430/what-is-the-maximum-length-of-a-command-line-in-mac-os-x

**Comment by angerman** [comment]
Ok. this didn't work either.
```
cmdLineLengthLimit :: Action Int
cmdLineLengthLimit = do
    windows <- windowsHost
    return $ if windows
             then 31000
             else 262144 - 4096 -- 4194304 -- Cabal needs a bit more than 2MB!
```
yet
```
/---------------------------------------------------------------------------\
| Run Ar (stage = Stage1, package = ghc-prim)                               |
|     input: libraries/ghc-prim/stage1/build/cbits/atomic.o (and 3657 more) |
| => output: libraries/ghc-prim/stage1/build/libHSghc-prim-0.5.0.0.a        |
\---------------------------------------------------------------------------/
shakeArgsWith   0.002s    0%                           
Function shake  0.032s    0%                           
Database read   0.263s    5%  =                        
With database   0.016s    0%                           
Running rules   4.691s   93%  =========================
Total           5.004s  100%                           
Error when running Shake build system:
* utils/compare_sizes/stage1/build/tmp/compareSizes
* libraries/ghc-prim/stage1/build/libHSghc-prim-0.5.0.0.a
user error (Development.Shake.cmd, system command failed
Command: /usr/bin/ar q libraries/ghc-prim/stage1/build/libHSghc-prim-0.5.0.0.a libraries/ghc-prim/stage1/build/cbits/atomic.o libraries/ghc-prim/stage1/build/cbits/bswap.o libraries/ghc-prim/stage1/build/cbits/clz.o libraries/ghc-prim/stage1/build/cbits/ctz.o libraries/ghc-prim/stage1/build/cbits/debug.o libraries/ghc-prim/stage1/build/cbits/longlong.o libraries/ghc-prim/stage1/build/cbits/popcnt.o libraries/ghc-prim/stage1/build/cbits/word2float.o libraries/ghc-prim/stage1/build/GHC/CString_o_split/CString__1.o libraries/ghc-prim/stage1/build/GHC/CString_o_split/CString__2.o [...] libraries/ghc-prim/stage1/build/GHC/Types_o_split/Types__9.o
/usr/bin/ar: createProcess: runInteractiveProcess: exec: resource exhausted (Argument list too long))
```

**Comment by snowleopard** [comment]
@angerman Can you check the actual length of the command line we use? Maybe play with the limit, e.g binary search the limit that works?

**Comment by angerman** [comment]
Well, well, well... something is *really* weird:
```
/---------------------------------------------------------------------------\
| Run Ar (stage = Stage1, package = ghc-prim)                               |
|     input: libraries/ghc-prim/stage1/build/cbits/atomic.o (and 3657 more) |
| => output: libraries/ghc-prim/stage1/build/libHSghc-prim-0.5.0.0.a        |
\---------------------------------------------------------------------------/
250278
3658
```
so the total length of the arguments is `250278`, which should fit into `262144 - 4096`.

What *does* work is `262144 - (9 * 4096)`. The correct value is probably somewhere in between, but I'm still confused about this.

**Comment by snowleopard** [comment]
OK, the command line length quirks don't surprise me, I also had fun looking for a limit on Windows.

The `ranlib` problem is new to me. No idea what's going on.

**Comment by angerman** [comment]
I guess we can ignore the `ranlib` note. That one's also there if it goes through.

**Comment by snowleopard** [comment]
Ah, good. So does this mean you solved this issue?

**Comment by angerman** [comment]
I've homed in this far:
```
262144 - (9 * 4096) + 2048 + 1024 + 512 + 256 - 128 - 64 + 32 + 16 + 8 - 4 - 2
```

**Comment by angerman** [comment]
we are now at:
```
232286
3370
---
17991
288
```

**Comment by angerman** [comment]
So the questions remains: what takes up `33166` parts of the input?

**Comment by snowleopard** [comment]
Impressive! Please add a note that the constant you choose comes from experiments.

Also, looking at the above snippet:
```haskell
cmdLineLengthLimit :: Action Int
cmdLineLengthLimit = do
    windows <- windowsHost
    return $ if windows
             then 31000
             else 262144 - 4096 -- 4194304 -- Cabal needs a bit more than 2MB!
```
I think we shouldn't change the default `4194304`, but handle OS X in a special way, similarly to Windows. Other limits may be discovered later on different platforms. To detect OS X you can use `anyHostOs ["ios"]`. Maybe it's worth to have it as a separate function, similar to `windowsHost`.

**Comment by snowleopard** [comment]
> So the questions remains: what takes up 33166 parts of the input?

I think `ar` does something bad internally. We are probably not breaking the command line length limit here, see:
```
Command: /usr/bin/ar q libraries/ghc-prim/stage1/build/libHSghc-prim-0.5.0.0.a libraries/ghc-prim/stage1/build/cbits/atomic.o libraries/ghc-prim/stage1/build/cbits/bswap.o libraries/ghc-prim/stage1/build/cbits/clz.o libraries/ghc-prim/stage1/build/cbits/ctz.o libraries/ghc-prim/stage1/build/cbits/debug.o libraries/ghc-prim/stage1/build/cbits/longlong.o libraries/ghc-prim/stage1/build/cbits/popcnt.o libraries/ghc-prim/stage1/build/cbits/word2float.o libraries/ghc-prim/stage1/build/GHC/CString_o_split/CString__1.o libraries/ghc-prim/stage1/build/GHC/CString_o_split/CString__2.o [...] libraries/ghc-prim/stage1/build/GHC/Types_o_split/Types__9.o
/usr/bin/ar: createProcess: runInteractiveProcess: exec: resource exhausted (Argument list too long))
```

**Comment by angerman** [comment]
Well, the subtraction of `33166` comes from experiments, which I usually don't trust.
The `262144` comes from

```bash
$ getconf ARG_MAX
262144
```

which apparently has been the same for the last 5 os x iterations.

**Comment by angerman** [comment]
I still don't get why `make` with `xargs` has no problem with this.

**Comment by snowleopard** [comment]
Maybe `xargs` is more conservative with length limits? Is there a way to find out what length it uses in this case?

**Comment by angerman** [comment]
@snowleopard the weird thing is, I tried the same command `make` uses with `xargs` through `shake`. The only difference being the `< file`  for `make` where `shake` got the `stdin` through `(Stdin contents)`.

**Comment by bgamari** [comment]
Moritz Angermann <notifications@github.com> writes:

> Ok. this didn't work either.
> ```
> cmdLineLengthLimit :: Action Int
> cmdLineLengthLimit = do
>     windows <- windowsHost
>     return $ if windows
>              then 31000
>              else 262144 - 4096 -- 4194304 -- Cabal needs a bit more than 2MB!
> ```
> yet

The typical way around Windows' pathetically small argument list limit
is to use a response file. It seems that `ar` supports this with the
usual `@` argument.

Cheers,

- Ben

**Comment by snowleopard** [comment]
@bgamari We do use `@file` whenever `ar` supports it.

**Comment by ndmitchell** [comment]
Looking at the code for `chunksOfSize`, as far as I can tell, it counts the length of the filenames, but _not_ the lengths of the spaces, which are important for finding out the right size. You can either modify the spec of `chunksOfSize` (I recommend doing so after merging the tests in #151), or pass a list interspersed with spaces to `chunksOfSize` (that seems easier and cleaner to me).

**Comment by angerman** [comment]
I did some digging into what `xargs` actually does (on OS X). Apple provides the source for `xargs`[1], but not for the most recent version shipped with the operating system. Looking at the `xargs` source wasn't really helpful. The systems `xargs` drops some `20 000` bytes from the reported `MAX_ARG` value, which the provided source version does not. Hence I suspect there is some additional magic in `xargs` on os x. We agreed on irc to use a pragmatic `200 000` byte limit, which would potentially cause some additional invocations, but be safe.

I'm not really happy, not knowing what `xargs` on os x does to compute the arg length, but I could not justify putting in even more effort :-( Next step would be to reverse engineer the `xargs` binary to see what's actually going on. Notably the `xargs` compiled from the provided source, exhibits the same issue the implemented solution exhibited.

[1]http://www.opensource.apple.com/source/shell_cmds/shell_cmds-116/xargs/xargs.c

**Comment by olsner** [comment]
The "command line size" also includes the environment on most/all Unixes, so the limit you get from `_SC_ARG_MAX` or similar is actually a limit on the total size of some block of extra data containing command line, environment, and possibly other stuff. That'll be why the usable maximum length is shorter than expected, and why you might get different results when running stuff directly and when running through shake, or locally vs on travis, etc.

Probably what happened to Apple's xargs is that people ran into the argument/environment limit even with the 4kB margin so they simply increased the margin to 20kB. Maybe because they added some variables to the default environment at some point.
