### ISSUE TITLE
Remove support for / disable by default `--split-objs`

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#153]
As far as I can tell, `--split-objs` is going to be replaced by `--split-sections` soon(ish). I propose that we drop support for `--split-objs` from `shaking-up-ghc` for being progressive in this direction.

We added support for `--split-obis` and `ghc-split` in #138. Yet we have #139 and #30. Hence I propose that we either remove split-objs completely, or at least disable it by default for shaking-up-ghc.

cc: @ezyang, @bgamari

**Comment by ezyang** [comment]
I'm not sure it is going to be that soon. When I looked into it, `--split-sections` requires an Apple-style linker... which is only on Mac OS X. There seems to be some benefits you get from `--split-sections` but I'm not sure how much this applies to Linux.

**Comment by snowleopard** [comment]
Is there any evidence for the plan to drop support of `-split-objs` in GHC? I've seen people talk about this, but is it really on the agenda? In which GHC release will this happen?

At the moment we already have a full support for `-split-objs`. I don't see any immediate need to remove this sooner than it's dropped from `make`.

I don't mind switching this off by default though. This will help us avoid bugs and extra dependencies.

**Comment by angerman** [comment]
Maybe I got that wrong, but https://ghc.haskell.org/trac/ghc/ticket/8405 and https://ghc.haskell.org/trac/ghc/ticket/9832 looked to me like `-split-objs` might actually be dropped.

Let's go with disabled by default then. Just found this https://ghc.haskell.org/trac/ghc/ticket/8300 as well.

It looks to me as if `-split-objs` should only be used if you *really* need that extra bit of space savings.

**Comment by snowleopard** [comment]
OK, done.

**Comment by olsner** [comment]
> When I looked into it, --split-sections requires an Apple-style linker...

Hmm, I think you're confusing it with the "subsections via symbols" feature that is used on Mac. The effect is quite similar to what `-split-sections` does, but it's activating an apple-specific linker/assembler feature instead of doing it ourselves.
The actual `-split-sections` feature instead does *not* support Mac at all, it currently (probably) only works on Linux. (It should work on other platforms that use GNU ld and ELF, if there are any.)

**Comment by angerman** [comment]
Ohh our beloved `-dead_strip`
```
   Options that control optimizations
     -dead_strip
                 Remove functions and data that are unreachable by the entry point or exported symbols.
```
(from the `ld` man page)

I remember fixing that for the `llvm` backend, as `xcode` always enables `-dead_strip` by default. 

Then, wouldn't that imply that we *do not need* `-split-sections` or `-split-objs` on Mac anyway, as we can rely on the linker to garbage collect unreachable code? (Assuming, we guide `-dead_strip` correctly)

**Comment by DemiMarie** [comment]
@angerman At the time you made your comment, that was not true, but I fixed `-dead_strip`.

**Comment by angerman** [comment]
@DemiMarie you are probably right. The `-dead_strip` fix in ghc, got unintentionally lost in a subsequent llvm backend improvement :-/

Thanks for fixing `-dead_strip` again then :) Hope you added enough comments, so yours does not get lost :)
