### ISSUE TITLE
doc issue, missing shake install

### ISSUE THREAD

**Issue by kgardas** [snowleopard/shaking-up-ghc#155]
Hello,

README is not clear about it, certainly it looks like you need to cabal install shake in order to give a shakized ghc a try. README mentions that what you needed with make for building GHC is enough, but this is not true probably.

**Comment by kgardas** [comment]
Another try: it also looks like you also need QuickCheck installed.

**Comment by kgardas** [comment]
And a last addition: you also need ansi-terminal

**Comment by snowleopard** [comment]
Thanks, you are right, it's better to be explicit about dependencies. I've updated README.

**Comment by angerman** [comment]
Haha we come full circle. Not sure how @quchen feels about that ;-)

Anyway. The QuickCheck Dependeny irks me a little. Shouldn't that be a `Test` only dependency? I though cabal allowed for Test only dependencies? cc: @ndmitchell

**Comment by snowleopard** [comment]
@angerman It's the second time this issue is raised. We already discussed adding such a line here: https://github.com/snowleopard/shaking-up-ghc/issues/37#issuecomment-167225959. This appears to have never been actioned.

**Comment by quchen** [comment]
`build.cabal.sh` installs all the deps automatically, why ping me?

**Comment by angerman** [comment]
Sorry @quchen, will not happen again.

**Comment by ndmitchell** [comment]
@angerman you can have multiple exe's in Cabal, and have different dependencies for each. We have one single exe though (which seems to suit us best), so all dependencies are required for everything.
