### ISSUE TITLE
ffi build failes when /tmp is different device

### ISSUE THREAD

**Issue by kgardas** [snowleopard/shaking-up-ghc#156]
Hello,
my attempt to use shake to build GHC on Solaris fails on building ffi with:
```
Reading shake-build/cfg/system.config...
| Successfully generated 'includes/ghcversion.h'.
| Successfully generated 'includes/ghcplatform.h'.
| Successfully generated 'includes/ghcautoconf.h'.
/------------------------------------------------\
| Run Tar (stage = Stage0, package = libffi)     |
|     input: libffi-tarballs/libffi-3.2.1.tar.gz |
| => output: /tmp/extra-dir--929703821           |
\------------------------------------------------/
/---------------------------------------------------\
| Move directory                                    |
|     input: /tmp/extra-dir--929703821/libffi-3.2.1 |
| => output: .build/stage0/libffi                   |
\---------------------------------------------------/
shakeArgsWith   0.002s    0%                           
Function shake  0.078s   31%  ===========              
Database read   0.001s    0%                           
With database   0.000s    0%                           
Running rules   0.165s   67%  ========================
Total           0.246s  100%                           
Error when running Shake build system:
* .build/stage1/rts/build/libHSrts.a
* OracleQ (PackageDataKey (".build/stage1/rts/package-data.mk",".build_stage1_rts_C_SRCS"))
* .build/stage1/rts/package-data.mk
* .build/stage1/rts/build/ffitarget.h
* .build/stage1/rts/build/ffi.h .build/stage1/rts/build/ffitarget.h
/tmp/extra-dir--929703821/libffi-3.2.1: rename: unsupported operation (Cross-device link)
```
the last message probably suggest that shake does not like to have /tmp mounted from different device than on home where it tries to build GHC...

**Comment by snowleopard** [comment]
Thanks for reporting! We haven't tried building GHC on Solaris yet. The build system does rely on creating temporary files and directories.

**Comment by kgardas** [comment]
And does it run for you on either Linux or Mac OS X when /tmp is tmpfs or different drive? That's the point IMHO here, otherwise Solaris is not that different...

**Comment by snowleopard** [comment]
@kgardas I'm using Windows myself, so can't check.

@angerman Could you check on OS X?

**Comment by kgardas** [comment]
Btw, when I moved the build tree to /tmp as a whole then this runs fine -- i.e. was able to rename unpacked ffi tree to stage0 sub dir. My guess is, the issue should be also preserved on Linux too...

**Comment by ndmitchell** [comment]
It is not OS specific, it's due to having tmp mounted in a different place from GHC. I will explain and give a patch tomorrow with luck, once I have more than a mobile.

**Comment by ndmitchell** [comment]
The issue is at https://github.com/snowleopard/shaking-up-ghc/blob/24e6c28e5884d49fbd408fe81fad9ca48c1f7f94/src/Rules/Libffi.hs#L86-L89

You can't rename a file or directory from temp to elsewhere, since renames have to be within a drive, and temp might be elsewhere. You can copy the directory if you want, or better still, extract it to the right place (although I'm not sure that's possible with tar).

**Comment by ndmitchell** [comment]
I've removed the Solaris tag because this will happen on any platform, even Windows.

**Comment by snowleopard** [comment]
@ndmitchell I don't think we can extract it in the right place using `tar`. And copying it would be slow. Shall we then simply extract directly to `.build` and then move from there?

**Comment by kgardas** [comment]
@snowleopard what about if you set the right directory as a current working directory of executed tar? Then tar will unpack on the right place I guess...

**Comment by ndmitchell** [comment]
Yep, that seems reasonable. You might want to `actionFinally` to delete the directory you are initially extracting to, so if there is an error or abort you don't get left with a stale dir.

**Comment by ndmitchell** [comment]
@kgardas - the tar file contains `libtar-0.3.2/file1.c`, but we want to produce `libtar/file1.c` - so extract with a current working directory _and_ trim the first directory component.

**Comment by snowleopard** [comment]
@ndmitchell Exactly, we are after a subdirectory.

I'll fix this now.

**Comment by snowleopard** [comment]
@ndmitchell Is this what you had in mind?

https://github.com/snowleopard/shaking-up-ghc/blob/86f3052c2cd738427136899bfe3a47210c4d98a5/src/Rules/Libffi.hs#L85-L87

**Comment by ndmitchell** [comment]
I was expecting a little more under the `actionFinally`, see #161 where I've pull requested the tweaks (and a few others while reading through).

I'm still a little worried that we might need a `removeDirectory (buildRootPath -/- libname)` just before the `actionFinally` in case there is stale stuff around and we need to clean up a `kill -9` build. Not sure though.

**Comment by snowleopard** [comment]
Thanks!
Regarding your last comment, maybe `Base.removeDirectoryIfExists` can be used?

**Comment by ndmitchell** [comment]
I updated my pull request with that.

**Comment by snowleopard** [comment]
@ndmitchell It says `removeDirectory`, not `removeDirectoryIfExists`, is this a typo?

**Comment by snowleopard** [comment]
Ah, sorry. I see now!

**Comment by ndmitchell** [comment]
Yes, its slightly starting to confuse me, and I'd also ideally use removeDirectoryIfExists on the actionFinally fallback, but that doesn't work because its Action not IO. I think once things are a bit more stable a big pass over all the IO/Directory combinators and their types might be useful.

**Comment by snowleopard** [comment]
Agreed. Also having some functions live in `Base.hs` and most others in `Rules/Actions.hs` is confusing.

**Comment by ndmitchell** [comment]
Also agreed. But I don't think its actively harmful just now, and hopefully more experience will give us a better idea which building blocks make sense.

**Comment by ndmitchell** [comment]
For info, the abstractions I used at work for these kind of things are all named rmdir/mkdir etc after their shell names rather than their Haskell names. These are short and imply build semantics rather than trying to compete with the Haskell functions for good names. Might be an idea here too.

**Comment by angerman** [comment]
:+1: for `rmdir/mkdir`.
