### ISSUE TITLE
ffi build fails on non-GNU make

### ISSUE THREAD

**Issue by kgardas** [snowleopard/shaking-up-ghc#157]
Hello,
ffi build steps does not care that on some Unixes the GNU make is not ```make``` command but is ```gmake``` command. This way it ends with executing Solaris provided make which simply fails:
```
Error when running Shake build system:
* .build/stage1/rts/build/libHSrts.a
* OracleQ (PackageDataKey (".build/stage1/rts/package-data.mk",".build_stage1_rts_C_SRCS"))
* .build/stage1/rts/package-data.mk
* .build/stage1/rts/build/ffitarget.h
* .build/stage1/rts/build/ffi.h .build/stage1/rts/build/ffitarget.h
user error (Development.Shake.cmd, system command failed
Command: make -C .build/stage0/libffi MAKEFLAGS=
Exit code: 1
Stderr:
Usage : make [ -f makefile ][ -K statefile ][ -x MODE_NAME=VALUE ]... [ -d ][ -dd ][ -D ][ -DD ]
             [ -e ][ -i ][ -k ][ -n ][ -p ][ -P ][ -q ][ -r ][ -s ][ -S ][ -t ]
             [ -u ][ -w ][ -V ][ target... ][ macro=value... ][ "macro +=value"... ]
make: Fatal error: Unknown option `-C'
)
```

**Comment by snowleopard** [comment]
Right, we need to find out which `make` to call. Not sure how to do that. The old build system uses `MAKE` variable, which I guess is provided by `make`, it's not part of the environment.

**Comment by kgardas** [comment]
You tag this as Solaris specific issue, but IMHO the same will hit us on *BSDs too.
IMHO would be the best to have user specific setting for GNU make command -- set to ```make''' by default for Linux but user can edit this for gmake on another Unixes...

**Comment by ndmitchell** [comment]
It is not OS specific, it's due to having tmp mounted in a different place from GHC. I will explain and give a patch tomorrow with luck, once I have more than a mobile.

**Comment by snowleopard** [comment]
> You tag this as Solaris specific issue, but IMHO the same will hit us on *BSDs too.

I think this just makes it easier for people to search for potential issues when building on Solaris. If someone on BSD reports this I'll add another tag.

> IMHO would be the best to have user specific setting for GNU make command -- set to ```make''' by default for Linux but user can edit this for gmake on another Unixes...

Sounds reasonable. I pushed a fix. Please edit `makeCommand` in `Settings.User`.

**Comment by ndmitchell** [comment]
Note the new build system doesn't really use make or gmake, other than small pieces. It is mostly Haskell :)

**Comment by ndmitchell** [comment]
Please ignore my comments - my mobile browser brought me to the wrong ticket!

**Comment by snowleopard** [comment]
> Note the new build system doesn't really use make or gmake, other than small pieces. It is mostly Haskell :)

@ndmitchell No we just have to convince `gmp` and `libffii` people to switch to Shake ;)

**Comment by angerman** [comment]
@snowleopard, @ndmitchell or can we just *read* the `Makefile` and run it through `shake`?

**Comment by ndmitchell** [comment]
@angerman I thought of that, and it is possible to some extent (see http://neilmitchell.blogspot.co.uk/2014/01/running-makefiles-with-shake.html), but I don't think its that realistic - it's too huge and too scary.
