### ISSUE TITLE
gmp build expects GNU patch as patch

### ISSUE THREAD

**Issue by kgardas** [snowleopard/shaking-up-ghc#158]
On Solaris and *BSD GNU patch is usually ```gpatch''' command. On Solaris particularly I get this failure:
```
Error when running Shake build system:
* utils/mkUserGuidePart/stage1/build/tmp/mkUserGuidePart
* OracleQ (PackageDataKey (".build/stage1/utils/mkUserGuidePart/package-data.mk",".build_stage1_utils_mkUserGuidePart_C_SRCS"))
* .build/stage1/utils/mkUserGuidePart/package-data.mk
* .build/stage1/utils/mkUserGuidePart/package-data.mk utils/mkUserGuidePart/stage1/package-data.mk
* .build/stage1/compiler/package-data.mk
* .build/stage1/compiler/package-data.mk compiler/stage1/package-data.mk
* .build/stage0/gmp/include/ghc-gmp.h
user error (Development.Shake.cmd, system command failed
Command: patch -p0 < gmpsrc.patch
Current directory: /tmp/shake-test/.build/stage0/gmp
* utils/mkUserGuidePart/stage1/build/tmp/mkUserGuidePart
* OracleQ (PackageDataKey (".build/stage1/utils/mkUserGuidePart/package-data.mk",".build_stage1_utils_mkUserGuidePart_C_SRCS"))
* .build/stage1/utils/mkUserGuidePart/package-data.mk
* .build/stage1/utils/mkUserGuidePart/package-data.mk utils/mkUserGuidePart/stage1/package-data.mk
* .build/stage1/compiler/package-data.mk
* .build/stage1/compiler/package-data.mk compiler/stage1/package-data.mk
* .build/stage0/gmp/include/ghc-gmp.h
user error (Development.Shake.cmd, system command failed
Command: patch -p0 < gmpsrc.patch
Current directory: /tmp/shake-test/.build/stage0/gmp
Exit code: 1
Stderr:
  Looks like a unified context diff.
Hunk #1 failed at line 3937.
Hunk #2 failed at line 24.
2 out of 2 hunks failed: saving rejects to gmp-5.0.3/configure.rej
done
)
```
GNU patch is running fine on it.
So we either need the same hack like done for gmake or even more preferably use similar setup like GHC itself with settings.in file. This file may be generated by configure and there we can deal with platforms differences.

**Comment by snowleopard** [comment]
Yes, there is a `TODO` item in the sources to add support for detecting the right `patch` command via `configure` and `system.config`.

Regarding `make`: what was the right mechanism to tell the old build system to use `gmake`? Was it via `configure --with-make`? I don't think it worked in the same way as with `gpatch`. It would be great to use the same convention for all builders, namely, to specify them using `configure` parameters.

**Comment by snowleopard** [comment]
Now fixed, see the above commit.

@kgardas Could you please test it?

**Comment by snowleopard** [comment]
OK, I'll close this. Looks like the fix was successful: https://github.com/snowleopard/shaking-up-ghc/issues/173#issuecomment-171932593.
