### ISSUE TITLE
Build ignores --with-* configure params

### ISSUE THREAD

**Issue by kgardas** [snowleopard/shaking-up-ghc#159]
It looks like shake completely ignores the fact that I've configured GHC to use system supplied GMP library (with --with-gmp-includes/--with-gmp-libraries) and tries to build its own GMP library build for GHC.
This is also the case of --with-ffi-* params since even if I use it shake still insist on building its own ffi library. I guess very same is also with iconv and ncurses related parameters.

**Comment by snowleopard** [comment]
We do have some functionality to detect installed `gmp`, but it hasn't been tested properly. And at the moment we always build `ffi`. Feel free to pick up this issue if you like.

Did the building of in-tree `gmp` and `ffi` work for you?

**Comment by kgardas** [comment]
FFI build seems to be fine after moving to /tmp to work around #156 the problem is gmp build which fails with
```
Error when running Shake build system:
* utils/mkUserGuidePart/stage1/build/tmp/mkUserGuidePart
* OracleQ (PackageDataKey (".build/stage1/utils/mkUserGuidePart/package-data.mk",".build_stage1_utils_mkUserGuidePart_C_SRCS"))
* .build/stage1/utils/mkUserGuidePart/package-data.mk
* .build/stage1/utils/mkUserGuidePart/package-data.mk utils/mkUserGuidePart/stage1/package-data.mk
* .build/stage1/compiler/package-data.mk
* .build/stage1/compiler/package-data.mk compiler/stage1/package-data.mk
* .build/stage0/gmp/include/ghc-gmp.h
user error (Development.Shake.cmd, system command failed
Command: bash configure
Current directory: /tmp/shake-test/libraries/integer-gmp
Exit code: 1
Stderr:
configure: error: Cannot find gmp.h
)
```

**Comment by snowleopard** [comment]
It seems to me that it fails right at the stage of determining whether there is an installed `gmp`. This is done by running `configure` in `libraries/integer-gmp`, which produces file `config.mk` with `HaveFrameworkGMP = YES`.

Could you show previously executed commands?

Second question: how do you typically run `configure` to build GHC using `make` and use installed `gmp`?

**Comment by snowleopard** [comment]
To whoever would like to pick this up: the right files to change are: `Rules/Gmp.hs` and `Rules/Libffi.hs`.

I won't be able to tackle this in the coming days.

**Comment by kgardas** [comment]
At top level I do ./configure --with-gmp-includes=/usr/include/gmp/ --with-gmp-libraries=/usr/lib/ -- this sets GMP_INCLUDE_DIRS and GMP_LIB_DIRS in mk/config.mk -- those are then used to pass the same --with-gmp-includes=/usr/include/gmp/ --with-gmp-libraries=/usr/lib/ while invoking configure script inside the libraries/integer-gmp.
I'll see if I can do anything about this (gmp) issue.

**Comment by snowleopard** [comment]
@kgardas Thank you!

What about `gmake`? Do you specify it manually or does the system picks it up automatically?

**Comment by kgardas** [comment]
gmake? This is easy, GHC requires that so you use it, after configure I simply do ```gmake```. Whenever there is a need to run subsequent make from the makefile (build system), it needs to use $(MAKE) instead of real command name since $(MAKE) is substituted by make itself to the right value.

**Comment by snowleopard** [comment]
@kgardas I see. So I guess we'll have to keep the `makeCommand` setting in `Settings/User.hs` for now. However, I imagine it would be possible to add `--with-make` flag to `configure` script at some point.

**Comment by kgardas** [comment]
@snowleopard IMHO much comfortable would be to simply invoke ```make --version``` and grep for ```GNU Make```. If not successful try ```gmake --version``` and do the same. If not successful error with nice explanation that for 3th party libraries (gmp/ffi) shake still requires GNU make to be installed. Example outputs from both command on Solaris 11.2:
```
$ make --version
make: Warning: Ignoring DistributedMake -v option
make: Warning: Ignoring DistributedMake -o option
make: Fatal error: No dmake output dir argument after -o flag
$
$ gmake --version
GNU Make 3.82
Built for i386-pc-solaris2.11
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ 
```
The same on OpenBSD 5.9-current looks:
```
$ make --version
make: unknown option -- -
usage: make [-BeiknpqrSst] [-C directory] [-D variable] [-d flags] [-f mk]
            [-I directory] [-j max_processes] [-m directory] [-V variable]
            [NAME=value] [target ...]
$
$ gmake --version
GNU Make 4.1
Built for x86_64-unknown-openbsd5.8
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$
```
hope this helps.

**Comment by snowleopard** [comment]
@kgardas This sounds like a typical task for the `configure` script. We could add the following to `system.config.in`:
```
make = @MakeCmd@
```
And ask `configure` to set `@MakeCmd@` to `make` or `gmake` using your approach. This is similar to what happens with many other `Builder`s.

**Comment by kgardas** [comment]
@snowleopard agree. In fact current ghc configure already checks for GNU make > 3.80 by following code:
```
checkMake380() {
    if $1 --version 2>&1 | head -1 | grep 'GNU Make 3\.80' > /dev/null
    then
        echo
        echo "WARNING: It looks like \"$1\" is GNU make 3.80."
        echo "This version cannot be used to build GHC."
        echo "Please use GNU make >= 3.81."
    fi
}

checkMake380 make
checkMake380 gmake
```
so it should not be too hard to do what you suggest.

**Comment by snowleopard** [comment]
@kgardas Thanks! I've created a separate issue for detecting `make`: #167.

**Comment by snowleopard** [comment]
I believe this is now fixed. Please reopen otherwise.

**Comment by kgardas** [comment]
@snowleopard I'd like to reopen this ticket but don't know how. Anyway, this ticket is not only about --with-gmp-* options but also with options related to FFI library and also to ICONV library. All those are important to get working to for example not break build on OpenBSD. Please reopen if possible yourself.
Anyway, fix for FFI library handling is on the way, I just need to do final testing...

**Comment by kgardas** [comment]
@snowleopard feel free to also put me as an assignee. Don't know how to do that myself. :-(

**Comment by snowleopard** [comment]
@kgardas Sure!

To assign this issue to you I had to add you as a collaborator to the project, which will give you access to the master branch. Please don't write to the master branch directly, use pull requests.

**Comment by kgardas** [comment]
@snowleopard Thanks! And sure, as a haskell beginner I'm not in a position to commit my haskell code changes anywhere except to my own branches. :-)

**Comment by snowleopard** [comment]
@kgardas Thanks! Although I'm a Haskell beginner too :-)

**Comment by kgardas** [comment]
@snowleopard I've pushed a pull request for handling FFI library configure args now. Let me appologize I'm not able to test that as I'm not able to build working GHC with either my branch or with your master for now -- see #181 -- so well, please be more careful about this. Also I've not tested on windows at all, just on Solaris and this resulted in ghc-stage2 binary correctly linked against system supplied FFI library if I used the right configure params so it kind of worked for me well...

**Comment by snowleopard** [comment]
@kgardas No problem, we have CI instances checking Linux/OSX/Windows, so we should be safe. I'll also make sure it works well on Windows.

**Comment by snowleopard** [comment]
@kgardas Have all issues been fixed now? Or is there anything else to be done?

**Comment by kgardas** [comment]
@snowleopard no, there are still outstanding issues shown on OpenBSD where gmp is not in /usr/lib but in /usr/local/lib -- so we need to correctly pass -L to the linker. Issue shows as:
```
Error when running Shake build system:
* inplace/lib/bin/unlit
user error (Development.Shake.cmd, system command failed
Command: /usr/local/bin/ghc -hisuf hi -osuf o -hcsuf hc -static -no-user-package-db -package-db /home/karel/src/shake-test/.build/stage0/bootstrapping.conf -i -i.build/stage0/utils/unlit/build -i.build/stage0/utils/unlit/build/autogen -I.build/stage0/utils/unlit/build -I.build/stage0/utils/unlit/build/autogen -odir .build/stage0/utils/unlit/build -hidir .build/stage0/utils/unlit/build -stubdir .build/stage0/utils/unlit/build -rtsopts -H32m -O -no-auto-link-packages -optl-lgmp .build/stage0/utils/unlit/build/unlit.o -o inplace/lib/bin/unlit -no-hs-main
Exit code: 1
Stderr:
Warning: -rtsopts and -with-rtsopts have no effect with -no-hs-main.
    Call hs_init_ghc() from your main() function to set these options.
/usr/bin/ld: cannot find -lgmp
collect2: ld returned 1 exit status
)
```
on Solaris everything's fine for the moment.

**Comment by snowleopard** [comment]
@kgardas I see, thanks for clarifying! If you need any help with this, please let me know.

**Comment by kgardas** [comment]
@snowleopard if you plan release just do it. I'll not be able to get to this issue before this or next weekend.

**Comment by snowleopard** [comment]
@kgardas Just FYI: I moved gmp and libffi to Stage1 (see two above commits). This should improve parallelism and make Stage0 build fit into 1 hour on AppVeyor.

**Comment by kgardas** [comment]
@snowleopard I've now been able to retest master on OpenBSD and to my surprise original issue with gmp not being able find is gone. I'm now able to build default build of GHC when it's configured with
```
./configure --with-gmp-includes=/usr/local/include/ --with-gmp-libraries=/usr/local/lib --with-iconv-includes=/usr/local/include/ --with-iconv-libraries=/usr/local/lib --with-system-libffi --with-ffi-includes=/usr/local/include/ --with-ffi-libraries=/usr/local/lib
```
I'm not sure if iconv options are well managed, but as both iconv and gmp reside in the same dir on OpenBSD I'm not able to test it easily, so please close this issue and thanks a lot for this hacking.

**Comment by snowleopard** [comment]
@kgardas Great, thanks for testing!

Could you please do another test? I'd like to test the new built-in `--configure` feature. Do a fresh clone and run the following command **without** running `boot` or `configure`:
```
shake-build/build.sh --configure="--with-gmp-includes=/usr/local/include/ --with-gmp-libraries=/usr/local/lib --with-iconv-includes=/usr/local/include/ --with-iconv-libraries=/usr/local/lib --with-system-libffi --with-ffi-includes=/usr/local/include/ --with-ffi-libraries=/usr/local/lib"
```
This should have the same effect as running `boot` and `configure` with given flags beforehand.

**Comment by kgardas** [comment]
Something's not right with it:
```
Error when running Shake build system:
* inplace/bin/ghc-stage2
* inplace/lib/bin/ghc-stage2
* .build/stage1/libraries/unix/build/HSunix-2.7.1.1.o
* .build/stage1/libraries/unix/build/System/Posix/IO/Common.o
user error (Development.Shake.cmd, system command failed
Command: inplace/bin/ghc-stage1 -hisuf hi -osuf o -hcsuf hc -static -hide-all-packages -no-user-package-db -this-package-key unix-2.7.1.1 -package-id base-4.9.0.0 -package-id bytestring-0.10.7.0 -package-id time-1.6 -i -i.build/stage1/libraries/unix/build -i.build/stage1/libraries/unix/build/autogen -ilibraries/unix -I.build/stage1/libraries/unix/build -I.build/stage1/libraries/unix/build/autogen -Ilibraries/unix/include -I/home/karel/src/test2_shake/libraries/time/lib/include -I/home/karel/src/test2_shake/libraries/bytestring/include -I/usr/local/include/ -I/home/karel/src/test2_shake/libraries/base/include -I/usr/local/include/ -I/home/karel/src/test2_shake/libraries/integer-gmp/include -I/home/karel/src/test2_shake/.build/stage1/rts/build -I/home/karel/src/test2_shake/includes -I/home/karel/src/test2_shake/includes/dist-derivedconstants/header -I/usr/local/include/ -optP-include -optP.build/stage1/libraries/unix/build/autogen/cabal_macros.h -XHaskell2010 -odir .build/stage1/libraries/unix/build -hidir .build/stage1/libraries/unix/build -stubdir .build/stage1/libraries/unix/build -rtsopts -H32m -O2 -c .build/stage1/libraries/unix/build/System/Posix/IO/Common.hs -o .build/stage1/libraries/unix/build/System/Posix/IO/Common.o
Exit code: 1
Stderr:
on the commandline: warning:
    -this-package-key unix-2.7.1.1 is deprecated: Use -this-unit-id instead

libraries/unix/System/Posix/IO/Common.hsc:316:61: error:
    * Couldn't match type `()' with `Base.CFLock'
      Expected type: Ptr Base.CFLock
        Actual type: Ptr CFLock
    * In the third argument of `Base.c_fcntl_lock', namely `p_flock'
      In the second argument of `throwErrnoIfMinus1_', namely
        `(Base.c_fcntl_lock fd (7) p_flock)'
      In a stmt of a 'do' block:
        throwErrnoIfMinus1_ "getLock" (Base.c_fcntl_lock fd (7) p_flock)

libraries/unix/System/Posix/IO/Common.hsc:364:61: error:
    * Couldn't match type `()' with `Base.CFLock'
      Expected type: Ptr Base.CFLock
        Actual type: Ptr CFLock
    * In the third argument of `Base.c_fcntl_lock', namely `p_flock'
      In the second argument of `throwErrnoIfMinus1_', namely
        `(Base.c_fcntl_lock fd (8) p_flock)'
      In the expression:
        throwErrnoIfMinus1_ "setLock" (Base.c_fcntl_lock fd (8) p_flock)

libraries/unix/System/Posix/IO/Common.hsc:371:35: error:
    * Couldn't match type `()' with `Base.CFLock'
      Expected type: Ptr Base.CFLock
        Actual type: Ptr CFLock
    * In the third argument of `Base.c_fcntl_lock', namely `p_flock'
      In the second argument of `throwErrnoIfMinus1_', namely
        `(Base.c_fcntl_lock fd (9) p_flock)'
      In the expression:
        throwErrnoIfMinus1_
          "waitToSetLock" (Base.c_fcntl_lock fd (9) p_flock)
)
```

**Comment by snowleopard** [comment]
@kgardas Thank you... it's the first time I see this error, no ideas what's wrong. This seems to be the key:
```haskell
allocaLock :: FileLock -> (Ptr CFLock -> IO a) -> IO a
```
Apparently call sites use `Ptr Base.CFLock` instead of `Ptr CFLock`. I don't see how this could be related to the `--configure=...` flag. Do you have any ideas?

**Comment by snowleopard** [comment]
@kgardas Apparently GHC HEAD is broken: https://mail.haskell.org/pipermail/ghc-devs/2016-January/011209.html. Maybe try an earlier commit?

**Comment by kgardas** [comment]
@snowleopard tried just now on Solaris, fresh checkout, went fine with:
```
./shake-build/build.sh --configure="--with-gmp-includes=/usr/include/gmp/ --with-gmp-libraries=/usr/lib/ --with-ar=/usr/bin/gar"
```
will rested on OpenBSD in the evening...

**Comment by snowleopard** [comment]
Many thanks @kgardas! I think we can close this, hoping that the retest on OpenBSD will go smoothly.

**Comment by kgardas** [comment]
@snowleopard bootstrap on OpenBSD with:
```
./shake-build/build.sh -B --configure=--with-gmp-includes=/usr/local/include/ --with-gmp-libraries=/usr/local/lib --with-iconv-includes=/usr/local/include/ --with-iconv-libraries=/usr/local/lib --with-system-libffi --with-ffi-includes=/usr/local/include/ --with-ffi-libraries=/usr/local/lib
```
went fine this time.

**Comment by snowleopard** [comment]
@kgardas :+1:

**Comment by snowleopard** [comment]
@kgardas I have made a number of simplifications in `Rules/Gmp.hs` in the above commit. I hope I haven't broken anything that you fixed in this issue. Could you please run a test?
