### ISSUE TITLE
hp2ps needs to depend upon ghcautoconf.h

### ISSUE THREAD

**Issue by bgamari** [snowleopard/shaking-up-ghc#16]
`hp2ps` apparently needs `includes/ghcautoconf.h` lest the following happens while generating dependencies,
```
$ shake-build/build.sh -j4
Reading shake-build/cfg/system.config...
Reading utils/ghc-cabal/dist-boot/package-data.mk...
Reading package dependencies...
Reading utils/hp2ps/dist-boot/package-data.mk...
Reading dependencies from utils/hp2ps/dist-boot/build/.dependencies...
╭──────────
│ Running GccM 0 with arguments:
│   ... skipping 13 arguments ...
│   utils/hp2ps/Deviation.c
╰──────────

In file included from utils/hp2ps/Main.h:4:0,
                 from utils/hp2ps/Deviation.c:1:
includes/ghcconfig.h:4:25: fatal error: ghcautoconf.h: No such file or directory
compilation terminated.
╭──────────
│ Running GccM 0 with arguments:
│   ... skipping 13 arguments ...
│   utils/hp2ps/Reorder.c
╰──────────

Error when running Shake build system:
* inplace/bin/hp2ps
* utils/hp2ps/dist-boot/build/Deviation.o
* OracleQ (DependenciesKey ("utils/hp2ps/dist-boot/build/.dependencies","utils/hp2ps/dist-boot/build/Deviation.o"))
* utils/hp2ps/dist-boot/build/.dependencies
* utils/hp2ps/dist-boot/build/Deviation.c.deps
user error (Development.Shake.cmd, system command failed
Command: /usr/bin/gcc -E -MM -Iincludes -Iincludes/dist -Iincludes/dist-derivedconstants/header -Iincludes/dist-ghcconstants/header -Iutils/hp2ps/dist-boot/build/autogen -MF utils/hp2ps/dist-boot/build/Deviation.c.deps -MT utils/hp2ps/dist-boot/build/Deviation.o -x c utils/hp2ps/Deviation.c
Exit code: 1
Stderr:
In file included from utils/hp2ps/Main.h:4:0,
                 from utils/hp2ps/Deviation.c:1:
includes/ghcconfig.h:4:25: fatal error: ghcautoconf.h: No such file or directory
compilation terminated.
)
```

**Comment by snowleopard** [comment]
Right. I believe there no build rules for `includes` yet. My understanding is that there are just a bunch of autogenerated files there, so the rules will go to `Rules/Generate.hs`.

As a temporary workaround you might ask `make` to build `includes` -- is this possible?

**Comment by snowleopard** [comment]
I will have time to implement build rules for `includes` tonight.

@bgamari Please assign yourself to this issue if you'd like to hack on it earlier so we don't duplicate our efforts.

**Comment by angerman** [comment]
Any updates on this? This is the very first thing that halts the build.

I think this is the relevant section from `includes/ghc.mk`
```
$(includes_H_CONFIG) : mk/config.h mk/config.mk includes/ghc.mk | $$(dir $$@)/.
        @echo "Creating $@..."
        @echo "#ifndef __GHCAUTOCONF_H__"  >$@
        @echo "#define __GHCAUTOCONF_H__" >>$@
#
#       Copy the contents of mk/config.h, turning '#define PACKAGE_FOO
#       "blah"' into '/* #undef PACKAGE_FOO */' to avoid clashes.
#
        @sed 's,^\([     ]*\)#[  ]*define[       ][      ]*\(PACKAGE_[A-Z]*\)[   ][     ]*".*".*$$,\1/* #undef \2 */,' mk/config.h >> $@
#
#       Tack on some extra config information from the build system
#
ifeq "$(GhcEnableTablesNextToCode) $(GhcUnregisterised)" "YES NO"
        @echo >> $@
        @echo "#define TABLES_NEXT_TO_CODE 1" >> $@
endif
#
ifeq "$(CC_LLVM_BACKEND)" "1"
        @echo >> $@
        @echo "#define llvm_CC_FLAVOR 1" >> $@
endif
#
ifeq "$(CC_CLANG_BACKEND)" "1"
        @echo >> $@
        @echo "#define clang_CC_FLAVOR 1" >> $@
endif
#
        @echo "#endif /* __GHCAUTOCONF_H__ */"          >> $@
        @echo "Done."

endif
```

**Comment by snowleopard** [comment]
I think we will have to implement all `includes` rules for things to work well, not just for `includes/ghcautoconf.h`.

Is it possible to ask `make` to build everything in `includes` as a temporary solution?

**Comment by angerman** [comment]
I wasn't able to only generate the `.h` files. running make in the `includes` folder or even only on `includes/ghcautoconf.h` builds a lot, and doesn't stop when `ghcautoconf.h` is generated. Maybe someone else can help us out here? And if so, that should be added to the `README.md`.

**Comment by snowleopard** [comment]
We will be coming across multiple similar issues due to missing bit and pieces in the new build system.

I think we should add `make` step in `README.md` -- this will create a full working build and we will then be running the new build system on top of it. That is what I do, as I already mentioned in #32.

**Comment by snowleopard** [comment]
I created a separate issue for implementing build rules for `includes`: #39.

In the meanwhile, I don't see a better way than to work on top of `make` build.

**Comment by snowleopard** [comment]
I've implemented a generator for `includes/ghcautoconf.h`: 6b7b9cc.
