### ISSUE TITLE
GNU-specific linker option is used even when GCC is not using GNU linker

### ISSUE THREAD

**Issue by kgardas** [snowleopard/shaking-up-ghc#164]
On Solaris compilation fails with:
```
 -I/tmp/shake-test/includes/dist-derivedconstants/header -optP-include -optP.build/stage1/libraries/base/build/autogen/cabal_macros.h -this-package-key base -XHaskell2010 -optP-DOPTIMISE_INTEGER_GCD_LCM -odir .build/stage1/libraries/base/build -hidir .build/stage1/libraries/base/build -stubdir .build/stage1/libraries/base/build -rtsopts -H32m -O2 -c libraries/base/GHC/Float.hs -o .build/stage1/libraries/base/build/GHC/Float.o
Exit code: 1
Stderr:
ld: fatal: unrecognized option '--'
ld: fatal: use the '-z help' option for usage information
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
)
```
this is due to internal GCC invocation which looks
```
*** Linker:
/usr/bin/gcc -U__i686 -fno-stack-protector -DTABLES_NEXT_TO_CODE -nostdlib -Wl,-r -nodefaultlibs '-Wl,--build-id=none' -o .build/stage1/libraries/base/build/GHC/Float.o /tmp/ghc11114_0/ghc_9.ldscript
```
```--build-id=<something>``` is GNU specific option not supported by the Solaris linker.

**Comment by snowleopard** [comment]
Could you find the corresponding piece of code in the old build system, which provides different command line options for non-GNU linkers? This could speed up the resolution of both this issue and #165.

**Comment by kgardas** [comment]
@snowleopard mk/config.mk contains following code:
```
# GNU ld supports input via a linker script, which is useful to avoid
# overflowing command-line length limits.
LdIsGNULd               = NO

# Set to YES if ld has the --build-id flag.  Sometimes we need to
# disable it with --build-id=none.
LdHasBuildId            = NO
```
as you can see, on Solaris both are NO. I guess if  you put those variables (LdIsGNULd/LdHasBuildId) into your system.config values then you can use them to decide if to use --build-id linker command-line option or linker script. The only question is if current code does have support to run w/o linker script.

**Comment by snowleopard** [comment]
@kgardas Sure, we can add these variables to `system.config`. However, I don't see how they are used in the old build system. I can only find this piece of code, which is only relevant with `--split-sections`:
```
ifeq "$$($1_$2_SplitSections)" "YES"
ifeq "$(LdIsGNULd)" "YES"
$1_$2_LD_SCRIPT = driver/utils/merge_sections.ld
endif
endif
```
We currently do not support `--split-sections`. 

Could you show the full command line which fails? I wonder where `--build-id` comes from: we certainly don't have it in the new build system. Perhaps it comes from `cabal` settings somehow.

**Comment by kgardas** [comment]
@snowleopard this was false path, probably some left-over. Anyway, what seems to be relevant is that both values are set into generated settings file and from this loaded and affects SysTools/DriverPipeline haskell code. Grep for
```
       ldSupportsCompactUnwind <- getBooleanSetting "ld supports compact unwind"
       ldSupportsBuildId       <- getBooleanSetting "ld supports build-id"
       ldSupportsFilelist      <- getBooleanSetting "ld supports filelist"
       ldIsGnuLd               <- getBooleanSetting "ld is GNU ld"
```
in SysTools and for ```GnuLd``` in DriverPipeline and you will find them.

**Comment by snowleopard** [comment]
Interesting, thanks for finding this. However, I don't see how the build system is involved:
* File `settings` is produced by `configure` from `settings.in`
* File `settings` is used directly by GHC, and apparently this is where the failure occurs.
How can this be fixed in the build system? Does the old build system work for you?

**Comment by snowleopard** [comment]
@kgardas You still haven't provided the the full command line which fails -- please do. We may be able to locate the flag responsible for this failure.

**Comment by kgardas** [comment]
@snowleopard please hold on, this whole may turn out as a simple user error.

**Comment by kgardas** [comment]
@snowleopard Please close that. It looks like it was really a user error. Since GMP build done in tree required GNU patch (already reported) and can't use gpatch but insist on patch I've put /usr/gnu/bin in front of my PATH. The problem is in unnoticed ld which also resides there. This is a GNU ld. It looks like GHC's configure is clever enough and still was detecting Sun Linker -- probably by using GNU C, but libraries/ configure is not so clever and detected GNU linker and then choked on linking by Sun linker. That's whole story of this issue and #165 . Please close both. Thanks and sorry for noise.

**Comment by snowleopard** [comment]
@kgardas No problem and many thanks for the clarification!

I'll close both #164 and #165 and will prepare a fix for the `patch/gpatch` issue.
