### ISSUE TITLE
GNU specific linker script is used on non-GNU linker platforms

### ISSUE THREAD

**Issue by kgardas** [snowleopard/shaking-up-ghc#165]
Current linking stage is using GNU linker script like:
```
*** Linker:
/usr/bin/gcc -U__i686 -fno-stack-protector -DTABLES_NEXT_TO_CODE -nostdlib -Wl,-r -nodefaultlibs '-Wl,--build-id=none' -o .build/stage1/libraries/base/build/GHC/Float.o /tmp/ghc11114_0/ghc_9.ldscript
```
this ``` /tmp/ghc11114_0/ghc_9.ldscript``` is unsupported for example on Solaris linker which complains about
```
ld: fatal: file /tmp/ghc11114_0/ghc_9.ldscript: not an ELF object
collect2: error: ld returned 1 exit status
```
related to #164

**Comment by snowleopard** [comment]
This is not an issue any more, see https://github.com/snowleopard/shaking-up-ghc/issues/164#issuecomment-171779674.
