### ISSUE TITLE
Use configure to detect the right `make` command

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#167]
The initial discussion started in #157 and #159. At the moment we have `makeCommand` in `Settings/User.hs` which has to be set manually.

We should instead add the following to `system.config.in`:
```
make = @MakeCmd@
```
And ask `configure` to set `@MakeCmd@` to `make` or `gmake` using the approach outlined by @kgardas here: https://github.com/snowleopard/shaking-up-ghc/issues/159#issuecomment-171243085. 

This is similar to what happens with many other `Builder`s. I'd appreciate if someone familiar with `configure` picks this up.

What needs to be done:
- [x] Submit a patch to GHC's `configure`.
- [x] Remove `makeCommand`.
- [x] Add `make` as a `Builder`.
- [ ] Fix `runMake` function in `Rules/Actions.hs`.

**Comment by kgardas** [comment]
configure machinery done here: https://phabricator.haskell.org/D1775

**Comment by snowleopard** [comment]
@kgardas Awesome! Once this is in GHC HEAD I can take care of the rest.
