### ISSUE TITLE
Using system GMP fails on Travis Linux

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#173]
After #168 we can detect system GMP on Travis instances, however, the Linux one then fails with a link error, similar to what I get on Windows, https://github.com/snowleopard/shaking-up-ghc/pull/168#issuecomment-171639193:
```
[...]
/home/travis/build/snowleopard/shaking-up-ghc/ghc/.build/stage1/libraries/integer-gmp/build/libHSinteger-gmp-1.0.0.1.a(Type.o): In function `cmbQ_info':
(.text+0x16372): undefined reference to `__gmpn_mod_1'
collect2: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
```
A GMP framework is also detected on the OS X instance, but it doesn't lead to the link error.

Note, the build log contains the following:
```
| Create directory .build/stage0/gmp
/------------------------------------------------------------------------------\
| Run Tar (stage = Stage0, package = integer-gmp)                              |
|      input:libraries/integer-gmp/gmp/tarball/gmp-5.0.3-nodoc-patched.tar.bz2 |
|  => output:.build/stage0/gmp                                                 |
\------------------------------------------------------------------------------/
| Apply .build/stage0/gmp/gmpsrc.patch
| Apply .build/stage0/gmp/gmp-5.0.4.patch
| Run configure in .build/stage0/libffi...
| Run configure in .build/stage0/gmp/gmp-5.0.3...
| Create directory .build/stage0/gmp/include
| GMP library/framework detected and will be used
/------------------------------------------------\
| Copy file                                      |
|      input:libraries/integer-gmp/gmp/ghc-gmp.h |
|  => output:.build/stage0/gmp/include/ghc-gmp.h |
\------------------------------------------------/
| Successfully built custom library 'integer-gmp'
```

Link to the Travis log: https://api.travis-ci.org/jobs/102343020/log.txt?deansi=true.

**Comment by snowleopard** [comment]
@kgardas Have you come across the same error on Solaris?

**Comment by kgardas** [comment]
@snowleopard no, at least not yet. But the question is if I get that far at all. You know #164 & #165

**Comment by snowleopard** [comment]
@kgardas I see. Sorry I can't help much with #164 and #165 as I can't reproduce these issues on Windows. I will try to fix this one though, because it seems to be reproducible on Windows.

**Comment by kgardas** [comment]
@snowleopard Solaris is probably hurt by this issue too, not sure, don't see enough of your failure. My failure looks:
```
<a lot of messages>
__gmpz_sizeinbase                   /tmp/shake-test/.build/stage1/libraries/integer-gmp/build/libHSinteger-gmp-1.0.0.1.a(wrappers.o)
__gmpn_divrem_1                     /tmp/shake-test/.build/stage1/libraries/integer-gmp/build/libHSinteger-gmp-1.0.0.1.a(Type.o)
__gmpn_tdiv_qr                      /tmp/shake-test/.build/stage1/libraries/integer-gmp/build/libHSinteger-gmp-1.0.0.1.a(wrappers.o)
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
)
```
and is cause by simple fact that build system completely omits -optl-lgmp from the linking arguments. This is when using system supplied GMP and when using appropriate --with-gmp-* flags for configuration. When I added -optl-lgmp to the problematic line the binary was linked well...

**Comment by snowleopard** [comment]
Thanks @kgardas. 

I attempted a fix based on your comment. Let's see if it works.

**Comment by kgardas** [comment]
Now, my build passes all the way long up to the point of:
```
/---------------------------------------------------------------\
| Successfully built program 'compareSizes' (Stage1).           |
| Executable: utils/compare_sizes/stage1/build/tmp/compareSizes |
| Program synopsis: Size comparison utility.                    |
\---------------------------------------------------------------/
shakeArgsWith                         0.000s    0%                           
Function shake                        0.061s    0%                           
Database read                         0.747s    0%                           
With database                         0.034s    0%                           
Running rules                      4271.027s   99%  =========================
Pool finished (22782 threads, 1 max)  0.000s    0%                           
Lint checking                         0.115s    0%                           
Total                              4271.986s  100%                           
Lint checking error - value has changed since being depended upon:
  Key:  libraries/integer-gmp/integer-gmp.buildinfo
  Old:  File {mod=0xACF0D705,size=0x87,digest=NEQ}
  New:  File {mod=0xAE28D93E,size=0x84,digest=NEQ}
```
I'm not sure if this is a failure or what...

**Comment by ndmitchell** [comment]
This says that something depended on integer-gmp.buildinfo, and then later it changed. Perhaps some unrelated rule touched it? Perhaps the dependency was insufficient? It's a warning from the build system error, so everything built properly, but if you were to rebuild again right now, more stuff would rebuild, which isn't great.

**Comment by snowleopard** [comment]
@kgardas Thanks, I see what's going on:
* When building GMP, we run the configure script inside `libraries/integer-gmp` to determine whether there is a system GMP library installed, and which one, by looking into produced files `config.mk` and `integer-gmp.buildinfo`.
* Later on the build process, the `integer-gmp` library is built, which also involves running the configure script (`ghc-cabal` performs it and we currently don't know how to avoid this, see #18).
* This second configure updates `integer-gmp.buildinfo` file again, and even though it is exactly the same as the first time, the build system raises a warning that we've done something suspicious: changed a file after we read it.

Not sure yet what would be the best solution, but it's great to hear that the build was successful for you!

**Comment by snowleopard** [comment]
Note Travis now also fails with the lint error mentioned by @kgardas.

**Comment by snowleopard** [comment]
So here's how I resolved this: I stopped tracking `integer-gmp.buildinfo` for now, switching from Shake's `readFileLines` to `liftIO . readFile`. When/if we resolve #18 we will be able to bring the tracking back.
