### ISSUE TITLE
Tracking bootstrapping.conf and package.conf.d directories

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#176]
@kgardas reports the following, https://github.com/snowleopard/shaking-up-ghc/issues/174#issuecomment-172203788:
> I usually hit following error when rm -rf .build inplace and when starting build without -B option:
```
user error (Development.Shake.cmd, system command failed
Command: /opt/ghc-7.10.1-i386/bin/ghc -hisuf hi -osuf o -hcsuf hc -static -no-user-package-db -package-db /tmp/shake-test/.build/stage0/bootstrapping.conf -i -i.build/stage0/utils/hp2ps/build -i.build/stage0/utils/hp2ps/build/autogen -I.build/stage0/utils/hp2ps/build -I.build/stage0/utils/hp2ps/build/autogen -odir .build/stage0/utils/hp2ps/build -hidir .build/stage0/utils/hp2ps/build -stubdir .build/stage0/utils/hp2ps/build -rtsopts -H32m -O -no-auto-link-packages -optl-lm -optl-lgmp .build/stage0/utils/hp2ps/build/AreaBelow.o .build/stage0/utils/hp2ps/build/Curves.o .build/stage0/utils/hp2ps/build/Error.o .build/stage0/utils/hp2ps/build/Main.o .build/stage0/utils/hp2ps/build/Reorder.o .build/stage0/utils/hp2ps/build/TopTwenty.o .build/stage0/utils/hp2ps/build/AuxFile.o .build/stage0/utils/hp2ps/build/Deviation.o .build/stage0/utils/hp2ps/build/HpFile.o .build/stage0/utils/hp2ps/build/Marks.o .build/stage0/utils/hp2ps/build/Scale.o .build/stage0/utils/hp2ps/build/TraceElement.o .build/stage0/utils/hp2ps/build/Axes.o .build/stage0/utils/hp2ps/build/Dimensions.o .build/stage0/utils/hp2ps/build/Key.o .build/stage0/utils/hp2ps/build/PsFile.o .build/stage0/utils/hp2ps/build/Shade.o .build/stage0/utils/hp2ps/build/Utilities.o -o inplace/bin/hp2ps -no-hs-main
Exit code: 1
Stderr:
ghc: can't find a package database at /tmp/shake-test/.build/stage0/bootstrapping.conf
)
```
this is very reproducible. Perhaps also pointing to a need to have proper shake clean way...

The problem is: at the moment we don't track `bootstrapping.conf` and `package.conf.d` directories in a correct way. The wrong solution, which is currently in place, is to use files `package-configuration-initialised-stageN` stored in Shake's database as indicators of whether the directories have been initialised by `ghc-pkg init`. In this way if one deletes one of these directories, but doesn't delete the corresponding indicator file, the build system gets confused.

It would be great if Shake supported `need` on a directory and corresponding build rules. However, as I understand this is currently not supported. @ndmitchell Any comments on this? Having first class support for directory targets may be useful I think.

One possible solution: Move the indicator files into the directories they track. This might work, although not sure it's completely reliable.

Note, we can't track this using `doesDirectoryExist` as this would lead to a Shake's lint error. We also can't track any existing files inside the directories, because the only file which is created together with the directory (`package.cache`) is updated multiple times during the build by `ghc-pkg`, which would also lead to a Shake's lint error.

**Comment by snowleopard** [comment]
I've implemented the only solution I can see: moved the indicator files into the directories they track. I'll keep this open for a while, maybe someone will come up with a better approach.

**Comment by ndmitchell** [comment]
What would need on a directory do? I can't think of any semantics beyond `need =<< getDirectoryFiles dir ["**"]`. And that's not going to help you anyway.

**Comment by snowleopard** [comment]
Here is what I would like to do: _If the directory does not exist, run the build rule that will create it._

Here is what my workaround does: _If the indicator file in the directory does not exist or is not fresh, run the build rule that will create both the directory and the indicator file._

(Note, the freshness check is redundant as the timestamp & contents of the indicator file are irrelevant.)

Maybe calling this `need` is wrong, because no freshness check should be involved.

@ndmitchell Do you see any problem with my workaround? Would you solve this problem differently?

**Comment by ndmitchell** [comment]
Stamps inside the directory seems a very good way to go. You aren't really needing the directory, you need a file inside it. You could track the creation of the file with a special type of rule that does not look at timestamp, but that's way too much hassle.

**Comment by ndmitchell** [comment]
In fact, an oracle which creates if necessary and returns () perfectly captures the dependency and is fully robust.

**Comment by snowleopard** [comment]
Aha, sounds good. Something like this?
```haskell
addOracle $ \PackageDb dir -> unlessM (doesDirectoryExist dir) $ createPackageDb dir

initialisePackageDb :: Stage -> Action ()
initialisePackageDb stage = askOracle . PackageDb $ packageDb stage
```

**Comment by ndmitchell** [comment]
Use doesDirectoryExist in IO not Action to avoid the lint failure. Probably use doesFileExist on the .cache file for more robustness if someone just deletes the file.

**Comment by snowleopard** [comment]
M-m, I'm a bit confused now. Since this always runs and never invalidates the build, then why use oracles? I guess the following `Action` will do:
```haskell
initialisePackageDb :: Stage -> Action ()
initialisePackageDb stage = unlessM (liftIO $ IO.doesDirectoryExist dir) $ createPackageDb dir 
  where
    dir = packageDb stage
```

**Comment by ndmitchell** [comment]
That action does one directory check every time (probably not actually expensive in practice) and might have a race - if you use a db while being created (not sure if the db rules).

**Comment by snowleopard** [comment]
Aha, so the difference is: the oracle action will run every build _but only once_, while the non-oracle action will run every time it is called, in particular the file/directory check will be done each time.

For me that's a good enough reason to prefer the oracle solution.

**Comment by snowleopard** [comment]
Fix delayed as I came across a nasty import cycle:
* `Action.Rules.build` requires `getArgs` from `Settings.Args` to determine the list of arguments to pass to the builder.
*  `getArgs` is computed by collecting arguments for all builders, in particular `ghcCabalBuilderArgs` living in `Settings.Builders.GhcCabal`.
* `ghcCabalBuilderArgs` needs to call the `PackageDb` oracles that in turn relies on `Action.Rules.build` for running `GhcPkg` builder (to initialise the package database).

Not sure how to get rid of the cycle.

**Comment by snowleopard** [comment]
OK, I managed to break the cycle. An oracle-based fix is now submitted.
