### ISSUE TITLE
configure fails

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#189]
I checked out a fresh GHC and tried to build from scratch using `--configure=--enable-tarballs-autodownload`. It failed with.

    configure: error: in `C:/Neil/ghc':
    configure: error: C compiler cannot create executables
    See `config.log' for more details

I then ran `./configure --enable-tarballs-autodownload` by hand and it said:

    configure: Checking for Windows toolchain tarballs...
    checking for gcc... C:/Neil/ghc/inplace/mingw/bin/gcc.exe
    checking whether the C compiler works... no
    configure: error: in `/c/Neil/ghc':
    configure: error: C compiler cannot create executables
    See `config.log' for more details

In neither case did `config.log` say anything interesting. I cleaned everything and reran `boot`/`configure` by hand and it worked. I then ran `shake-build/build.bat -j` and it said:

    Configuration file shake-build/cfg/system.config is missing.
    Run the configure script either manually or via the build system by passing --configure[=ARGS] flag.`

That seems to be no longer true, as I've already run `configure`. I then passed `--configure=--enable-tarballs-autodownload` and it now seems to be working (at least it's got a lot further). 32bit Windows.

**Comment by snowleopard** [comment]
Hmm, can you try to reproduce the following:
* Check out a fresh GHC
* Run `./boot`
* Run `./configure --enable-tarballs-autodownload`

At this point `shake-build/cfg/system.config` is missing (if we believe the error message). If this is the case, it means the problems start before the build system had any chance to do anything.

**Comment by ndmitchell** [comment]
Three scenarios:

* Fresh checkout. Run shake --config runner. Fails.
* Fresh checkout. Run shake --config runner. Fails. Then run boot, configure. Fails.
* Fresh checkout. Run boot, configure, shake --config runner. Succeeds.

So I don't know what about preconfiguring makes it works, and I don't know how a shake --config breaks future configures, but it does seem to... At first I thought this was a general GHC problem, until I started from scratch once more.

**Comment by snowleopard** [comment]
Could you try the 'traditional' scenario?
* Fresh checkout
* `./boot`
* `./configure --enable-tarballs-autodownload`
* `shake-build/build.bat`

**Comment by snowleopard** [comment]
Another useful experiment:
* Fresh checkout
* `shake-build/build.bat --configure configure`
* `./configure --enable-tarballs-autodownload`
* `shake-build/build.bat`

Note: in the second step, the build system should run boot only, allowing us to test it in isolation.

**Comment by ndmitchell** [comment]
When I tried that it said:

    Configuration file shake-build/cfg/system.config is missing.
    Run the configure script either manually or via the build system by passing --configure[=ARGS] flag.`

**Comment by snowleopard** [comment]
Can you check the file is indeed missing? I think this means the build system is not to blame.

**Comment by ndmitchell** [comment]
Why would you expect running ./configure to generate anything in shake-build? Unfortunately I doubt I'll have time to run any more scenarios tonight (have to pack). Tomorrow I might manage to squeeze in one before I leave, but might not.

**Comment by snowleopard** [comment]
> Why would you expect running ./configure to generate anything in shake-build? 

Well, that's how it's supposed to work: https://github.com/ghc/ghc/blob/master/configure.ac#L1094-L1097
```
# Create the configuration for the Shake-based build system if it is present
if test -e shake-build/cfg/system.config.in; then
    AC_CONFIG_FILES([shake-build/cfg/system.config])
fi
```

**Comment by ndmitchell** [comment]
Ahha! I think I did a fresh checkout, configured ghc, and _next_ checked out the shake pieces. My intention was to guarantee there could be no interference with the fresh Shake bits. I guess I succeeded too well! At least that explains some of it.

**Comment by snowleopard** [comment]
Aha, that sounds like a possible explanation! I was actually wondering how to make this a bit more robust w.r.t. to the order of configure vs shake checkout. I expect other people might fall into this trap too.

**Comment by ndmitchell** [comment]
So we're left with shake-build --configure is broke on my system, plus there is one order where things break badly. Two separate issues, one clearly understood, one not.

**Comment by snowleopard** [comment]
So, coming back to the failure of `shake-build/build.bat --configure`. This seems to be the key:
```
configure: Checking for Windows toolchain tarballs...
checking for gcc... C:/Neil/ghc/inplace/mingw/bin/gcc.exe
checking whether the C compiler works... no
```
The tarball with `gcc` was downloaded (I assume it is present at `C:/Neil/ghc/inplace/mingw/bin/gcc.exe`), but the executable is somehow broken. Can you run it by hand? Could it be a network issue? Or are we back to the issue with mismatching environment variables?

**Comment by ndmitchell** [comment]
Checking the new config logs, it seems the "real" configure also used gcc, which I assume means it worked, since I have a working build. Running `--version` works. I would love to get what error message configure got when it "checked gcc" and found it wanting, but I have no idea how to do that. I don't think there's a network issue. Some kind of environmental issue seems most likely.

**Comment by ndmitchell** [comment]
For the `configure` not being in the right place, I suggest that _before_ shakeWithArgs you do a check. If the GHC configured one exists, but the Shake configured one doesn't, you copy across. That should patch things up without involving the build system, and the `--configure` will be obeyed properly.

**Comment by snowleopard** [comment]
> For the `configure` not being in the right place

But `configure` is in the right place, I never copy it. I run the usual top-level `configure`.

The issue is with the error message:
```
Configuration file shake-build/cfg/system.config is missing.
Run the configure script either manually or via the build system by passing --configure[=ARGS] flag.
```
I could make it more friendly: if I detect that `configure` did run, but _before shake-build was cloned_, I could give a different error, perhaps hinting that one needs to run `configure` again.

**Comment by ndmitchell** [comment]
Ah, I didn't realise configure actually has meaningful differences in the presence of shake, I thought it was just copying a file.

**Comment by ndmitchell** [comment]
I checked out two fresh repos from scratch, and did `./boot && ./configure` in one (which I called `old-configure`) and `shake-build/build.bat --configure=--enable-tarballs-autodownload -j` in the other (named `new-configure`). `old` succeeded, but `new` failed. Looking at the differences in `config.log`, I see:

* `old` invoked `./configure`, while new just called `configure`.
* `old` had `/bin` on the `$PATH`.

Neither of these look like a real problem.

It then lead to an error when invoking `inplace/mingw/bin/gcc.exe`. Diffing the two `inplace/mingw/bin` directories, `old` contained `gcc.exe` while `new` had every other file but was missing `gcc.exe`. Looking at `configure.ac` line 345 I see:

        # NB. Now since the GCC is hardcoded to use /mingw32 we need to
        # make a wrapper around it to give it the proper paths
        mv inplace/mingw/bin/gcc.exe inplace/mingw/bin/realgcc.exe
        PATH=`pwd`/inplace/mingw/bin:$PATH
        inplace/mingw/bin/realgcc.exe driver/gcc/gcc.c driver/utils/cwrapper.c driver/utils/getLocation.c -Idriver/utils -o inplace/mingw/bin/gcc.exe

So it does seem to be moving `gcc` to `realgcc` then compiling a fresh `gcc` in it's place. If I run the change of `PATH` followed by the following `realgcc` line then it does create the `gcc.exe`. I am just trying to get more out of configure.

**Comment by snowleopard** [comment]
@ndmitchell Impressive investigation :+1: 

> NB. Now since the GCC is hardcoded to use /mingw32 we need to

I don't understand this. Where exactly is GCC hardcoded? I believe the new build system doesn't care where GCC lives as long as `configure` provides the right path to it in `system.config` (in fact, we could even easily look it up in PATH automatically). I also don't think that the old build system relied on a hardcoded GCC. Very strange.

Just out of curiosity: if you comment out these GCC manipulations in `configure.ac`, will the build succeed? 

> If I run the change of `PATH` followed by the following `realgcc` line then it does create the `gcc.exe`.

Are you saying we need to modify the `PATH` variable before running `configure`? We can easily do this.

**Comment by ndmitchell** [comment]
So, what's meant to happen in configure is:

* Extract the tarballs
* Rename gcc.exe to realgcc.exe
* Change the PATH to put the new mingw tarballs on the PATH
* Compile a fresh gcc.exe using realgcc.exe

That works normally, but not when you run configure from inside the build system. I need a few more configure edits to figure out exactly what's gone wrong. Best current guess is that `pwd` is returning a different value, but I'm not totally convinced. I need to debug the PATH. I'll have more info tomorrow evening.

**Comment by ndmitchell** [comment]
OK, I've tracked down a more direct cause of the bug. Configure does:

    PATH=`pwd`/inplace/mingw/bin:$PATH

When I run `./configure` on the command line, `pwd` reports as `/c/Neil/ghc/conf2/ghc/inplace/mingw/bin`. When the build system runs `configure`, then `pwd` reports as `C:/Neil/ghc/conf/ghc/inplace/mingw/bin`. The second `:` screws everything up and means the new things are not on the PATH. I'm not sure _why_ `pwd` changes - any ideas? Note that `pwd` in the shell reports as `/c/Neil/...`.

**Comment by snowleopard** [comment]
Note, this is similar to the problem we had with `ACLOCAL` paths starting with `C:`. In that case we could work around this in Haskell land.

Could `pwd` be taking the path from the `PWD` environment variable? If yes, we could replace it a correct path in `Environment.hs`.

**Comment by snowleopard** [comment]
On my machine:
```bash
$ echo $PWD
/home/nam83/ghc/shake-build
```

However
```haskell
Just pwd <- lookupEnv "PWD"
putStrLn $ "PWD = " ++ pwd
```
prints `PWD = D:/msys/home/nam83/ghc/shake-build`.

@ndmitchell Can you try setting `PWD` to `/c/Neil/...` in `Environment.hs`?

**Comment by ndmitchell** [comment]
If `$PWD` is set then `pwd` returns it. If `PWD` isn't set, then `pwd` computes the current working directory. MinGW sets `PWD` to be a `/c` path, then spawns our Windows binary using a `C:/` path, and then we spawn configure keeping the `/c` path. Much simpler to just unconditionally clear `PWD`, which fixes the issue, and makes it use the real current directory, which is what we actually want. I've done that in #199.
