### ISSUE TITLE
Better naming convention for build directories

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#19]
The old build system used a variety of different names for build directories: `dist`, `dist-boot`, `dist-install`, `stage1`, etc.

Proposal: always use `stageN` as the build directory when using `stageN` compiler. This will simplify the build system considerably.

One potential inconvenience: in the old build system, `ghc-stage2` executable lived in `stage2` directory. Under this proposal `ghc-stage2` will live in `stage1` directory, because it is built by `stage1` compiler. Admittedly this may be confusing for the long-time users of the old build system, however I think this is logically consistent.

**Comment by snowleopard** [comment]
I'll give it a try today. Please shout if you have any concerns about this proposal.

**Comment by hvr** [comment]
This sounds intriguing

> Under this proposal ghc-stage2 will live in stage1 directory, because it is built by stage1 compiler. 

...and where will `ghc-stage1` then be located? :-) (and what will be found in `/stage2` then?)

/cc @thomie

**Comment by snowleopard** [comment]
> ...and where will ghc-stage1 then be located? :-)

Well, in `/stage0` :-) The bootstrapping compiler is referred to as `Ghc Stage0` in the new build system. Does this make sense?

> ...the stage0/ folder would countain binaries and object-code runnable on the build-host, while stage1/ would contain binaries and object-code compiled for the target-arch. That appears to be nicely consistent

Indeed! That's another bonus I didn't think about.

**Comment by snowleopard** [comment]
I've implemented this and it works smoothly so far: 52ecf6c.

It's possible to rollback to the old naming convention without much difficulty if need be.
