### ISSUE TITLE
stack and GHC_PACKAGE_PATH

### ISSUE THREAD

**Issue by cocreature** [snowleopard/shaking-up-ghc#191]
When I try to run `./shake-build/build.stack.sh --configure` I run into the following error:
```
| Run configure...
Reading shake-build/cfg/system.config...
Found 'make' at '/usr/bin/make'
/---------------------------------------------------------------------\
| Copy file                                                           |
|      input: includes/dist-derivedconstants/header/platformConstants |
|  => output: inplace/lib/platformConstants                           |
\---------------------------------------------------------------------/
Reading package dependencies...
Reading .build/stage0/utils/unlit/package-data.mk...
Reading dependencies from .build/stage0/utils/unlit/build/.dependencies...
Reading .build/stage0/utils/hp2ps/package-data.mk...
Reading dependencies from .build/stage0/utils/hp2ps/build/.dependencies...
Reading .build/stage0/utils/ghc-cabal/package-data.mk...
/-----------------------------------------------------\
| Run GhcCabal (stage = Stage0, package = binary)     |
|      input: libraries/binary/binary.cabal           |
|  => output: libraries/binary/stage0/package-data.mk |
\-----------------------------------------------------/
Configuring binary-0.8.0.0...
ghc-cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible
with Cabal. Use the flag --package-db to specify a package database (it can be
used multiple times).
shakeArgsWith   0.000s    0%                           
Function shake  0.038s    0%                           
Database read   0.007s    0%                           
With database   0.000s    0%                           
Running rules   7.460s   99%  =========================
Total           7.505s  100%                           
Error when running Shake build system:
* inplace/bin/ghc-pkg
* inplace/lib/bin/ghc-pkg
* OracleQ (PackageDataKey (".build/stage0/utils/ghc-pkg/package-data.mk",".build_stage0_utils_ghc-pkg_C_SRCS"))
* .build/stage0/utils/ghc-pkg/package-data.mk
* .build/stage0/utils/ghc-pkg/package-data.mk utils/ghc-pkg/stage0/package-data.mk
* .build/stage0/libraries/binary/package-data.mk
* .build/stage0/libraries/binary/package-data.mk libraries/binary/stage0/package-data.mk
user error (Development.Shake.cmd, system command failed
Command: inplace/bin/ghc-cabal configure libraries/binary stage0  --with-ghc=/home/moritz/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc --with-ghc-pkg=/home/moritz/.stack/programs/x86_64-linux/ghc-7.10.3/bin/ghc-pkg --package-db=/home/moritz/code/haskell/ghc/.build/stage0/bootstrapping.conf --enable-library-vanilla --enable-library-for-ghci --disable-library-profiling --disable-shared --with-hscolour=/home/moritz/.local/bin/HsColour --configure-option=CFLAGS=-fno-stack-protector --configure-option=CPPFLAGS=-Iincludes -Iincludes/dist-derivedconstants/header --gcc-options=-fno-stack-protector --configure-option=--with-cc=/usr/bin/gcc --constraint Cabal == 1.23.1.0 --constraint binary == 0.8.0.0 --constraint ghc-boot == 8.1 --constraint hoopl == 3.10.2.1 --constraint hpc == 0.6.0.3 --constraint template-haskell == 2.11.0.0 --constraint terminfo == 0.4.0.2 --constraint transformers == 0.5.0.0 --with-gcc=/usr/bin/gcc --with-ar=/usr/bin/ar --with-alex=/home/moritz/.local/bin/alex --with-happy=/home/moritz/.local/bin/happy
Exit code: 1
Stderr:
ghc-cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible
with Cabal. Use the flag --package-db to specify a package database (it can be
used multiple times).
)
```
It looks like the problem is that running inside of `stack exec` sets GHC_PACKAGE_PATH. The cabal sandbox script seems to work, but since the stack script is in the repo it’s probably supposed to work as well.

**Comment by ndmitchell** [comment]
I think we should be clearing the GHC PACKAGE flags, since we're already passing a package db path. A know stack vs cabal headache :(

**Comment by Ericson2314** [comment]
Agreed. And wouldn't probably interfere when bootstrapping anyways?

**Comment by snowleopard** [comment]
I also came across this problem when using Stack on AppVeyor.

> The cabal sandbox script seems to work, but since the stack script is in the repo it’s probably supposed to work as well.

Sure, we either need to fix it or drop from the repository. It was added in PR #190 by @joehillen. 

@joehillen have you come across this problem too? Did you find a workaround?

I could probably reset the `GHC_PACKAGE_PATH` variable from within the build system, but this looks unsatisfactory. Hopefully there is some command-line solution.

Can Stack be convinced not to set  `GHC_PACKAGE_PATH`?

**Comment by ndmitchell** [comment]
I think deleting the variable is the right thing to do even without stack. This is a variable that may get set for other reasons, and when set, breaks ghc-cabal. I personally consider this a bug in cabal, but easier to work around than fix.

**Comment by snowleopard** [comment]
@ndmitchell That's a good point. OK, I will prepare a fix. Something like this in `Main.hs`?
```haskell
System.Environment.unsetEnv "GHC_PACKAGE_PATH"
```

**Comment by snowleopard** [comment]
This should be fixed now, please reopen otherwise.

I decided to add a separate module `Environment` that will be responsible for setting up the environment.

**Comment by joehillen** [comment]
I wonder why I didn't hit this issue when I tested it. 

@snowleopard You should install stack. It's become a standard haskell dev tool. I haven't used cabal-install once since I started using it. http://docs.haskellstack.org/en/stable/README.html#how-to-install

**Comment by snowleopard** [comment]
@joehillen I am aware of Stack's advantages. However, the old build system didn't rely on it, so the new one shouldn't either. Of course, users of the build system are free to use whatever they like, but I need to stay away from Stack while I'm working on the build system to make sure it doesn't become a dependency by accident.
