### ISSUE TITLE
First Attempt Log

### ISSUE THREAD

**Issue by mpickering** [snowleopard/shaking-up-ghc#194]
Writing down the steps I had to go through on my first attempt to get the build to work.

1) Clone everything, works fine.
2) Get a bit confused about which build script I am meant to run, decided that `build.cabal.sh` looks the most promising. 
3) Have to manually edit `build.cabal.sh` and `cabal.config` to specify the compiler I want to use rather than the one on my patch.
4) Run `build.cabal.sh` again, run into this error

```
onfiguration file shake-build/cfg/system.config is missing.
Run the configure script either manually or via the build system by passing --configure[=ARGS] flag.
shakeArgsWith   0.000s    0%                           
Function shake  0.051s   66%  =========================
Database read   0.002s    2%                           
With database   0.000s    0%                           
Running rules   0.024s   30%  ===========              
Total           0.077s   99%                           
Error when running Shake build system:
* OracleQ (ConfigKey "host-os")
* shake-build/cfg/system.config
GHC build system error: Configuration file shake-build/cfg/system.config is missing.
Run the configure script either manually or via the build system by passing --configure[=ARGS] flag.
```

5) `ls configure` shows no results in the current directory. Maybe it means the normal configure script?
6) Run ./configure as normal
7) Ok, that worked, things start to happen
8) ... wait a bit (this is all very blue)
9) Another error

```
Error when running Shake build system:
* inplace/lib/bin/unlit
* OracleQ (LookupInPath "ghc-7.10")
Prelude.head: empty list
```

10) Investigates to try and find the problem...

11) I find the problem in `src/Builder.hs`, this is line 119

```
(p, False) -> lookupInPath (p -<.> exe)  
```

In this case `p = ghc-7.10.2` so the `-<.>` command strips off the `.2`. It seems that this is a windowsism so shouldn't happen on osx?

12) Removing that bit, start the build again. (GHC compilation begins)

13) Waiting... 

14) The time in the status bar is very wrong. It have been hovering at around 3 minutes, 90% for most of the build and stage 1 hasn't even built yet.

**Comment by snowleopard** [comment]
@mpickering Thanks a lot for your detailed report! Sorry you hit so many bumps on the way.

Let me go through your issues one by one:

> 2) Get a bit confused about which build script I am meant to run, decided that build.cabal.sh looks the most promising. 

I think I should add a warning to `README` that only `build.sh` and `build.bat` are supported at the moment. Other scripts have been added by several contributors mostly for their own use. They should all be considered experimental.

> 3) Have to manually edit build.cabal.sh and cabal.config to specify the compiler I want to use rather than the one on my patch.

As I understand correctly you wanted to do something like `./configure --with-ghc=`? There are two ways to achieve this:
* After cloning, run a standard sequence: `./boot`, `./configure --with-ghc=...`, `./build.sh`.
* After cloning, run `./build.sh --configure=--with-ghc=...`.

The former one is safer, but I hope the latter one will work too. I don't know whether `--configure=--with-ghc=...` flag also works correctly with `build.cabal.sh`. Could you please test all three ways?

> 4) Run build.cabal.sh again, run into this error

This means you didn't run the `configure` script and you didn't run `./build.sh --configure` either. I think `README` says quite clearly that you have to run this command. Maybe the last paragraph about `build.*.sh` alternatives is confusing and should be dropped altogether.

> 11) I find the problem in src/Builder.hs, this is line 119
`(p, False) -> lookupInPath (p -<.> exe)`

This is certainly a bug. It should be `p <.> exe` instead. Thanks for spotting it! I'll fix this asap.

> 13) Waiting...

What's the end result?

**Comment by mpickering** [comment]
I am currently building stage2, so I think that everything else should go as expected.

**Comment by snowleopard** [comment]
Thanks! Could you please test the `--configure="--with-ghc=<path/to/ghc>"` flag on a fresh clone? I think it should work both with `build.sh` and `build.cabal.sh` scripts. If it does, then the only remaining problem will be with the `-<.> exe` bug, which I am fixing now.

**Comment by snowleopard** [comment]
OK, the path bug should be fixed now.

**Comment by mpickering** [comment]
> As I understand correctly you wanted to do something like ./configure --with-ghc=? There are two ways > to achieve this:
>
> After cloning, run a standard sequence: ./boot, ./configure --with-ghc=..., ./build.sh.
> After cloning, run ./build.sh --configure=--with-ghc=....
> The former one is safer, but I hope the latter one will work too. I don't know whether --configure=--with-> ghc=... flag also works correctly with build.cabal.sh. Could you please test all three ways?

1. Doesn't work - `ghc` is hard coded into the `build.sh` script. 
2. The problem with `build.cabal.sh` is that it tries to install the dependencies with the compiler in your path. You really have to add a `cabal.config` script with the line `with-compiler: ghc-7.10.2`.

**Comment by mpickering** [comment]
Also, I can clean all artifacts with `./build.sh clean`? It might be worth putting that exact somewhere in the readme, it seems to be buried inside a paragraph.

**Comment by snowleopard** [comment]
> Doesn't work - ghc is hard coded into the build.sh script.

Oh, I see. That's a headache. I've created a separate issue for this: #196.

**Comment by snowleopard** [comment]
> Also, I can clean all artifacts with ./build.sh clean? It might be worth putting that exact somewhere in the readme, it seems to be buried inside a paragraph.

@mpickering Will the following be better as a `README` section?

----

#### Clean and full rebuild

* Run `shake-build/build.sh clean` to remove all build artefacts. Note, we are working towards a complete separation of GHC sources and build artefacts: #113.

* Run `shake-build/build.sh -B` to force Shake to rerun all rules, even if results of the previous build are still in the GHC tree.

**Comment by mpickering** [comment]
I think so. Thank you for your quick and useful responses.

**Comment by snowleopard** [comment]
Thanks @mpickering!

I am closing this issue now. Hopefully #195 and #196 won't take too much time to resolve.
