### ISSUE TITLE
Build shared libs (dyn way).

### ISSUE THREAD

**Issue by kgardas** [snowleopard/shaking-up-ghc#198]
I've not seen issue for this, but both my Solaris and OpenBSD builds end with missing shared libs:
```
bindisttest$ ../inplace/bin/ghc-stage2 -dynamic --make HelloWorld.lhs 
[1 of 1] Compiling Main             ( HelloWorld.lhs, HelloWorld.o )

HelloWorld.lhs:3:8: error:
    Failed to load interface for ‘Prelude’
    Perhaps you haven't installed the "dyn" libraries for package ‘base-4.9.0.0’?
    Use -v to see a list of the files searched for.
```
probably this is general issue and we do not build shared libs yet? If it's already noted somewhere please feel free to close it. Thanks!

**Comment by snowleopard** [comment]
@kgardas Yes, this is a general and very old issue: #4. I've copied your comment there.
