### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#201]
shake-build/build.bat clean
    shake-build/build.bat .build/stage1/libraries/integer-gmp/build/libHSinteger-gmp-1.0.0.0.a .build/stage1/libraries/ghc-prim/build/libHSghc-prim-0.5.0.0.a -j4 --profile

Gives:

    Error when running Shake build system:
    * .build/stage1/libraries/ghc-prim/build/libHSghc-prim-0.5.0.0.a
    * OracleQ (PackageDataKey (".build/stage1/libraries/ghc-prim/package-data.mk",".build_stage1_libraries_ghc-prim_C_SRCS"))
    * .build/stage1/libraries/ghc-prim/package-data.mk
    * .build/stage1/libraries/ghc-prim/package-data.mk libraries/ghc-prim/stage1/package-data.mk
    * .build/stage1/libraries/ghc-prim/build/GHC/PrimopWrappers.hs
    * .build/stage1/compiler/build/primops.txt
    user error (Development.Shake.cmd, system command failed
    Command: C:/Neil/ghc/conf/ghc/inplace/mingw/bin/gcc.exe -E -undef -traditional -P -Iincludes -Iincludes/dist-derivedconstants/header -I.build/stage1/compiler -x c compiler/prelude/primops.txt.pp
    Exit code: 1
    Stderr:
    In file included from compiler/prelude/primops.txt.pp:74:0:
    includes/MachDeps.h:20:0: fatal error: ghcautoconf.h: No such file or directory
     #include "ghcautoconf.h"
     ^
    compilation terminated.
    )

Looks like a missing dependency to me.

**Comment by snowleopard** [comment]
I will take care of this. This did happen to me once, but I forgot to prepare a fix.

**Comment by snowleopard** [comment]
Should be fixed now.
