### ISSUE TITLE
Configure flags are confusing

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#204]
As a Windows user, the first time I MUST run `--configure=--enable-tarballs-autodownload`. If I run with those flags in any subsequent run, then I end up reconfiguring and doing most of the rebuild from scratch. That's nasty, meaning my first run, and every run that has already got past configure, must use different flags. Can I suggest:

* If Windows really does require those configure flags, make them the default.
* There is a difference between `--configure` meaning "run configure with these flags", and "these are the settings required for configure". I'm on the fence as to what configure should mean, but the current state doesn't seem great. One option would be to say the configure flags are tracked, and we run configure if they change, but that means Windows users would always have to include `--enable-tarballs-autodownload` - but that's really a weird flag, because its an action for configure to perform, not a setting for configure to check.

I think just making `--enable-tarballs-autodownload` the default on Windows would let us side-step most of these issues for now.

**Comment by ndmitchell** [comment]
OK, so seems there are a lot of issues going on here. Is there any reason not to make `--enable-tarballs-autodownload` the default on Windows? Under what circumstances is it a bad idea?

**Comment by ndmitchell** [comment]
(Selfishly, this would mean _I_ never have to deal with configure flags again :smile: )

**Comment by snowleopard** [comment]
Yes, I did consider passing `--enable-tarballs-autodownload` by default on Windows. The only downside I see is that the semantics of `--configure` becomes even more complicated than it is now. 

Let's see what `build --configure` should do on Windows:
* Run `boot` if needed (`configure` script does not exist or is not up-to-date).
* Detect whether we need to pass `--enable-tarballs-autodownload`. If we need it, add it to `configure` flags. How do we detect this? Shall we check _all files that had to be autodownloaded_? Or only one of them? Or shall we always add `--enable-tarballs-autodownload` after `boot`?
* Run `configure` with appropriate flags.

And then `--configure=ARGS` will become even more convoluted, because we will track some flags, but not others.

Right now the semantics is much simpler: `--configure` means roughly "Please also run configure script for me and boot if needed", and `--configure=ARGS` simply adds `ARGS` to the `configure` call. Much easier to explain, but perhaps less useful for users.

**Comment by snowleopard** [comment]
@ndmitchell Looks like the semantics you propose is something like "Please run configure and do the Right Thing" :-) It is certainly appealing from the user perspective, but only if it works as advertised!

**Comment by ndmitchell** [comment]
I would just always pass `--enable-tarballs-autodownload` if 1) we decide to run configure; 2) the user is on windows; and 3) there are no configure flags. Once you have that, the biggest pain point is gone.

It's a bit weird at the moment that there is a "first run" command that is different to "subsequent run" commands. I didn't figure that out...

**Comment by snowleopard** [comment]
This seems reasonably easy to explain. But are you sure passing `--enable-tarballs-autodownload` each time is harmless? Wouldn't it initiate unnecessary downloads?

As I understand, with this proposal `--configure` and `--configure=` would mean different things, which may be a surprise.

**Comment by ndmitchell** [comment]
Yes, passing enable-tarballs-autodownload each time is harmless - it checks if the directory exists before doing the download.

Yes, --configure and --configure= would be different. But --profile and --profile= are already different, so I don't see it as a great shock. Adding a trailing = to a flag is rare.

**Comment by snowleopard** [comment]
OK, agreed then. I'll try to implement this today.

**Comment by thomie** [comment]
Some previous discussion about the `--enable-tarballs-autodownload` flag.

@hvr asked in https://phabricator.haskell.org/D339#7796: 
> Is there any precedent for having ./configure download something from the Internet?
>
> (I've seen ./configure scripts telling you download something manually, and place it in a specific location, but never actually performing network I/O w/o the user's consent)

@thoughtpolice [replied](https://phabricator.haskell.org/D339#7933):
>  And yes, we definitely should never default to doing network I/O any time in the build system.
>
> Every time you do this, kittens cry and distro package maintainers (like myself) are sad (because we like to enable security features like no-network for building, and writing patches to change this is bad.)

@bgamari moved the download logic to a [script](https://phabricator.haskell.org/D1378), so you can also run `run mk/get-win32-tarballs.sh download ${HostArch}"`.

**Comment by ndmitchell** [comment]
I think distro maintainers want one thing, and poor little Windows users want another...

**Comment by snowleopard** [comment]
Oh, this is more complicated than I thought. Can I ask why the difference between Windows and non-Windows at all? We are building inside `mingw` and ask that `gcc` is installed, yet it looks like we are downloading them anyway into `inplace/mingw` folder. Why not use the `gcc` that is already installed?

**Comment by ndmitchell** [comment]
For Windows, GHC bundles gcc, so it makes sense for GHC to grab a known specific version of gcc, and use that when building. If not, you might get ABI incompatibilities. In addition, various versions of gcc on Windows have various bugs, so better to be consistent.

**Comment by snowleopard** [comment]
I don't understand, aren't different versions of `gcc` a problem on Linux? Why we bundle on Windows but not on Linux?

**Comment by ndmitchell** [comment]
You can assume a Linux machine has gcc installed. In general a Windows machine won't have gcc installed, so ghc bundles it.

**Comment by snowleopard** [comment]
But we are mixing different things here: building GHC and using pre-built GHC, right?

For people who build GHC, there are specific preparation requirements: https://ghc.haskell.org/trac/ghc/wiki/Building/Preparation/Windows. In particular,
```
Now we can install GHC's system dependencies as followed:

pacman -S git tar binutils autoconf make \
    libtool automake python2 p7zip patch \
    gcc mingw-w64-$(uname -m)-python3-sphinx
```
So, we **can** assume `gcc` is installed.

**Comment by ndmitchell** [comment]
The GHC package that gets shipped to end users needs to bundle gcc. Assuming we want that to be a specific known version (and we do), then ghc has to obtain its own specific gcc. Given its obtaining its own specific gcc to ship to users, it then makes sense to use that internally to avoid ABI issues and compatibility issues.

**Comment by snowleopard** [comment]
Then what is the point of doing `pacman gcc` in the preparation guide? Are you saying we are never actually using it?

**Comment by ndmitchell** [comment]
Hmm. Quite possibly... Note that ghc itself on Windows ships with gcc, so even if we did need another gcc we've got one as part of the ghc install, so it does seem quite redundant. Perhaps experiment on the appveyor machine?

**Comment by snowleopard** [comment]
Just for referenece, here is my `system.config` on Windows:
```
# Paths to builders:
#===================

alex           = /usr/local/bin/alex
ar             = /usr/bin/ar
gcc            = D:/msys/home/nam83/ghc/inplace/mingw/bin/gcc.exe
happy          = /usr/local/bin/happy
hs-cpp         = D:/msys/home/nam83/ghc/inplace/mingw/bin/gcc.exe
hscolour       = 
ld             = D:/msys/home/nam83/ghc/inplace/mingw/bin/ld.exe
make           = @MakeCmd@
nm             = D:/msys/home/nam83/ghc/inplace/mingw/bin/nm.exe
objdump        = D:/msys/home/nam83/ghc/inplace/mingw/bin/objdump.exe
ranlib         = D:/msys/home/nam83/ghc/inplace/mingw/bin/ranlib.exe
system-gcc     = D:/msys/mingw64/lib/../mingw/bin/gcc.exe
system-ghc     = /mingw64/bin/ghc
system-ghc-pkg = /mingw64/bin/ghc-pkg
tar            = /usr/bin/tar
patch          = /usr/bin/patch
perl           = D:/msys/home/nam83/ghc/inplace/perl/perl
```
Looks like the installed `gcc` is never called by the build system.

Yes, I'll try to remove `gcc` from AppVeyor.

**Comment by ndmitchell** [comment]
I see:

    system-gcc     = D:/msys/mingw64/lib/../mingw/bin/gcc.exe

Is that ever used? Or is that a link to the system-ghc one?

**Comment by snowleopard** [comment]
Ah... indeed! `system-gcc` is what is called `Gcc Stage0` in the build system. Yes, it is used during `Stage0`.

**Comment by ndmitchell** [comment]
So why do we use system-gcc rather than just gcc? And why aren't we picking up system-gcc from next to system-ghc on Windows? If the requirement is that the system-gcc and system-ghc must be compatible (which makes sense for stage0), then on Windows it should be the ghc one, not a separate system installed one.

**Comment by snowleopard** [comment]
Here is a relevant excerpt from `config.mk.in`:
```makefile
#-----------------------------------------------------------------------------
# C compiler
#
# NB. Don't override $(WhatGccIsCalled) using build.mk,  re-configure using
# the flag --with-gcc=<blah> instead.  The reason is that the configure script
# needs to know which gcc you're using in order to perform its tests.

WhatGccIsCalled       = @WhatGccIsCalled@
GccVersion            = @GccVersion@
ifeq "$(phase)" "0"
CrossCompilePrefix    =
else
CrossCompilePrefix    = @CrossCompilePrefix@
endif
# TargetPlatformFull retains the string passed to configure so we have it in
# the necessary format to pass to libffi's configure.
TargetPlatformFull    = @TargetPlatformFull@
GccLT34         = @GccLT34@
GccLT46         = @GccLT46@
GccIsClang      = @GccIsClang@

CC              = $(WhatGccIsCalled)
CC_STAGE0       = @CC_STAGE0@
CC_STAGE1       = $(CC)
CC_STAGE2       = $(CC)
CC_STAGE3       = $(CC)

AS              = $(WhatGccIsCalled)
AS_STAGE0       = @CC_STAGE0@
AS_STAGE1       = $(AS)
AS_STAGE2       = $(AS)
AS_STAGE3       = $(AS)

# We don't have an LD_STAGE0.  CC_STAGE0 is determined by asking "ghc
# --info", and it doesn't report an LD.
LD_STAGE0       = error-no-ld-stage0
LD_STAGE1       = $(LD)
LD_STAGE2       = $(LD)
LD_STAGE3       = $(LD)
```
`configure` turns this into the following on my machine:
```makefile
#-----------------------------------------------------------------------------
# C compiler
#
# NB. Don't override $(WhatGccIsCalled) using build.mk,  re-configure using
# the flag --with-gcc=<blah> instead.  The reason is that the configure script
# needs to know which gcc you're using in order to perform its tests.

WhatGccIsCalled       = D:/msys/home/nam83/ghc/inplace/mingw/bin/gcc.exe
GccVersion            = 5.2.0
ifeq "$(phase)" "0"
CrossCompilePrefix    =
else
CrossCompilePrefix    = 
endif
# TargetPlatformFull retains the string passed to configure so we have it in
# the necessary format to pass to libffi's configure.
TargetPlatformFull    = x86_64-unknown-mingw32
GccLT34         = NO
GccLT46         = NO
GccIsClang      = 

CC              = $(WhatGccIsCalled)
CC_STAGE0       = D:/msys/mingw64/lib/../mingw/bin/gcc.exe
CC_STAGE1       = $(CC)
CC_STAGE2       = $(CC)
CC_STAGE3       = $(CC)

AS              = $(WhatGccIsCalled)
AS_STAGE0       = D:/msys/mingw64/lib/../mingw/bin/gcc.exe
AS_STAGE1       = $(AS)
AS_STAGE2       = $(AS)
AS_STAGE3       = $(AS)

# We don't have an LD_STAGE0.  CC_STAGE0 is determined by asking "ghc
# --info", and it doesn't report an LD.
LD_STAGE0       = error-no-ld-stage0
LD_STAGE1       = $(LD)
LD_STAGE2       = $(LD)
LD_STAGE3       = $(LD)
```

**Comment by snowleopard** [comment]
And then we use `$1_$2_CC = $$(CC_STAGE$3)` in build rules, where `$3` is the current stage.

To sum up:
* In `Stage0` we use `@CC_STAGE0@` which evaluates to `D:/msys/mingw64/lib/../mingw/bin/gcc.exe` on my machine. This is what I call `system-gcc` in the new build system or, equivalently, `Gcc Stage0`.
* In all other stages we use `@WhatGccIsCalled@` instead, which evaluates to `D:/msys/home/nam83/ghc/inplace/mingw/bin/gcc.exe` on my machine, that is the one we download with `--enable-tarballs-autodownload`. These correspond to `gcc` and `Gcc StageN` in the new build system.

So, maybe I should just throw away all this `configure` stuff out of the build system (as we did with `make`), to have one less nasty thing to worry about? :-) But then poor Windows users (myself including) should keep using the standard incantation with `boot`, `configure` and `--enable-tarballs-autodownload`.

The alternative is to keep doing network I/O on Windows when run with `--configure` flag. If anyone finds this unacceptable then the solution is easy: don't use the `--configure` flag.

@ndmitchell @thomie Thoughts?

**Comment by ndmitchell** [comment]
If we can't have network IO by default (which I think is not a problem on Windows), then we're going to have to tell all Windows to do something, and make the instructions more complex. If so, one option would be to have two separate flags `--configure` to run configure, and `--configure-flag=--enable-tarballs-autodownload` so that if configure has to run (either because you didn't do it already or you passed `--configure`) then use these flags.

I think pushing boot/configure into the Haskell is a good plan, on the assumption that over time some of these will become at least slightly Haskell and more integrated with the build system.

**Comment by snowleopard** [comment]
What about a generic `--use-network` flag that, if given, would enable network IO and unlock some features, such as adding `--enable-tarballs-autodownload` to configure flags on Windows. (I can imagine other useful things one can do when network IO is allowed.)

The advantage of this is that it is immediately obvious from the command line that some network IO may happen, so it wouldn't come as a shock for maintainers.

**Comment by ndmitchell** [comment]
It still requires Windows users to pass something special, that is annoying in terms of docs, and (assuming its not there always) requires running the build differently the first time to all other times.

**Comment by snowleopard** [comment]
Agree, I'm still in favour of allowing network by default, because this simplifies docs. We can have a separate section specifically for maintainers explaining how to disallow it.

I don't understand your second comment: you still need to run the build differently for the first time, because that's the only time you need to run `configure`.

**Comment by ndmitchell** [comment]
Oh - won't it automatically run configure if that hasn't ever been done? I assumed it would, but I guess not. That would be nice...

**Comment by snowleopard** [comment]
The problem is that we don't know which flags the user would like to use when running `configure`. We can run configure without any flags by default (perhaps, just adding `--enable-tarballs-autodownload` on Windows), but what if this screws up things? There are a lot of flags out there...

**Comment by ndmitchell** [comment]
> Sounds like potential source of hard to understand errors.

Sounds like configure all over :wink:

I don't have any great ideas though. Leaving configure separately might be better in the end... Until we're ready to properly smash it up into new pieces.

**Comment by snowleopard** [comment]
What about doing the following: 
* On the front page we tell everyone to use the new `build` script instead of `make`. That's it. They still have to worry about exactly the same things as before (`boot`, `configure`, etc.).
* We add a section covering certain new and experimental features of the new build system, where we describe how one can use `--configure` to simplify things up a little. Particularly useful for poor Windows users. With a note for those sad maintainers that it uses network IO.

**Comment by ndmitchell** [comment]
:+1:

**Comment by snowleopard** [comment]
OK, done. Hopefully there is less confusion now.

**Comment by snowleopard** [comment]
Interestingly, I had to use `System.Info.os == "mingw32"` instead of `windowsHost` to detect the platform, because otherwise we fall into a cyclic dependency. This made me wonder: to what extent we can rely on `System.Info` in the new build system?

**Comment by ndmitchell** [comment]
Note https://hackage.haskell.org/package/extra-1.4.3/docs/System-Info-Extra.html#v:isWindows, which is a version of that test which is semantically clearer and avoids the possibility of typos and is evaluated at compile time.

**Comment by hvr** [comment]
Fwiw, even  in those few occasions I'm on windows, I certainly wouldn't want something `--configure` to automatically download stuff...  that's simply against all conventions :-/

**Comment by snowleopard** [comment]
> Fwiw, even in those few occasions I'm on windows, I certainly wouldn't want something called `--configure` to automatically download stuff... that's simply against all conventions and expectations :-(

@hvr I think many issues are mixed in your comment, let me try to better understand it:
* Do you think you will be using the `--configure` feature yourself to streamline the first build on non-Windows platforms? If yes, don't you think it is useful to have an equivalent for Windows users too?
* Are you against _any_ network IO in the build system, regardless of how well documented, flag-guarded and useful it is?
* Or are you specifically against the name of the flag? In this case, do you have any suggestions?

> Morever, it's so pointless to `--enable-tarballs-autodownload` by default on windows only, as that's the only case it would have had any effect at all!

I'm lost. Are you suggesting that we should pass `--enable-tarballs-autodownload` on _all platforms_? But this is not what the current GHC build guides say: they only advise to use it on Windows. I'm simply following them.

> Not only maintainers dislike when tools trigger unexpected network downloads.

I fully agree. I don't want it to be unexpected, that's why this behaviour is documented. Maybe not well enough, but I am open to suggestions.

**Comment by hvr** [comment]
> Or are you specifically against the name of the flag? In this case, do you have any suggestions?

...mostly this :-)

It's a pet peeve of mine, that something like `--configure` is never supposed to download stuff, but rather *configure* stuff that's already . Terms with (maybe) less connotations:

 -  `--setup`
 -  `--bootstrap`
 -  `--initialize`

Also, `--configure` as you use it seems to do more than merely "configure" anyway, it also bootstraps the `configure` script via `autoreconf`. This on its own already represents a bit of a misnomer of the `configure`-term.

> I'm lost. Are you suggesting that we should pass --enable-tarballs-autodownload on all platforms? But this is not what the current GHC build guides say: they only advise to use it on Windows. I'm simply following them.

Well, the thing is that `--enable-tarballs-autodownload` is a hack done specifically for windows users' convenience - nobody else  benefits from autodownloading the win32 tarballs!
Originally it would have been enabled by default, but that was opposed (by me). And instead  users who want this need to explicitly opt-in via that flag. And since this auto-download hack is only for the benefit of windows, it's kinda ironic that the new build-systems thwarts this by enabling it by default... ;-)

At this point I wonder if we should just remove the `--enable-tarballs-autodownload`  feature from `configure.ac` again, since all it does is call the `mk/get-win32-tarballs.sh` script anyway, and if shake is going to download tarballs for users anyway (via some flag called differently from `--configure`), it can call `mk/get-win32-tarballs.sh` directly...

**Comment by snowleopard** [comment]
> `--setup`

Thanks, I like this one! It makes it fairly obvious that the flag is supposed to be used only once. This is not so with `--configure`. Also, as you rightly point out we are doing more than just calling `configure`.

> if shake is going to download tarballs for users anyway (via some flag called differently from `--configure`), it can call `mk/get-win32-tarballs.sh` directly...

Yes, that sounds like the right thing to do. 

So, I'm reopening the issue and doing the following:
- [ ] Rename the `--configure` flag to `--setup`, making sure error messages are consistent.
- [ ] Drop `--enable-tarballs-autodownload` and instead run `mk/get-win32-tarballs.sh` on Windows.
- [ ] Update the `README`.

I'll wait for a day for more comments.

**Comment by snowleopard** [comment]
Just to give an update: on the recent Hadrian meeting it was decided that `configure` should lose the status of a special command line tool and should become just another `Builder`, see: https://github.com/snowleopard/hadrian/commit/72f6ec653e2f8801fc275ffa5d294a85e6e34ee8. The same will happen with `make` and some other tools we are still calling in an ad-hoc manner.

This means that the user of the build system can now override `configure` flags in `Settings/User.hs`.

**Comment by hvr** [comment]
note sure what this means. But I guess I'm fine as long as can keep calling `./configure` directly, and shake not messing around with the flags I made sticky by passing them to `configure`...

**Comment by snowleopard** [comment]
This means that users get an additional method of customising `configure` arguments, e.g.:
```haskell
userArgs :: Args
userArgs = builder (Configure ".") ? arg "--with-ghc=/usr/bin/ghc-7.10.2"
```
Also, we will optimise Hadrian's command line arguments for the most common use-case, which means the `--setup` flag will be dropped and both `boot` and `configure` will run by default if need be, as this is what most users want. There is no reason to force everyone to remember calling Hadrian with `--setup`. But don't worry we will provide a way to suppress automated invocation of `boot` and `configure` if required. Any ideas on how to call such suppression flag? Something like `--no-configure` or `--skip-configure`?

**Comment by snowleopard** [comment]
By the way, there are three `Configure` builders currently:
* The top-level one: `Configure "."`.
* The one we use for `libffi` library: `Configure libffiBuildPath`.
* The one we use for GMP library: `Configure $ gmpBuildPath -/- "lib"`.

In general, it is `Configure FilePath` where `FilePath` is the directory where we run the script. This doesn't look very nice, so any suggestions on how to improve this are welcome. Perhaps, we should use a datatype instead: `data ConfigureScript = TopLevel | Libffi | Gmp`, leading to `Configure TopLevel`, etc.

**Comment by hvr** [comment]
@snowleopard `--skip-...` sounds reasonable, if shake has already such a precedent
