### ISSUE TITLE
Transient failure with package cache

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#205]
Error when running Shake build system:
    * .build/stage1/libraries/ghc-boot/build/libHSghc-boot-8.1.a
    * .build/stage1/libraries/ghc-boot/build/GHC/LanguageExtensions.o
    * OracleQ (DependenciesKey (".build/stage1/libraries/ghc-boot/build/.dependencies",".build/stage1/libraries/ghc-boot/build/GHC/LanguageExtensions.o"))
    * .build/stage1/libraries/ghc-boot/build/.dependencies
    * .build/stage1/libraries/ghc-boot/build/.hs-dependencies
    user error (Development.Shake.cmd, system command failed
    Command: inplace/bin/ghc-stage1.exe -M -hisuf hi -osuf o -hcsuf hc -static -hide-all-packages -no-user-package-db "-this-package-key ghc-boot-8.1" "-package-id base-4.9.0.0" "-package-id binary-0.8.0.0" "-package-id bytestring-0.10.7.0" "-package-id directory-1.2.5.0" "-package-id filepath-1.4.1.0" -i -i.build/stage1/libraries/ghc-boot/build -i.build/stage1/libraries/ghc-boot/build/autogen -ilibraries/ghc-boot -I.build/stage1/libraries/ghc-boot/build -I.build/stage1/libraries/ghc-boot/build/autogen -IC:\Neil\ghc\conf3\ghc\libraries\directory\include -IC:\Neil\ghc\conf3\ghc\libraries\time\lib/include -IC:\Neil\ghc\conf3\ghc\libraries\containers\include -IC:\Neil\ghc\conf3\ghc\libraries\Win32\include -IC:\Neil\ghc\conf3\ghc\libraries\bytestring\include -IC:\Neil\ghc\conf3\ghc\libraries\base\include -IC:\Neil\ghc\conf3\ghc\libraries\integer-gmp\include -IC:/Neil/ghc/conf3/ghc/.build/stage1/rts/build -IC:/Neil/ghc/conf3/ghc/includes -IC:/Neil/ghc/conf3/ghc/includes/dist-derivedconstants/header -optP-include -optP.build/stage1/libraries/ghc-boot/build/autogen/cabal_macros.h -XHaskell2010 -odir .build/stage1/libraries/ghc-boot/build -hidir .build/stage1/libraries/ghc-boot/build -stubdir .build/stage1/libraries/ghc-boot/build -rtsopts -include-pkg-deps -dep-makefile .build/stage1/libraries/ghc-boot/build/.hs-dependencies -dep-suffix "" libraries/ghc-boot/GHC/LanguageExtensions.hs libraries/ghc-boot/GHC/Lexeme.hs libraries/ghc-boot/GHC/PackageDb.hs libraries/ghc-boot/GHC/Serialized.hs
    Exit code: 1
    Stderr:
    on the commandline: warning:
        -this-package-key ghc-boot-8.1 is deprecated: Use -this-unit-id instead
    C:\Neil\ghc\conf3\ghc\inplace\lib\package.conf.d\package.cache: openBinaryFile: permission denied (Permission denied)
    )

Another transient failure.

**Comment by snowleopard** [comment]
Looks like two parallel `ghc-pkg` invocations happened? Noone else should be touching `package.cache`.

**Comment by ndmitchell** [comment]
This looks like the thing that failed was reading the ghc package cache. Do normal ghc executions read from the package cache? Is that meant to be safe multithreaded? Is there a multiple-reader single-writer pattern required?

**Comment by thomie** [comment]
See https://ghc.haskell.org/trac/ghc/ticket/8591 (Concurrent executions of ghc-pkg can cause inconstant package.cache files)

**Comment by ndmitchell** [comment]
@thomie - couldn't GHC just use a file lock? https://github.com/ndmitchell/shake/blob/master/src/General/FileLock.hs has been super robust in Shake across multiple platforms for preventing these kind of single-file race conditions.

**Comment by ndmitchell** [comment]
For info, I've been rerunning the build system most of the afternoon every now and then (perhaps 10-20 complete rebuilds?) and just bumped into another instance:

    Error when running Shake build system:
    * .build/stage1/libraries/base/build/libHSbase-4.9.0.0.a
    * .build/stage1/libraries/base/build/Foreign/Marshal/Utils.o
    user error (Development.Shake.cmd, system command failed
    Command: inplace/bin/ghc-stage1.exe -hisuf hi -osuf o -hcsuf hc -static -hide-all-packages -no-user-package-db "-this-package-key base-4.9.0.0" "-package-id ghc-prim-0.5.0.0" "-package-id integer-gmp-1.0.0.1" "-package-id rts" -i -i.build/stage1/libraries/base/build -i.build/stage1/libraries/base/build/autogen -ilibraries/base -I.build/stage1/libraries/base/build -I.build/stage1/libraries/base/build/autogen -Ilibraries/base/include -IC:\Neil\ghc\conf3\ghc\libraries\integer-gmp\include -IC:/Neil/ghc/conf3/ghc/.build/stage1/rts/build -IC:/Neil/ghc/conf3/ghc/includes -IC:/Neil/ghc/conf3/ghc/includes/dist-derivedconstants/header -optP-include -optP.build/stage1/libraries/base/build/autogen/cabal_macros.h -this-unit-id base -XHaskell2010 -optP-DOPTIMISE_INTEGER_GCD_LCM -odir .build/stage1/libraries/base/build -hidir .build/stage1/libraries/base/build -stubdir .build/stage1/libraries/base/build -rtsopts -H32m -O2 -c libraries/base/Foreign/Marshal/Utils.hs -o .build/stage1/libraries/base/build/Foreign/Marshal/Utils.o
    Exit code: 1
    Stderr:
    on the commandline: warning:
        -this-package-key base-4.9.0.0 is deprecated: Use -this-unit-id instead
    C:\Neil\ghc\conf3\ghc\inplace\lib\package.conf.d\package.cache: openBinaryFile: permission denied (Permission denied)

So maybe 5% of builds are going to fail this way?

**Comment by snowleopard** [comment]
@ndmitchell 5% may be the right figure. I also come across this occasionally.

**Comment by snowleopard** [comment]
Let me summarise my understanding of what happens:
* `ghc-pkg` writes to `package.cache`. We do not allow more than one `ghc-pkg` to run concurrently.
* `ghc` reads from `package.cache`. Multiple parallel instances of `ghc` presumably do not cause any issues, as otherwise I'd expect to see more frequent failures.
* So what happens is that we occasionally have a collision between `ghc-pkg` and `ghc`.

@ndmitchell What would be the right way to reduce concurrency in this case using Shake? If I am not mistaken this is the classic concurrent read exclusive write (CREW) conflict.

**Comment by ndmitchell** [comment]
@snowleopard Create a resource of quantity 1000. Require writers to take 1000 elements of the resource, and readers to take 1 element. That effectively gives you single-writer multiple-reader.

**Comment by snowleopard** [comment]
@ndmitchell Nice and simple, should work! I'll implement this. (Although the magic number bothers me slightly...)

How does it work in terms of scheduling/fairness? Can it happen that writers never have a chance to get through because there is always at least one reader using the resource? In our case there are a dozen of writers, but thousands of readers.

Of course at some point writers will go through, because readers depend on them, but it's not obvious to me what happens in general.

**Comment by snowleopard** [comment]
Done. I've tested the result several times on my machine and couldn't trigger this failure any more. If it reappears, please reopen the issue.

**Comment by ndmitchell** [comment]
The magic number is just higher than we expect someone to have threads - a little inelegant, but perfectly models what we are after. The scheduler guarantees that the first task to request a resource will run next, so when ghc-pkg tries to run, it will stop any ghc processes starting - no starvation problems.

**Comment by snowleopard** [comment]
:+1:
