### ISSUE TITLE
Refactor Target

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#207]
We currently have the following `Target` datatype:
```haskell
-- | Parameters relevant to the current build target.
data Target = Target
    { stage   :: Stage      -- ^ Stage being built
    , package :: Package    -- ^ Package being built
    , builder :: Builder    -- ^ Builder to be invoked
    , way     :: Way        -- ^ Way to build (set to vanilla for most targets)
    , inputs  :: [FilePath] -- ^ Source files passed to the builder
    , outputs :: [FilePath] -- ^ Files to be produced
    } deriving (Show, Eq, Generic)
```
It makes sense to factor out `Stage`, `Package` and `Way` into a separate datatype called `Context`:
* At the moment we mix different notions in one datatype: _target-specific_ ones (`builder`, `inputs`, `outputs`) and _context-specific ones_ (what is the current `stage`, `package` and `way`?).
* By factoring out GHC-specific bits into `Context` we make it easier to reuse our build abstractions in other build systems. Arguably, `builder`, `inputs` and `outputs` are common for all non-trivial build systems, however, not all build systems need `way`, `package` or, especially, `stage`.
* We already have a datatype called `PartialTarget` in the build system:

    ```haskell
    -- | A partially constructed Target with fields 'Stage' and 'Package' only.
    -- 'PartialTarget's are used for generating build rules.
    data PartialTarget = PartialTarget Stage Package deriving (Eq, Show)
    ```
This is almost exactly what we want to have as a `Context`.

/cc @simonpj @simonmar @ndmitchell

**Comment by ndmitchell** [comment]
Seems reasonable to me. Will we be able to kill `PartialTarget` afterwards?

**Comment by snowleopard** [comment]
@ndmitchell Yes, I think so. It will be consumed by `Context`.
