### ISSUE TITLE
Use --profile=- on the buildbots

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#209]
That should give a very rough profile breakdown on stdout (10 lines or so), which is gently curious to have, and can't hurt.

**Comment by ndmitchell** [comment]
Either add it onto the main build, or add it after with a new command line containing `--no-build`.

**Comment by snowleopard** [comment]
Nice, I didn't know one can do that. Let's add it onto the main build -- shall I assign this to you?

**Comment by ndmitchell** [comment]
Up to you - before #208 I'd have sent a speculative patch. But it seems someone needs to give our Travis a kick. If adding it is easy at that point, just go for it.

**Comment by snowleopard** [comment]
Yes, I'll be looking into the Travis issue today. Will also add `--profile=-` while I'm at it.
