### ISSUE TITLE
Bad hsc2hs call

### ISSUE THREAD

**Issue by quchen** [snowleopard/shaking-up-ghc#21]
I've been trying to build GHC HEAD with ghc-shake, but I keep running into this error:

```
No template specified, and template-hsc.h not located.
```

It seems HSC is called with bad parameter; [I've pasted the full error on lpaste.](http://lpaste.net/147628)

**Comment by snowleopard** [comment]
I can't reproduce on my machine, but I'm lagging behind GHC HEAD.

Template `template-hsc.h` is not a generated file and is included into `hsc2hs` package: see https://git.haskell.org/hsc2hs.git/tree for example.

**Comment by quchen** [comment]
I can fix the error by adding

```haskell
, arg $ "--template=" ++ "/home/david/Coding/haskell/ghc/utils/hsc2hs/template-hsc.h"
```

to hsc2hs' `Args`, so it seems the file isn't found in my environment. I then run into another error that may or may not be related:

```haskell
* inplace/bin/ghc-pkg
-- snip
/usr/bin/ld: cannot find -lHSterminfo-0.4.0.2
/usr/bin/ld: cannot find -lHSghc-boot-0.0.0.0
/usr/bin/ld: cannot find -lHSCabal-1.23.0.0
/usr/bin/ld: cannot find -lHSbinary-0.8.0.0
collect2: error: ld returned 1 exit status
```

I'll keep looking for a solution.

**Comment by snowleopard** [comment]
Not sure what's going on. Could it be related to the changes you made in your branch, particularly in `build.sh`? Maybe worth trying `snowleopard:master`.

**Comment by quchen** [comment]
I'm now able to reproduce the error mentioned in my last comment across multiple machines (all Linux, Xubuntu >= 14.04). Strange!
