### ISSUE TITLE
bootstrapping with GHC 8.0.1RC

### ISSUE THREAD

**Issue by hvr** [snowleopard/shaking-up-ghc#215]
The first issue one stumbles over is easy to fix (this actually assumes a more recent snapshot than GHC 8.0RC2):

```diff
diff --git a/shaking-up-ghc.cabal b/shaking-up-ghc.cabal
index fc0744d..3bd6ede 100644
--- a/shaking-up-ghc.cabal
+++ b/shaking-up-ghc.cabal
@@ -118,7 +118,7 @@ executable ghc-shake
                        , ScopedTypeVariables
     build-depends:       base >= 4.8 && < 5
                        , ansi-terminal        == 0.6.*
-                       , Cabal                == 1.22.*
+                       , Cabal                == 1.22.* || == 1.24.*
                        , containers           == 0.5.*
                        , directory            == 1.2.*
                        , extra                == 1.4.*
```

----

The next issue is that shake hasn't picked up ghc/ghc@525a304f8c010ce73f1456e507aca668eb4917ac yet; so `Settings.Packages.GhcCabal` needs updating. As a quick workaround I added something along the lines of

```haskell
arg "-hide-all-packages" : [ arg ("-package " ++ p) | p <- words "base array time containers bytestring deepseq process pretty directory unix" ]
```

(btw, once we reach GHC 8.3.x development, we won't need that ugly `cabal_macros_boot.h` hack anymore...)

----

I see a lot of

```
on the commandline: warning:
    -this-package-key ghc-boot-8.1 is deprecated: Use -this-unit-id instead
```

lines

**Comment by snowleopard** [comment]
@hvr Thanks! This has been in my wish list for a while. It's good to have it documented here.

I assume these changes are backward compatible, that is, booting with GHC 7.10 will still work?

**Comment by hvr** [comment]
@snowleopard yes.. booting with 7.10 *should* still work

maybe @ezyang can chime in regarding the `-this-package-key` warning (if this still happens)

**Comment by ezyang** [comment]
Yes, for GHC 8.0 and later please use `-this-unit-id` not `-this-package-key`. I apologize profusely for all of the faffing about >_<

**Comment by snowleopard** [comment]
Thanks @hvr and @ezyang. I'll be taking care of this during the coming week. Haven't had time recently to keep up with the project, but things are getting back to normal now.

**Comment by hvr** [comment]
Btw, the last item (`-this-unit-id`) is not only relevant for bootstrapping with 8.0, but in general when building stage2, as the stage1-ghc wants the `-this-unit-id` flag as well.

**Comment by snowleopard** [comment]
I think I've done all the changes, see the above commit.

Could you clarify where this list of packages comes from? I thought I would be able to compute it instead of hard-coding, but I can't quite figure out how.
```makefile
ifeq "$(Windows_Host)" "YES"
CABAL_BUILD_DEPS := base array time containers bytestring deepseq process pretty directory Win32
else
CABAL_BUILD_DEPS := base array time containers bytestring deepseq process pretty directory unix
endif
```

**Comment by hvr** [comment]
@snowleopard that package list has been manually invented by finding out which dependencies are needed by `ghc-cabal` (which includes its transitive deps, such as `binary`). It's basically a subset of bundled GHC's boot packages. But we can't parse `.cabal` files yet, because `ghc-cabal` isn't built yet and we can't assume `cabal` to exist to help us out (in which case we'd be able to properly solve an exact install-plan which would be way better), so this is why we use this crude heuristic here...

**Comment by snowleopard** [comment]
@hvr Strange that the list doesn't match `.build_stage1_utils_ghc-cabal_TRANSITIVE_DEP_NAMES`:
```
Cabal process pretty directory time filepath binary containers Win32 bytestring deepseq array base integer-gmp ghc-prim rts
```
We actually do parse `.cabal` files in the build system, see module `Rules.Cabal`. So, we could probably extract the list from `ghc-cabal.cabal`. However, since we are planning to get rid of `ghc-cabal` anyway at some point, maybe it doesn't worth the effort. I'll leave this as is, with a note.

**Comment by hvr** [comment]
On 2016-04-18 at 11:11:21 +0200, Andrey Mokhov wrote:
> @hvr Strange that the list doesn't match `.build_stage1_utils_ghc-cabal_TRANSITIVE_DEP_NAMES`:

I wasn't fully accurate here; we don't need *all* transitive deps, only
those that the `.hs` files compiled to generate ghc-cabal needs to
import packages from directly... so we only need a subset of that
TRANSITIVE_DEP_NAMES variable... 

> We actually do parse `.cabal` files in the build system, see module
> `Rules.Cabal`. So, we could probably extract the list from
> `ghc-cabal.cabal`.

that probably wouldn't be enough though, since ghc-cabal.cabal doesn't
list all packages we need to pass to `-package` for the cabal-less
building of ghc-cabal. It's important to understand that we're in a
bootstrapping state here where we can't rely on .cabal files *yet*.

> However, since we are planning to get rid of
> `ghc-cabal` anyway at some point, maybe it doesn't worth the
> effort. I'll leave this as is, with a note.

If ghc-cabal is going to be sucked up into shake then I'd agree that
it's not worth the effort for now.

OTOH, this just shifts the problem we had with ghc-cabal to shakebuild,
i.e. not being able to rely on any .cabal files for generating
shakebuild, nor on having `cabal-install` at our disposal. We can only
assume a minimal pre-installed GHC bindist (for building a GHC
source-distribution).

**Comment by snowleopard** [comment]
> OTOH, this just shifts the problem we had with ghc-cabal to shakebuild,
i.e. not being able to rely on any .cabal files for generating
shakebuild

Could you clarify? We already parse `.cabal` files from Shake for extracting package dependencies, so we can build them in the right order, and this seems to work well. Am I missing a potential pitfall here?

**Comment by snowleopard** [comment]
> EDIT: Github seems to epically fail at rendering inline quoted email replies *sigh*

Indeed, that's very frustrating.

**Comment by hvr** [comment]
> Am I missing a potential pitfall here?

you're assuming that shakebuild was already built :-)

**Comment by snowleopard** [comment]
Hmm, I do, but why wouldn't it be built? :-) We build it with the bootstrapping GHC via plain `ghc --make`. 

Are you saying that the bootstrapping Cabal library will not be able to parse `.cabal` files in the GHC source tree? That may indeed be the pitfall I'm missing, but that would lead to a runtime failure after Shake has been already built.

**Comment by hvr** [comment]
You may want to notice that ghc-cabal only access the global package database, and in order to be able to use `ghc --make` we just make a monolithic source-tree via `-i`:

```
               -ilibraries/Cabal/Cabal \
               -ilibraries/binary/src -DGENERICS \
               -ilibraries/filepath \
               -ilibraries/hpc 
```

so we basically avoid the complexity of cabal package registration altogether, and build everything via a monolithic `ghc --make` invocation. Also, the GHC buildsystem is not allowed to install into or use things from the per-user package db.

**Comment by snowleopard** [comment]
Sorry, I'm still lost :-)

We are using the Shake library installed on the system. Surely, we can also use the Cabal library?

Or are you saying Shake also needs to use the `-ilibraries/Cabal/Cabal` trick?

**Comment by hvr** [comment]
> We are using the Shake library installed on the system.

that's actually a detail that needs to be formalised; this is a departure from the previous pre-reqs which didn't require any libs not already bundled with the bootstrapping GHC!

**Comment by ndmitchell** [comment]
My personal opinion is that using the Shake library installed by the system is the right approach, and building the tool that builds GHC should be handled by Cabal or Stack. We have infrastructure for describing how to compile Haskell tools that respect versions ranges, no need to reinvent the wheel. I don't see any advantage from making GHC bundle Shake or pull in its own copy.

I think that concern is separate from whether the Shake-based GHC build tool uses the existing Cabal library or the one in-tree. On that I have no real opinion.

**Comment by snowleopard** [comment]
> that's actually a detail that needs to be formalised; this is a departure from the previous pre-reqs which didn't require any libs not already bundled with the bootstrapping GHC!

Ah, so that's the source of confusion! This is actually 'formalised' in the `README`:

```markdown
This build system is written in Haskell (obviously) and depends on the following Haskell
packages, which need to be installed: `ansi-terminal`, `mtl`, `shake`, `QuickCheck`.
```

> whether the Shake-based GHC build tool uses the existing Cabal library or the one in-tree. On that I have no real opinion.

Same with me. Using the existing Cabal library seems to be a simpler approach, but may be limiting.

**Comment by bgamari** [comment]
> > whether the Shake-based GHC build tool uses the existing Cabal library or the one in-tree. On that I have no real opinion.
> Same with me. Using the existing Cabal library seems to be a simpler approach, but may be limiting.

@ezyang, as one of the principle contributors to Cabal you might have an opinion here.

**Comment by hvr** [comment]
>> whether the Shake-based GHC build tool uses the existing Cabal
>library or the one in-tree. On that I have no real opinion.
>
>Same with me. Using the existing Cabal library seems to be a simpler
>approach, but may be limiting

this is a bad idea as ghcs sourcetree may contain cabal files needing a bleeding edge cabal parser

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ndmitchell** [comment]
@hvr, makes sense, I guess that means ghc-shake should be required to use the in-tree Cabal.

**Comment by ezyang** [comment]
Yes, the point of compiling Cabal first is we don't want to assume the user's Cabal is sufficiently recent.

**Comment by Ericson2314** [comment]
We already depend on the previous GHC to be sufficiently recent, so what's the problem with depending the same for Cabal? Cabal files have a min version field, right? I think there is a dangerous assumption that bundling things somehow makes life easier, when the fact of the matter is the added complexity / deviation from the way most Haskell is built crates more problems than it solves.

I think there's a big difference between build-time deps, and runtime-deps, and base libraries for the to-be-installed GHC. The base libraries are closely tied to the GHC they are intended to be built with, and should definitely be bundled, runtime deps are a middle ground, but build-time deps really should be more tailored for the building compile system and the being-built compile, so I don't think its very important to include them.

**Comment by ezyang** [comment]
@Ericson2314 In general, GHC must be bootstrappable by the previous three versions. So there's a much larger window.

As an example, Cabal recently changed where the `cabal_macros.h` file gets generated for executables. This change only shows up in 1.25+. The previous three versions of GHC ship with 1.24, 1.22, etc. So if GHC's build system must be bootstrappable against each version of Cabal that these versions of GHC shipped with, we'd need to add a conditional here. Or we can bundle the specific version of Cabal we need and no conditionals are necessary. (BTW, did Cabal really need to change the location of the macros? The new place where the macros is, arguably, the most logically appropriate way to do it; to preserve the old system would require extra BC gunk. Tradeoffs!)

I mean, it may not be that much of a burden to track three versions of Cabal, and maybe even less so now that the build system is written in Haskell. But that's the tradeoff.

**Comment by Ericson2314** [comment]
There is no issue with installing a Cabal / cabal-install newer than the one that comes with the booting ghc, right?

**Comment by ezyang** [comment]
No, that's fine. But sometimes GHC needs to track changes in an unreleased version of Cabal.

**Comment by snowleopard** [comment]
The fact that the build system should be able to handle unreleased versions of the Cabal library means we have to use the in-tree Cabal. I'll create a separate issue to track this.

**Comment by Ericson2314** [comment]
Well, if and when that occurs, sure. A cabal config / stack.yaml / whatever can force the shake build system to be built with the bundled library. But I'd do my best not to keep that hanging around --- e.g. revert it as soon as a version of Cabal supporting the requisite features is released.

**Comment by snowleopard** [comment]
@Ericson2314 We could probably make this into a setting... Not yet sure how, but maybe useful.

**Comment by ezyang** [comment]
@Ericson2314 Well, that's not how the GHC/Cabal release process works at the moment. For most of the year, Cabal does not do any releases, and GHC occasionally updates its in-tree copy to a newer internal version so that we can shake out any incompatibilities in ghc-pkg and ghc-cabal. When release time comes around, Cabal finally starts cutting releases. (Actually, in the GHC 8.0 cycle, Cabal STILL hasn't cut a 1.24 release. I think @hvr has finally convinced the Cabal RMs that this is a mistake so we'll probably cut 1.24 releases when the RCs roll around.) So most of the time you'll need the bundled library.

**Comment by Ericson2314** [comment]
> For most of the year, Cabal does not do any releases, and GHC occasionally updates its in-tree copy to a newer internal version so that we can shake out any incompatibilities in ghc-pkg and ghc-cabal.

I get that one needs to keep those things in sync, but that should only apply to the Cabal being used with the in-development version of GHC, not the Cabal being used to build that GHC, right?

**Comment by ezyang** [comment]
> I get that one needs to keep those things in sync, but that should only apply to the Cabal being used with the in-development version of GHC, not the Cabal being used to build that GHC, right?

Remember that GHC is staged. So the order goes something like this:

1. With the bootstrapping compiler and the bundled GHC, build `ghc-cabal`
2. Use `ghc-cabal` to preemptively register all of the boot libraries that GHC is going to be built with (by the bootstrapping compiler)
3. Build the stage 1 compiler

So, I guess (and this is just a guess, because I don't know too much about this part of the build system) if the boot libraries can be built with any version of Cabal, and ghc-cabal can be made to support all bootstrapping versions of Cabal, then you could get rid of the initial build.

**Comment by hvr** [comment]
@ezyang it gets more complicated though with shake being linked against `Cabal`. Then we'd be limited to use  only features that are not available to shakebuilds' `Cabal`-version (unless we do staged builds of shakebuild itself...). This would be a heavy limitation compared to our current system where we can use the latest yet unreleased features of Cabal within GHC's source-tree.

**Comment by Ericson2314** [comment]
You're right, When that happens, staged builds of this or depending on the bundled Cabal is in order. But last I checked, absorbing ghc-cabal was put on hold, and I see no reason for either of those things until then.

**Comment by ezyang** [comment]
Right, so all I know is how  GHC's build system is currently set up, I don't have very much knowledge about Shake. If indeed Shake does not do `ghc-cabal` (I wonder; how do you do cross package parallelism?) then maybe something else should be done.

**Comment by Ericson2314** [comment]
https://github.com/snowleopard/shaking-up-ghc/issues/18 is the relevant issue.

IMO linking Cabal directly and avoiding GHC cabal would be really slick to do in conjunction with getting Cabal to also use Shake. Then Cabal can naturally expose a monadic rule-creating-rule.

**Comment by ndmitchell** [comment]
@Ericson2314 - while Cabal using Shake might be nice, I think if we tie all the pieces to that at once nothing might ever move forward.

@ezyang - currently the biggest issue is that `ghc-cabal` changes directory. That works if you are the only thing in the process, but if you want to run multithreaded that's a disaster. Cross-package parallelism is nothing difficult, because `ghc-cabal` installs just a single package, not the child packages, and Shake knows the package dependencies between them.

@snowleopard Referring to the Shake-based GHC-build-system as "Shake" is probably confusing things, leading to @ezyang who has a lot of knowledge about "Shake" to utter phrases such as "I don't have very much knowledge about Shake". Perhaps we need some concise way of referring to this particular build system?

**Comment by ezyang** [comment]
@ndmitchell Yes, I've run into this problem and it's quite irritating. In fact, cabal-install goes out of its way to invoke Cabal the library out of process so that it can change directory. To make matters worse, refactoring Cabal to fix this problem would probably break most Custom scripts which assume that the current directory is the package directory. But maybe it can be done...

**Comment by Ericson2314** [comment]
@ndmitchell Well if #18 doesn't block this replacing the make system, that isn't so bad.

@ezyang isn't `setup-depends` supposed to offer an method for making breaking changes to Cabal?

**Comment by snowleopard** [comment]
> @snowleopard Referring to the Shake-based GHC-build-system as "Shake" is probably confusing things, leading to @ezyang who has a lot of knowledge about "Shake" to utter phrases such as "I don't have very much knowledge about Shake". Perhaps we need some concise way of referring to this particular build system?

@ndmitchell Yes, indeed. Both `new build system` and `Shake(-based) build system` are unsatisfactory. Let's come up with a short name before merging into the GHC tree... something to discuss during the upcoming meeting in Cambridge? Perhaps with the aid of a pint? :-)
