### ISSUE TITLE
Figure out the GHC equivalent command line

### ISSUE THREAD

**Issue by ndmitchell** [snowleopard/shaking-up-ghc#218]
This build system doesn't do everything. To benchmark, it is useful to have an equivalent in the old GHC build system. Running:

    shake-build/build  --flavour=quick -j4

Is equivalent to:

* In `mk/build.mk` set `BuildFlavour = quick`
* Run `make -j4`

And what else? What other things does GHC build that we don't?

**Comment by snowleopard** [comment]
By default we don't build documentation (it sometimes breaks and also takes a lot of time, so I decided not to enable it by default for now). To enable it we can pass `--haddock` flag.

By default we also don't build split objects (for the same reason: fragile and slow), to enable you can pass `--split-objects` flag.

We currently only build vanilla way (plus `threaded` RTS for `haddock`), so we should disable all other ways in `make`. Not entirely sure what's the right way to do that.

I think that's it. Other limitations are listed here, but I don't think they are relevant: https://github.com/snowleopard/shaking-up-ghc#current-limitations.

**Comment by snowleopard** [comment]
Let me check whether `profiling` works. It actually should, unless I broke it recently.

**Comment by ndmitchell** [comment]
Looking at my directory after a complete build there are only 175 HTML files, and most are tests from the Haddock repo, so it seems GHC doesn't build documentation by default either. I think everything else is captured with:

```
BuildFlavour = quick
SplitObjs = NO
GhcLibWays = v
```

**Comment by ndmitchell** [comment]
For info, on the "nothing to do" build, we are 3.7s and Make is 12.3s. That's terrible from both!

**Comment by ndmitchell** [comment]
Having a little less in the pile for doing my testing is nicer - means I can run more tests and get more robust measurements, especially if the extra stuff is just "more of the same".

For the slowness of the current system, I'll profile and see what I can do - leave it to me.

**Comment by snowleopard** [comment]
> For info, on the "nothing to do" build, we are 3.7s and Make is 12.3s.

Yay! :-)

> That's terrible from both!

I may be wrong, but I think current implementation of `ArgsHashOracle` and `dependencies` are bottlenecks. To test without the former, you can set `trackBuildSystem = False` in `Settings/User.hs`.

**Comment by ndmitchell** [comment]
`unifyPath` is taking up 17% of the time according to profiling, because you call it 40 million times in a zero build. I suspect instead of normalising all paths at every step (easy to do but wasteful), you should normalise paths only as they arrive into the build system (e.g. from a user or a config file) and then `-/-` can be `x ++ '/' : y`, which is a lot cheaper.

**Comment by snowleopard** [comment]
The problem is that `</>` uses the Windows separator `\` even though we are working in MSYS, which leads to chaos: different parts of the file paths use different separators. I believe we can't just apply `unifyPath` to paths from the configuration file, because that's not the only source of file paths... 

However, the build system may work correctly even with `-/- = </>`, I think the reason I did all this was purely an aesthetic one: I didn't like the resulting build log. But then we could, perhaps, deal with it when printing. 

(It looks like having `newtype FilePath` would actually be quite helpful, as we would have a better control over where the file paths come from and where they are consumed.)

**Comment by ndmitchell** [comment]
In fact, 40 million seems just crazy. I'll trace them all - we may be duplicating huge pieces of work. If not, a newtype seems like a reasonable plan. Using / everywhere does seem sensible, even if not essential.

**Comment by snowleopard** [comment]
> In fact, 40 million seems just crazy. I'll trace them all - we may be duplicating huge pieces of work.

Yes, this does sound suspicious... That seems like thousands of `-/-` per output file. I think only `moduleFilesOracle` could be doing more than O(files) applications of `-/-`, but not that much.

**Comment by snowleopard** [comment]
@ndmitchell We can build profiled libraries. I've enabled profiling way by default, as in the old build system, but passing `--flavour=quick` disables it (also as before). So this will not affect your benchmarking. (If it does, please shout!)

**Comment by ndmitchell** [comment]
The GHC Profiler isn't the most accurate. Adding a real trace I see 120315 calls to unifyPath, operating on 5713 unique paths. So still a massive number of duplicates. Looking at the most common duplicates:

```
   6597 stage1\compiler
   6597 .build\stage1/compiler
   6422 stage0\compiler
   6422 .build\stage0/compiler
   4689 .build/stage1/compiler\package-data.mk
   4569 .build/stage0/compiler\package-data.mk
```

So Andrey, why do we append `stage1` and `compiler` 6597 times? Is this (and any other work nearby) something that could be pulled out into a CAF and shared?

**Comment by snowleopard** [comment]
Function `buildPath :: Context -> FilePath` is computing that and it is called from a lot of places.

Are you suggesting to cache it somehow?

We don't actually need to use a smart `-/-` in it, because it always operates on unified file paths.

**Comment by snowleopard** [comment]
@ndmitchell Have a look at the above commit. It uses `x ~/~ y = x ++ '/' : y` in all `Settings.Paths` functions, including `buildPath`. This should hopefully mitigate things to some extent.

**Comment by ndmitchell** [comment]
@snowleopard - I'll make some hacks for the paper which correctly and precisely capture the speedup we'll get, but are a disaster for code maintenance, to get some numbers. I suggest we revisit actual code improvements next week. The `~/~` should be a step forward, I'll benchmark later today.

**Comment by ndmitchell** [comment]
I think we managed to find equivalents, so this can now be shut. I've created https://github.com/snowleopard/shaking-up-ghc/issues/220 to track speeding it up.
