### ISSUE TITLE
needed CFLAGS not passed to c compiler?

### ISSUE THREAD

**Issue by hvr** [snowleopard/shaking-up-ghc#221]
Recently, GHC HEAD started requiring the c compiler being in C99 mode (and configure.ac augmented accordingly)

In fact I see that `system.config` picks up the required flag (needed for GCC 4.* -- clang & gcc 5 don't need any flags to be placed into C99 mode):

```hs
conf-cc-args-stage0         =  -std=gnu99 -D_THREAD_SAFE -fno-stack-protector
conf-cc-args-stage1         =  -std=gnu99 -D_THREAD_SAFE -fno-stack-protector
conf-cc-args-stage2         =  -std=gnu99 -D_THREAD_SAFE -fno-stack-protector

conf-cpp-args-stage0        =  -std=gnu99 -D_THREAD_SAFE
conf-cpp-args-stage1        =  -std=gnu99 -D_THREAD_SAFE
conf-cpp-args-stage2        =  -std=gnu99 -D_THREAD_SAFE
```

however, building GHC HEAD fails  because the CFLAGS weren't passed to the C compiler:

```
Error when running Shake build system:
* .build/stage1/rts/libHSrts_thr.a
* .build/stage1/rts/posix/Select.thr_o
* OracleQ (DependenciesKey (".build/stage1/rts/.dependencies",".build/stage1/rts/posix/Select.thr_o"))
* .build/stage1/rts/.dependencies
* .build/stage1/rts/sm/Evac_thr.c.deps
user error (Development.Shake.cmd, system command failed
Command: /usr/bin/gcc -E -MM -Iincludes -Iincludes/dist-derivedconstants/header -I.build/stage1/rts -I.build/stage1/rts/autogen -MF .build/stage1/rts/sm/Evac_thr.c.deps -MT .build/stage1/rts/sm/Evac_thr.o -x c .build/stage1/rts/sm/Evac_thr.c -Irts -I.build/stage1/rts -DRtsWay="rts_v" -O2 -funroll-loops -DPARALLEL_GC -Irts/sm
Exit code: 1
Stderr:
In file included from includes/Rts.h:30:0,
                 from .build/stage1/rts/sm/Evac_thr.c:15:
includes/Stg.h:30:3: error: #error __STDC_VERSION__ does not advertise C99 or later
 # error __STDC_VERSION__ does not advertise C99 or later
   ^
)
```

**Comment by snowleopard** [comment]
Thanks @hvr, this should be an easy fix. I'll take care of it.

**Comment by snowleopard** [comment]
@hvr I pushed a fix, could you test please? It works for me on Windows, but Travis fails with a timeout for some reason... Not sure where the 2x+ slowdown comes from, the Windows build is not affected.

**Comment by hvr** [comment]
@snowleopard I was about to try it, when I stumbled over #222 (cause on my current system the default `gcc` points to GCC 5, wherease the issue in #222 is clealry visible for GCC 4.*)

**Comment by hvr** [comment]
fwiw, the fix seems to have worked for the compile failure at hand; I haven't checked though if there are other places that may have not get the same flags as with the `make`-based system...

**Comment by snowleopard** [comment]
@hvr I'll close this now, but do reopen if you encounter any other missing CFLAGS.
