### ISSUE TITLE
CC executable name incorrectly mangled 

### ISSUE THREAD

**Issue by hvr** [snowleopard/shaking-up-ghc#222]
I just stumbled into this failure:

```
Error when running Shake build system:
* OracleQ (PackageDataKey (".build/stage1/compiler/package-data.mk",".build_stage1_compiler_COMPONENT_ID"))
* .build/stage1/compiler/package-data.mk
* compiler/stage1/package-data.mk
* .build/stage1/compiler/primop-vector-tycons.hs-incl
* .build/stage1/compiler/primops.txt
user error (Development.Shake.cmd, system command failed
Command: /usr/bin/gcc-4 -E -undef -traditional -P -Iincludes -Iincludes/dist-derivedconstants/header -I.build/stage1/compiler -x c compiler/prelude/primops.txt.pp
/usr/bin/gcc-4: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory))
```

even though `system.config` knows the proper executable name:

```
$ grep gcc-4 ./shake-build/cfg/system.config
gcc            = gcc-4.9
hs-cpp         = gcc-4.9
system-gcc     = gcc-4.9
```

**Comment by hvr** [comment]
btw, `gcc` doesn't seem like a variable name; coincidentally I've been working on https://phabricator.haskell.org/D2078 which tries to get rid of the misnamed `--with-gcc`/`WhatGccIsCalled` et in favor of the more generic "CC" style naming

**Comment by hvr** [comment]
The culprit seems to be

```hs
           fixAbsolutePathOnWindows $ path' -<.> exe
```

in `src/Builder.sh`

**Comment by ndmitchell** [comment]
I guess rather than removing any arbitrary extension it should be removing only `.exe` and `.EXE` trailing strings?

**Comment by snowleopard** [comment]
Oh, that's annoying. I'll fix this.

@ndmitchell Yes, I think so. I will `tolower . takeExtension` just in case.

**Comment by hvr** [comment]
@snowleopard even appying 'toLower'  on the extension sounds dangerous... e.g. consider if I had an executable called 'gcc.DEBUG' ... I'm wondering why you even need to transform the filename on windows at all. what would happen if you left the extension as is?

**Comment by snowleopard** [comment]
@hvr I agree about the name -- I was also thinking to rename it to `cc`. I'll create a separate issue on this.

**Comment by snowleopard** [comment]
@hvr Hmm, maybe I don't need to bother with adding `exe` extensions at all? I simply followed what the old build system did with `exeext`...

**Comment by snowleopard** [comment]
OK, apparently `-<.> exe` wasn't needed at all -- the above fix worked fine without it on my machine.

@hvr Hopefully, this fixes things for you too, so I'll close this issue.
