### ISSUE TITLE
C and Haskell compiler: builder and setting names

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#223]
At the moment the build system uses `gcc` and `ghc` to refer to the C and Haskell compilers used in the build process. However, in principle they don't necessarily have to be GCC and GHC. It therefore seems more logical to use generic names like `cc` (i.e. 'C compiler') and `hc`. This has been mentioned in #222.

One subtlety here is that different C or Haskell compilers will probably expect different command line arguments, so in general we will still need to distinguish them and provide explicit support for GCC/clang/etc, and similarly for different Haskell compilers. I'm not yet clear what would be the best way to do that in the current implementation. Hence this issue -- please share your ideas!

From the practical standpoint, however, a very simple solution may work well: the only alternative to `gcc` that we currently support is `clang` and the latter tries very hard to be as `gcc`-like as possible, hence we mostly pass the same arguments to both compilers. And furthermore, I think it would be unrealistic to expect that anything else than GHC will ever be able to compile it. Note thought that there may be several *versions* of GHC that we might want to support and which will expect different command line arguments.

Anyway, my current plan is to simply rename `gcc` to `cc` and `ghc` to `hc` everywhere in the build system. If you think this is not the best way forward, please shout!

**Comment by snowleopard** [comment]
As a first step I did the following renaming:
* `gcc` to `cc` in `system.config`
* `system-gcc` to `system-cc` in `system.config`
* `Gcc` to `Cc` in sources.
* `GccM` to `CcM` in sources.
There are still a few instances of `Gcc` found by `git grep Gcc` but they all follow conventions in the previous build system.

As the next step I intend to get rid of builder duplication, merging `Cc` and `CcM` (and other similar pairs) into something like `Cc CcMode`.

**Comment by Ericson2314** [comment]
It is indeed true that Clang tries to suffice as a drop-in replacement for GCC. That said, there are Clang-specific flags which yield a better way of expressing something than possible with the GCC-compatable flags alone. So such functionality, while certainly not necessary for building with Clang, can still come in handy.

**Comment by snowleopard** [comment]
@Ericson2314 Yes, I agree. The question is: what is the best way to provide support for different C compilers? At the moment we do have the following:
* `gcc-is-clang` and `gcc-lt-46` flags in `system.config`, where the former should probably be renamed to `cc-is-clang`.
* `GccIsClang` and `GccLt46` in sources, which allow to alter command lines by using `flag GccIsClang ?` conditions. Again, it makes sense to rename the former.

However, a better approach may be to embed the information about which C compiler we use into the datatype itself, i.e. to have `Cc CcMode CcVersion` or something similar, which will essentially mean we have a family of related C compilers.

**Comment by ggreif** [comment]
@snowleopard `gcc-is-clang` is probably named this way, because on Mac OS X `gcc` is simply a symlink to `clang`.

**Comment by snowleopard** [comment]
@ggreif Aha, I see, this makes sense. Indeed on Mac OS X instance of Travis we see the following:
```makefile
cc = /usr/bin/gcc
...
gcc-is-clang = YES
```

**Comment by hvr** [comment]
@snowleopard  I'd try to keep it generic, and just follow the traditional CC/CFLAGS/LDFLAGS scheme and have Autoconf handle figuring out which flags are needed... or does Shake really need to *know* which compiler is used?

**Comment by snowleopard** [comment]
@hvr I think I need a three-fold answer!

> I'd try to keep it generic, and just follow the traditional CC/CFLAGS/LDFLAGS scheme and have Autoconf handle figuring out which flags are needed...

Firstly, with the above commits in place, the `Cc` builder now stands for a generic C compiler, just as you want. There is a bit of additional structure though, which may be arguable: `Cc Compile` is what we use to compile sources, `Cc FindDependencies` is what we use to extract source dependencies. These are two logically separate tasks, and perhaps we should even have separate builders for them? It seems accidental that both tasks are implemented by the same executable. Furthermore, `Cc Compile StageN` is the C compiler we use in `StageN`.

>  or does Shake really need to *know* which compiler is used?

It's not about Shake specifically. In fact, you'll find that the make build system did this:
```makefile
ifneq "$(GccIsClang)" "YES"

# Debian doesn't turn -Werror=unused-but-set-variable on by default, so
# we turn it on explicitly for consistency with other users
ifeq "$(GccLT46)" "NO"
# Never set the flag on Windows as the host gcc may be too old.
ifneq "$(HostOS_CPP)" "mingw32"
SRC_CC_WARNING_OPTS += -Werror=unused-but-set-variable
endif
# gcc 4.6 gives 3 warning for giveCapabilityToTask not being inlined
SRC_CC_WARNING_OPTS += -Wno-error=inline
endif

else

# Don't warn about unknown GCC pragmas when using clang
SRC_CC_WARNING_OPTS += -Wno-unknown-pragmas

endif
```
So apparently not everything is handled by Autoconf in the old build system. Is this a bug? Maybe. I don't know, so I also use `GccIsClang` and `GccLT46` in Shake. Do you think we need to get rid of these flags and let Autoconf handle everything? Perhaps we should. But then to change the above warnings one would have to rerun the `configure` script, which sounds tedious.

Finally, there is hope, however remote, that one day we will be able to get rid of the Autoconf black magic that very few people can understand and maintain, incorporating all the complexity into the Shake build system, improving abstractions, portability and performance of the build system as the result. I'd be very keen on doing that eventually, which may mean that at some point we'll have to care about `gcc` vs `clang` distinction. This is certainly not on the agenda today, but we might keep this in mind for future.

**Comment by hvr** [comment]
The logical partition of the C compiler into operational mode and stage, that makes sense. And in some way this was already expressed in the Autoconf/Make setup by using different variables for each context.

So I do agree there's some structure here, but that still doesn't mean that Shake needs to know which version or compiler flavour we need. It just needs to know how the executable is named, and which flags to pass for each phase/mode-of-operation. This is a kind of "separation of concerns" or abstraction layering.

----

As to the Makefile fragment you quoted, yes I consider that a layering violation, and I'm currently trying to get rid of those in the current Makefile system so shakebuild doesn't have to inherit those technical debts... but it's a slow process and needs careful investigation to figure out if there's anything that breaks down if I rip out some superflous looking [awful pillar](http://geekandpoke.typepad.com/.a/6a00d8341d3df553ef013488b0aa31970c-pi)...

----

Finally, a very condensed answer to that "get rid of Autoconf" heresy :smiley: : I doubt we'll ever want to have to maintain a reimplemented clone the Autoconf functionality in GHC's buildsystem; I'm currently in the process of cleaning up our Autoconf scripts, and I really wouldn't want to have to reimplement all the scripts and subtle platform-specific hacks that Autoconf provides us out-of-the-box in Haskell just for the sake of Haskell. It's really no fun having to test each platform-specific feature-test on every platform we want to support, and it'd be way more work if you'd have to compile Haskell program rather than just copy over a portable `configure`-bash script. So in contrast to replacing our Makefiles with shake, I simply don't see a  long-term benefit of replacing Autoconf with Haskell-code :-)

**Comment by bgamari** [comment]
Herbert Valerio Riedel <notifications@github.com> writes:
> Finally, a very condensed answer to that "get rid of Autoconf" heresy
> :smiley: : I doubt we'll ever want to have to maintain a reimplemented
> clone the Autoconf functionality in GHC's buildsystem; I'm currently
> in the process of cleaning up our Autoconf scripts, and I really
> wouldn't want to have to reimplement all the scripts and subtle
> platform-specific hacks that Autoconf provides us out-of-the-box in
> Haskell just for the sake of Haskell. It's really no fun having to
> test each platform-specific feature-test on every platform we want to
> support, and it'd be way more work if you'd have to compile Haskell
> program rather than just copy over a portable `configure`-bash script.
> So in contrast to replacing our Makefiles with shake, I simply don't
> see a long-term benefit of replacing Autoconf with Haskell-code :-)
>
For what it's worth, I agree with Herbert here. It's easy to
underestimate the value that Autoconf offers. Yes, it's antiquated and a
bit cryptic but it has the advantage of literally decades of effort to
make things "just work" across a wide range of platforms.

The unfortunate truth here is that portability (especially between unix
flavors) is a frustratingly difficult thing to get right; every change
to this sort of code needs to be tested across a spectrum of platforms,
many of which we don't even have stable access to, each with its own
quirks. By dumping Autoconf we'd be taking on an enormous amount of
testing surface area and lose automatic support for countless odd
platform configurations, all in exchange for relatively few benefits.

**Comment by snowleopard** [comment]
> As to the Makefile fragment you quoted, yes I consider that a layering violation, and I'm currently trying to get rid of those in the current Makefile system so shakebuild doesn't have to inherit those technical debts... 

@hvr As a hypothetical example, I can see how one would want to pass an extra flag to `clang` when dealing with a particular source file, because `clang` fails to be completely identical to `gcc` and, say, produces a suboptimal result for that particular file. This would be impossible to achieve with the "separation of concerns" you propose. I'm therefore not convinced that a build system should be oblivious to the implementation of a particular builder -- this seems to be a leaky abstraction.

**Comment by hvr** [comment]
Fair enough, but if we go down this hypothetical road, then again you'd run into the class of problems that Autoconf's golden rule *"test for features not for versions"* solves in a principled way:

How do we know which versions of `clang` require or even support this different flag? Are we sure this flag is a good idea for future versions as well? Does `gcc`  need different special flags for some versions? Is this platform/arch specific? Are there any other  compilers which need specific flags? 

So even in this case we may actually want to leave to Autoconf the detection of which flags that particular file needs, and pass the make-system the respective special `CFLAGS` for that file. This gives us a chance to cover platforms and configurations we don't have easy acccess to, as well as future configurations.

(Fwiw, The dual scheme "test for versions not for features" is followed by CMake which needs a database of known tool/version configurations)

**Comment by snowleopard** [comment]
> Finally, a very condensed answer to that "get rid of Autoconf" heresy :smiley:

@hvr @bgamari To avoid highjacking this thread, let me invite you here: https://github.com/snowleopard/shaking-up-ghc/issues/227

**Comment by snowleopard** [comment]
I decided not to rename `ghc` to `hc` eventually. It is unlikely at this point that we will ever build GHC using any other Haskell compiler.
