### ISSUE TITLE
Linux Travis instance times out

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#229]
Not sure what happened but the full build now takes 2+ hours on Travis and is therefore terminated. It used to take around 1 hour previously. I had a brief look at build logs but couldn't figure out what has changed. 

Any ideas?

**Comment by ndmitchell** [comment]
I released shake-0.15.6 yesterday. Can you try requesting `shake-0.15.5`?

Which GHC are you using to bootstrap? There's a known bug in GHC 8 which leads to hangs - see https://ghc.haskell.org/trac/ghc/ticket/11830. Turning off `-I0` seems to help.

**Comment by snowleopard** [comment]
@ndmitchell We are bootstrapping with `ghc-7.10.3`. 

> I released shake-0.15.6 yesterday.

Great, I'll start migrating! But why do want me to request `shake-0.15.5`?

**Comment by ndmitchell** [comment]
Depending on how things are setup you might have migrated automatically as soon as the new Shake arrived. And I'm suggesting it may have been the automatic migration that broke things.

**Comment by ndmitchell** [comment]
Looking at it, the new Shake came out after the releases started timing out, so that's not the cause.

**Comment by snowleopard** [comment]
> Looking at it, the new Shake came out after the releases started timing out, so that's not the cause.

Yes, I don't think the problem is with Shake.

> Depending on how things are setup you might have migrated automatically as soon as the new Shake arrived. 

I've added diagnostic `ghc-pkg list` to CI scripts so that we know exactly which package versions we pick up. It turns out we are still using `shake-0.15.5` on CI. 

Shall we switch from `shake == 0.15.*` to `shake == 0.15.6` in the `.cabal` file? We'll then be able to use some nice new features of Shake.

**Comment by snowleopard** [comment]
Just spotted: even compiling the build system takes a huge time on Linux Travis instance. The Mac OS X instance is much faster for some reason...

Command `./ghc/shake-build/build.sh selftest` currently takes `815.12s` (most time spent on compilation) on Linux and only `29.00s` on Mac OS X. Where does the 28x slow-down come from?

**Comment by ndmitchell** [comment]
Perhaps https://github.com/travis-ci/travis-ci/issues/5623 is relevant - you are using Docker. I find that makes builds with GHC massively slower. Did you switch to Docker around that point? Anything else changed around the difference?

**Comment by snowleopard** [comment]
Hmm, interesting. I didn't switch to Docker explicitly. But looking at the build logs, previously successful builds were running on Docker too. It still makes sense to try building with `sudo: true` to see what happens; I'll give it a try.

**Comment by snowleopard** [comment]
Seems to be working -- selftest now took only `22.52s`!

Thanks @ndmitchell, I think you've solved the issue.

**Comment by ndmitchell** [comment]
Can you put measurements on the travis-ci/travis-ci#5623 ticket. In the blog post the Travis people claimed "equivalent performance" plus lower startup times and access to a cache. The second are true, but the first seems demonstrably false (at least for GHC, which might be doing something funky).

**Comment by snowleopard** [comment]
Sure, we'll do.

**Comment by snowleopard** [comment]
Wow, the whole Linux build is now complete in 34 min 48 sec (in `quick` flavour). That's definitely a record.

**Comment by snowleopard** [comment]
Thanks to this change we can now also fit full Mac OS X build in the time limit.

**Comment by ndmitchell** [comment]
Woohoo!
