### ISSUE TITLE
What needs to be done to drop `make inplace/bin/ghc-cabal`?

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#23]
The README.md lists
```
$ make inplace/bin/ghc-cabal
```
as need to be fixed. Can I tap into any existing knowledge why this step needed?
What would need to change to be able to build `ghc-cabal` with shake again?

**Comment by quchen** [comment]
@angerman I think #18 is already about this.

**Comment by angerman** [comment]
@quchen you are right. Thanks.

**Comment by snowleopard** [comment]
Actually I believe I have fixed this already: we can now build `ghc-cabal`, see #5. Hence I believe we can remove the `make inplace/bin/ghc-cabal` step from the instructions now.

We still rely on `make` for building some important bits though, e.g. #22, so other similar steps may be needed there.

#18 is a longer term goal where we will get rid of `ghc-cabal` executable completely.

**Comment by snowleopard** [comment]
I'll reopen the issue for someone to verify that `make inplace/bin/ghc-cabal` is not needed on Linux. I verified that it's not needed on Windows.

**Comment by bgamari** [comment]
Indeed this works for me.
