### ISSUE TITLE
Grammar in paper

### ISSUE THREAD

**Issue by ggreif** [snowleopard/shaking-up-ghc#231]
In your "Non-recursive make considered harmful" paper at bottom of p. 5:

"should depends on" ---> depend

**Comment by snowleopard** [comment]
Thank you! :-)

Fixed now: https://github.com/ndmitchell/shake-paper/commit/9c968fc8ce9717bb85e396e851c647a9bcb72187.

Here is the paper's repo: https://github.com/ndmitchell/shake-paper.
