### ISSUE TITLE
Add "On OS X" section to the README.md

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#24]
Currently sections of Linux and Windows are present.
A third one for OS X (maybe completely identical to linux),
as well as one for ghc with the llvm backend on OS X would be a good addition.

I will document my findings and extend the README.md, once I know what
the steps involved are.

**Comment by snowleopard** [comment]
@angerman Thank you. Can you assign this issue to yourself so that people can easily find unattended issues in the list?

**Comment by angerman** [comment]
Now, this is going to sound stupid, but how do I asking the ticket to myself? It's all grayed out on the right.

**Comment by snowleopard** [comment]
OK, apparently only collaborators can be assigned to an issue. I've added you to the list and assigned this issue to you.

Please keep using pull requests (don't push to this branch to avoid confusion).

**Comment by angerman** [comment]
I think this has been fixed already.
