### ISSUE TITLE
Simplify import conventions

### ISSUE THREAD

**Issue by bgamari** [snowleopard/shaking-up-ghc#33]
Currently the codebase has many modules re-exporting other modules. Not only does this make it difficult for the developer to know the "proper" way to import a given definition, but it makes import cycles almost inevitable due to the more dense module dependency graph.

**Comment by quchen** [comment]
A **very** big +1 to that.

**Comment by snowleopard** [comment]
Sigh. 

I agree. I tried to minimise the import clutter at some point, but it just made things more complicated.

> I think a module should never export modules other than its own submodules.

So, is this proposal to get rid of re-exports completely or only partially?

**Comment by bgamari** [comment]
I would say that re-exports should be limited to "children" of the re-exporting module. E.g. `Oracles` can re-export definitions from `Oracles.*`, but nothing else (without careful consideration, that is).

**Comment by snowleopard** [comment]
@bgamari OK, this sounds reasonable. Would you like to give it a try?

**Comment by bgamari** [comment]
Sure.

**Comment by snowleopard** [comment]
I'll close this. Imports/reexports are much more sane now thanks to #36.
