### ISSUE TITLE
Implement build rules for `includes`

### ISSUE THREAD

**Issue by snowleopard** [snowleopard/shaking-up-ghc#39]
See #16.

The following files need to be generated:
* ~~`includes/ghcautoconf.h`~~ Done: 6b7b9cc.
* ~~`includes/ghcplatform.h`~~ Done: 8c32f2c.
* `includes/ghcversion.h`: WIP @angerman.
* ~~`includes/dist-derivedconstants/header/DerivedConstants.h`~~ Done: c6cfb36.
* ~~`includes/dist-derivedconstants/header/GHCConstantsHaskellType.hs`~~ Done: c6cfb36.
* ~~`includes/dist-derivedconstants/header/platformConstants`~~ Done: c6cfb36.
* ~~`includes/dist-derivedconstants/header/GHCConstantsHaskellWrappers.hs`~~ Done: c6cfb36.
* ~~`includes/dist-derivedconstants/header/GHCConstantsHaskellExports.hs`~~ Done: c6cfb36.

Please add other `includes` files that need attention to the above list.

**Comment by snowleopard** [comment]
As the first step I improved the infrastructure we have for generated files: now generators live in directory `Rules/Generators/` and we track changes in them. The relevant commit: 8c3022d.

**Comment by snowleopard** [comment]
We can now generate `includes/ghcautoconf.h` :6b7b9cc.

**Comment by angerman** [comment]
Going to give this a try shortly.

**Comment by angerman** [comment]
Now we are missing `includes/ghcplatform.h" :-)

**Comment by snowleopard** [comment]
@angerman Done :-) See 8c32f2c.

That's probably enough for today. The next one is `includes/ghcversion.h`. I'll work on it tomorrow unless anyone picks it up earlier.

**Comment by angerman** [comment]
Ha, I was just going to give this a try. Well done! I’ll see if I can get `includes/ghcversion.h` then :D

**Comment by snowleopard** [comment]
@angerman Thanks! All infrastructure is in place, so this should be fairly straightforward, but a bit tedious.

**Comment by snowleopard** [comment]
Another file to generate: `includes/dist-derivedconstants/header/GHCConstantsHaskellExports.hs` (#53).

**Comment by angerman** [comment]
> Another file to generate: includes/dist-derivedconstants/header/GHCConstantsHaskellExports.hs (#53).
Wouldn't that live in `compiler/includes/dist-derivedconstants/header/GHCConstantsHaskellExports.hs`?

**Comment by snowleopard** [comment]
@angerman I don't see any `includes` directory in `compiler`.

I think we are talking about `includes/dist-derivedconstants/header/GHCConstantsHaskellExports.hs`.

**Comment by snowleopard** [comment]
OK, I think I've done all `includes` apart from `includes/ghcversion.h`.

@angerman, this is now up to you to finish :-)

**Comment by angerman** [comment]
Adding pressure. I see. Alright, I'll give it a show now.

**Comment by snowleopard** [comment]
There may be some other files we missed, but I'm closing this for now.

**Comment by snowleopard** [comment]
I've done a test build, everything works fine. However, we are not needing `includes/ghcversion.h` anywhere in the system yet.
