### ISSUE TITLE
Use Gitter?

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#40]
Should we add a semi-realtime medium? I know that begriffs/postgrest uses Gitter. (https://gitter.im)

**Comment by snowleopard** [comment]
Good idea, I'll give it a try once I have some non-interrupted coding time.

**Comment by angerman** [comment]
I just gave this a try, it generated #41

**Comment by quchen** [comment]
What's the advantage over IRC? That's where everyone I know is, it's non-centralized and non-owned by someone. UI isn't as fancy, but other than that?

**Comment by angerman** [comment]
@quchen not much. It *does* give trivial history though, and some github activity on the side. You brought up IRC in #1 already; which didn't gain any traction. As begriffs/postgrest used gitter, I just wanted to leave this here. It's up of course up for debate.

**Comment by bgamari** [comment]
For what it's worth I am generally always on IRC but try to avoid Gitter. The latter's notification mechanism leaves much to be desired.

**Comment by angerman** [comment]
I'm fine with either. @snowleopard can we get you onto irc as well?

**Comment by angerman** [comment]
Alright. We are on irc. irc://chat.freenode.net/shaking-up-ghc :100:
