### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by quchen** [snowleopard/shaking-up-ghc#43]
Once we reach a half-decent state of stability, we should add continuous integration. This would provide us with a "standard" build that other builds can be compared to. Right now, we've got loosely coupled Windows, OSX, and Linux builds, and everyone is a little bit in his own bubble. Travis seems like the standard solution.

**Comment by snowleopard** [comment]
Completely agree! I've never used Travis, so it'll take me some time to work it out. I'll appreciate any help with this.

**Comment by angerman** [comment]
Looking at `shake`[1], we can apparently do `windows` ci on `appvoyer`?
Anyone experience with that?

[1]: https://github.com/ndmitchell/shake

**Comment by snowleopard** [comment]
@angerman Thanks for the pointer. I'll look into this once more critical issues are out of the way.

**Comment by angerman** [comment]
Maybe @quchen and @bgamari can take over? @quchen has this assigned already, and @bgamari has an open PR for travis.

To my understanding Travis can do Linux (and Mac - Beta Feature I think), and [appveyor](https://ci.appveyor.com) can do Window. So we should have the three most common platforms covered.
Not sure about architectures though.

**Comment by quchen** [comment]
I'm only familiar with Travis, and @bgamari has done the required work already in his pull request. I've never used Windows CI.

**Comment by snowleopard** [comment]
@quchen I believe @bgamari's pull request is still work in progress.

**Comment by bgamari** [comment]
Andrey Mokhov <notifications@github.com> writes:

> @quchen I believe @bgamari's pull request is still work in progress.
>
Indeed it is. I haven't had time to keep poking away at it this week.

**Comment by quchen** [comment]
#93 should do the trick for now.
