### ISSUE TITLE
inplace/lib/template-hsc.h not created

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#44]
This is just a copy of `utils/hsc2hs/template-hsc.h`. See #35

**Comment by snowleopard** [comment]
This is easy to implement, but do we really need two identical files in the build system?

**Comment by snowleopard** [comment]
I've implemented the build rule: 6863e5e.

It's still unclear whether a single `template-hsc.h` file could be used instead. This might have something to do with the fact that we want to be able to run `hsc2hs` outside the build system.

**Comment by snowleopard** [comment]
Another relevant commit: 43b6cc3.
