### ISSUE TITLE
Implement support for unlit

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#83]
For #81 (`ghc-split`), we need #82 (`build-perl`), which in turn requires `unlit`. Hence we need `unlit`, the unliterizer tool (turns `lprl` literate perl files into `prl` files when used in `build-perl`).

**Comment by snowleopard** [comment]
What is the purpose of `ghc-split`? Any chance to get rid of it and associated dependencies given that we now have the full power of Haskell in the build system?

**Comment by snowleopard** [comment]
The `ghc-split.prl` file looks quite complicated, we probably don't want to do translate this in Haskell now. 

I think GHC uses `ghc-split` for splitting objects when executed with `-split-objs` flag.

**Comment by angerman** [comment]
Yes. translating `ghc-split.lprl` looks like a non trivial task. Eep. to get it right :)

The best I found was this SO answer[1], which links to the GHC manual[2].

[1]: http://stackoverflow.com/questions/9198112/haskell-unnecessary-binary-growth-with-module-imports/9198223#9198223
[2]: https://downloads.haskell.org/~ghc/7.4.1/docs/html/users_guide/options-phases.html#id3081262

**Comment by snowleopard** [comment]
This means there is a temporary workaround: you can set `splitObjects` to `return False` locally and see how far this will get you in the build.

**Comment by angerman** [comment]
That's what I just did.

Now I'm stuck at `gmp` again(?). 
```
| Copy gmp.h -> libraries/integer-gmp/gmp/gmp.h
| Copy .libs/libgmp.a -> libraries/integer-gmp/gmp/libgmp.a
| Successfully build custom library 'integer-gmp'
/----------
| Running Gcc Stage1 (package = integer-gmp):
|     input: libraries/integer-gmp/cbits/wrappers.c
| => output: libraries/integer-gmp/stage1/build/cbits/wrappers.o
\----------

/----------
| Running Ld (stage = Stage1, package = integer-gmp):
|     input: libraries/integer-gmp/stage1/build/cbits/wrappers.o (and 5 more)
| => output: libraries/integer-gmp/stage1/build/HSinteger-gmp-1.0.0.0.o
\----------

shakeArgsWith         0.002s    0%                           
Function shake        0.028s    0%                           
Database read         0.320s    0%                           
Database compression  0.087s    0%                           
With database         0.009s    0%                           
Running rules       148.557s   99%  =========================
Total               149.002s  100%                           
Error when running Shake build system:
* utils/hpc/stage1/build/tmp/hpc-bin
* libraries/integer-gmp/stage1/build/libHSinteger-gmp-1.0.0.0.a
* getDirectoryFiles  [libraries/integer-gmp/gmp/objs/*.o]
libraries/integer-gmp/gmp/objs: getDirectoryContents: does not exist (No such file or directory)
```

**Comment by snowleopard** [comment]
Looks like we are missing a `need [integerGmpLibrary]` before `getDirectoryFiles`.

**Comment by angerman** [comment]
The strange thing is, it's actually being built right before that step. I think we just somehow do not end up putting the object files into `objs`. I'll have to look into where the original `Makefile` did that, and we missed it.

**Comment by snowleopard** [comment]
I see. To get more informative error messages I think we better insert an appropriate `need` before every invocation of `getDirectoryFiles`.

**Comment by angerman** [comment]
Great. It's exactly the TODO comments I left in `Rules/IntegerGmp.hs:105`+.
