### ISSUE TITLE
-split-objs not supported (yet)

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#84]
I just want to hold this here. We currently do *not* support the `-split-objs` feature of build `ghc`s. 
This depends on #83, #82 and #81. See also the Linkage Optimization [1] item in the wiki.

[1]: https://wiki.haskell.org/HSFFIG/Linkage_optimization

**Comment by angerman** [comment]
I belive, over the long run we will need to support `-split-objs` and all the dependencies that come with it: `unlit`, `perl`, ...

**Comment by snowleopard** [comment]
I added a proper way to control `splitObjects` in `Settings/User.hs`:
```haskell
-- To switch off split objects change to 'return False'
splitObjects :: Predicate
splitObjects = return False -- FIXME: should be defaultSplitObjects, see #84.
```
