### ISSUE TITLE
iserv-bin configuration fails

### ISSUE THREAD

**Issue by bgamari** [snowleopard/shaking-up-ghc#9]
```
Configuring iserv-bin-0.0...
/--------
| Running GhcPkg 1 with arguments:
|   update
|   --force
|   iserv/dist-install/inplace-pkg-config
\--------
Reading package info from "iserv/dist-install/inplace-pkg-config" ... ghc-pkg: iserv/dist-install/inplace-pkg-config: openBinaryFile: does not exist (No such file or directory)
Error when running Shake build system:
* iserv/dist-install/doc/html/iserv-bin/iserv-bin.haddock
* OracleQ (PackageDataKey ("iserv/dist-install/package-data.mk","iserv_dist-install_HS_SRC_DIRS"))
* iserv/dist-install/package-data.mk
* iserv/dist-install/package-data.mk iserv/dist-install/haddock-prologue.txt iserv/dist-install/setup-config iserv/dist-install/build/autogen/cabal_macros.h
user error (Development.Shake.cmd, system command failed
Command: /opt/exp/ghc/ghc/inplace/bin/ghc-pkg update --force iserv/dist-install/inplace-pkg-config
Exit code: 1
Stderr:
ghc-pkg: iserv/dist-install/inplace-pkg-config: openBinaryFile: does not exist (No such file or directory)
)

```
Still trying to work out why.

**Comment by bgamari** [comment]
The reason here appears to be that `iserv` has no `Library` component and `ghc-cabal` only produces `inplace-pkg-config` for packages with library components.

**Comment by bgamari** [comment]
I think all of this stems from the fact that `Settings.isLibrary` is fragile at best. @snowleopard, shouldn't the nature of a package be declared explicitly?

**Comment by snowleopard** [comment]
@bgamari Agreed. If you look into Package.hs, you'll see that I planned to add `pkgType :: PackageType` field to differentiate packages better. However it was not clear to me at that point which package types we want and whether types are mutually exclusive. Is this just `data PackageType = Program | Library`?

Any thoughts on this?

**Comment by bgamari** [comment]
@snowleopard strictly speaking it's a bit of a false-dichotomy. A Cabal package consists of one or more components. These may either be Library components (of which there is at most one) or (one or more) Executable components.

**Comment by snowleopard** [comment]
@bgamari I see. It looks though that in the GHC build system every package can be considered either a `Library` (in which case we generate a bunch of object/library files) or a `Program` (in which case we generate an executable or several executables in case of `iserv`). Is this correct? If yes, we can stick to the current design but, perhaps, make defaultProgramPath depend on Way in addition to Stage and Package.

We may want to be more ambitious and handle all possible cabal packages eventually, but this could be postponed.

By the way `make` didn't build `iserv` on my machine. Is it Linux specific?

**Comment by bgamari** [comment]
> We may want to be more ambitious and handle all possible cabal packages eventually, but this could be postponed.

Yes, but I am wondering whether it might be worth doing it the right way from the start. Ultimately it doesn't seem that much harder and it seems ill-advised to have the build system's data model not match that of Cabal. Regardless, I've implemented the explicit approach in #8.

> By the way make didn't build iserv on my machine. Is it Linux specific?

Hmm, at one point it was broken on Windows but Simon Marlow said he fixed it before merging it. Perhaps you need to pull or rerun `boot`?

**Comment by snowleopard** [comment]
Thanks for implementing `PackageType` etc! If you don't mind I'll rename `setPkgType` to `setType` for consistency with `setPath`.

Shall we consider this issue closed now? We'll come back to proper support of cabal packages at some point.

I'll try to get `iserv` working on my machine.

**Comment by bgamari** [comment]
I've opened #12 to track this potential refactoring. This can now be closed.
