### ISSUE TITLE
Add more labels

### ISSUE THREAD

**Issue by angerman** [snowleopard/shaking-up-ghc#99]
Can we have `stage`, `stage2`, `cross`(or `crosscompiler`, which is quite long), `win`, `linux`, `OS X` as labels, to better separate the issues?

**Comment by snowleopard** [comment]
Good idea. Done! If any other labels are needed, just shout.

**Comment by snowleopard** [comment]
Also adding way-specific labels: `profiling`, `dynamic`, `threaded`, `debug`.
